-- Gen2Rev challenge ingest: 1 Kings (World 11), 2 Kings (World 12),
-- 1 Chronicles (World 13), 2 Chronicles (World 14)
-- Generated from docs/content/{1-kings,2-kings,1-chronicles,2-chronicles}.md
-- All four books: theological review approved/approved-with-changes, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md, docs/QA_SIGNOFF.md, both 2026-08-08/09).

with w as (select id from public.world where book_slug = '1-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s request to Yahweh at Gibeon.', '1 Kings 3:9', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?', 'WEB', 1,
   '{"type": "recall", "template": "Give your servant therefore an ___ heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?", "answer": "understanding"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: where Yahweh appeared to Solomon and offered to give him anything he asked.', '1 Kings 3:5', 'In Gibeon, Yahweh appeared to Solomon in a dream by night; and God said, ''Ask for what I should give you.''', 'WEB', 1,
   '{"type": "recall", "template": "In Gibeon, Yahweh appeared to Solomon in a ___ by night; and God said, ''Ask for what I should give you.''", "answer": "dream"}', false, 2),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 3:5-14, what did Solomon ask Yahweh for instead of long life, riches, or victory over his enemies?', '1 Kings 3:9', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["An understanding heart to judge the people", "Long life", "Riches", "The lives of his enemies"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s ruling in the case of the two women and the living child.', '1 Kings 3:25', 'The king said, ''Divide the living child in two, and give half to the one, and half to the other.''', 'WEB', 1,
   '{"type": "recall", "template": "The king said, ''Divide the living child in two, and give half to the one, and half to the ___.''", "answer": "other"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 3:27-28, how did the people respond to the king''s judgment?', '1 Kings 3:27-28', 'Then the king answered, ''Give the first woman the living child, and definitely do not kill him. She is his mother.'' All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of God was in him to do justice.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["They feared the king, for they saw that the wisdom of God was in him", "They asked Solomon to divide the kingdom", "They rejected Solomon''s ruling", "They demanded a retrial before the elders"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word describing what filled Yahweh''s house at the temple dedication.', '1 Kings 8:10-11', 'It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled Yahweh''s house.', 'WEB', 2,
   '{"type": "recall", "template": "It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s ___ filled Yahweh''s house.", "answer": "glory"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s dedication prayer, on whether God can be contained.', '1 Kings 8:27', 'But will God in very deed dwell on the earth? Behold, heaven and the heaven of heavens can''t contain you; how much less this house that I have built!', 'WEB', 3,
   '{"type": "recall", "template": "But will God in very deed dwell on the earth? Behold, heaven and the heaven of heavens can''t contain you; how much less this ___ that I have built!", "answer": "house"}', true, 7),
  ((select id from w), 'sequence', 'Put these beats of the temple''s dedication in the order they happen in the text.', '1 Kings 8:10-11; 8:29', 'It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled Yahweh''s house.; That your eyes may be open toward this house night and day, even toward the place of which you have said, ''My name shall be there.''', 'WEB', 3,
   '{"type": "sequence", "items": ["The ark of the covenant is brought into the temple", "The cloud fills Yahweh''s house so the priests cannot continue ministering", "Solomon prays, asking that Yahweh''s eyes be open toward this house night and day"], "correct_order": [0, 1, 2]}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word from the northern tribes'' request to Rehoboam.', '1 Kings 12:4', 'Your father made our yoke difficult. Now therefore make the hard service of your father, and his heavy yoke which he put on us, lighter, and we will serve you.', 'WEB', 1,
   '{"type": "recall", "template": "Your father made our yoke difficult. Now therefore make the hard service of your father, and his heavy yoke which he put on us, lighter, and we will ___ you.", "answer": "serve"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 12:16, what did the northern tribes say when Rehoboam refused their request?', '1 Kings 12:16', 'When all Israel saw that the king didn''t listen to them, the people answered the king, saying, ''What portion have we in David? ... To your tents, Israel!''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["''What portion have we in David? ... To your tents, Israel!''", "''We will serve you forever, our king.''", "''Let us make Rehoboam king over all Israel.''", "''We shall return to Egypt.''"], "correct_index": 0}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word from Elijah''s challenge to the people on Mount Carmel.', '1 Kings 18:21', 'How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.', 'WEB', 2,
   '{"type": "recall", "template": "How long will you ___ between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.", "answer": "waver"}', false, 11),
  ((select id from w), 'sequence', 'Put these five scenes of 1 Kings in the order they happen in the book.', '1 Kings 3:9; 3:27-28; 8:10-11; 12:16; 18:38-39', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?; Then the king answered, ''Give the first woman the living child, and definitely do not kill him. She is his mother.'' All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of God was in him to do justice.; It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled Yahweh''s house.; When all Israel saw that the king didn''t listen to them, the people answered the king, saying, ''What portion have we in David? ... To your tents, Israel!''; Then Yahweh''s fire fell and consumed the burnt offering, the wood, the stones, and the dust; and it licked up the water that was in the trench. When all the people saw it, they fell on their faces. They said, ''Yahweh, he is God! Yahweh, he is God!''', 'WEB', 5,
   '{"type": "sequence", "items": ["Solomon asks Yahweh for an understanding heart to govern well (1 Kings 3)", "Solomon settles the dispute between the two women claiming the same child (1 Kings 3)", "Solomon builds and dedicates the temple in Jerusalem (1 Kings 6, 8)", "The kingdom splits into Israel and Judah after Rehoboam''s harsh response (1 Kings 12)", "Elijah defeats the prophets of Baal at Mount Carmel (1 Kings 18)"], "correct_order": [0, 1, 2, 3, 4]}', true, 12)
;

with w as (select id from public.world where book_slug = '2-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what Elisha asked Elijah for before Elijah was taken from him.', '2 Kings 2:9', '''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''', 'WEB', 1,
   '{"type": "recall", "template": "''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a ___ portion of your spirit be on me.''", "answer": "double"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 2:11, what appeared as Elijah was taken up from Elisha?', '2 Kings 2:11', 'As they continued on and talked, behold, a chariot of fire and horses of fire separated them; and Elijah went up by a whirlwind into heaven.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A chariot of fire and horses of fire", "A pillar of cloud by day", "An earthquake and a strong wind", "A flock of ravens"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing name: who the sons of the prophets recognized Elijah''s spirit now rested on.', '2 Kings 2:15', 'When the sons of the prophets who were at Jericho facing him saw him, they said, ''The spirit of Elijah rests on Elisha.''', 'WEB', 2,
   '{"type": "recall", "template": "When the sons of the prophets who were at Jericho facing him saw him, they said, ''The spirit of Elijah rests on ___.''", "answer": "Elisha"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: who Assyria carried away to Assyria after capturing Samaria.', '2 Kings 17:5-6', 'The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried Israel away to Assyria.', 'WEB', 1,
   '{"type": "recall", "template": "The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried ___ away to Assyria.", "answer": "Israel"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 17:7, why does the text say the fall of Israel happened?', '2 Kings 17:7', 'It was so because the children of Israel had sinned against Yahweh their God... and had feared other gods.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Because Israel had sinned against Yahweh and feared other gods", "Because Assyria simply had a larger army", "Because Israel refused to pay a yearly tax", "Because of a drought and famine"], "correct_index": 0}', true, 5),
  ((select id from w), 'recall', 'Fill in the missing word from Hezekiah''s prayer for deliverance from Assyria.', '2 Kings 19:19', 'Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.', 'WEB', 1,
   '{"type": "recall", "template": "Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God ___.", "answer": "alone"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: where Sennacherib went and lived after the Assyrian camp was struck.', '2 Kings 19:35-36', 'That night, Yahweh''s angel went out and struck one hundred eighty-five thousand in the camp of the Assyrians... So Sennacherib king of Assyria departed, went home, and lived at Nineveh.', 'WEB', 3,
   '{"type": "recall", "template": "That night, Yahweh''s angel went out and struck one hundred eighty-five thousand in the camp of the Assyrians... So Sennacherib king of Assyria departed, went home, and lived at ___.", "answer": "Nineveh"}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what Hilkiah told Shaphan he had found in Yahweh''s house.', '2 Kings 22:8', 'Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.', 'WEB', 1,
   '{"type": "recall", "template": "Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the ___ in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.", "answer": "law"}', false, 8),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 22:11, what did Josiah do when he heard the words of the book of the law?', '2 Kings 22:11', 'When the king had heard the words of the book of the law, he tore his clothes.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["He tore his clothes", "He ignored the scroll", "He ordered a feast", "He rebuilt the temple immediately"], "correct_index": 0}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word from Josiah''s covenant renewal before Yahweh.', '2 Kings 23:3', 'The king stood by the pillar and made a covenant before Yahweh to walk after Yahweh and to keep his commandments, his testimonies, and his statutes with all his heart and all his soul... and all the people agreed to the covenant.', 'WEB', 2,
   '{"type": "recall", "template": "The king stood by the pillar and made a covenant before Yahweh to walk after Yahweh and to keep his commandments, his testimonies, and his statutes with all his ___ and all his soul... and all the people agreed to the covenant.", "answer": "heart"}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: whose king''s servant, Nebuzaradan, came to Jerusalem and burned it.', '2 Kings 25:8-9', 'Nebuzaradan the captain of the guard, a servant of the king of Babylon, came to Jerusalem. He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem.', 'WEB', 1,
   '{"type": "recall", "template": "Nebuzaradan the captain of the guard, a servant of the king of ___, came to Jerusalem. He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem.", "answer": "Babylon"}', false, 11),
  ((select id from w), 'sequence', 'Put these five scenes of 2 Kings in the order they happen in the book.', '2 Kings 2:11; 17:5-6; 19:19; 22:8; 25:8-9', 'As they continued on and talked, behold, a chariot of fire and horses of fire separated them; and Elijah went up by a whirlwind into heaven.; The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried Israel away to Assyria.; Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.; Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.; Nebuzaradan the captain of the guard, a servant of the king of Babylon, came to Jerusalem. He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem.', 'WEB', 5,
   '{"type": "sequence", "items": ["Elijah is taken up in a whirlwind and Elisha succeeds him as prophet (2 Kings 2)", "The northern kingdom, Israel, falls to Assyria after persistent idolatry (2 Kings 17)", "Hezekiah prays in the temple during Assyria''s siege of Jerusalem, and the siege ends (2 Kings 18-19)", "Josiah''s workers rediscover the book of the law, and Josiah renews the covenant (2 Kings 22-23)", "Babylon conquers Jerusalem, burns the temple, and carries the people into exile (2 Kings 25)"], "correct_order": [0, 1, 2, 3, 4]}', true, 12)
;

with w as (select id from public.world where book_slug = '1-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing name: the second name in 1 Chronicles'' opening genealogy.', '1 Chronicles 1:1', 'Adam, Seth, Enosh,', 'WEB', 1,
   '{"type": "recall", "template": "Adam, ___, Enosh,", "answer": "Seth"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what David was moved to take, per 1 Chronicles 21:1.', '1 Chronicles 21:1', 'Satan stood up against Israel, and moved David to take a census of Israel.', 'WEB', 1,
   '{"type": "recall", "template": "Satan stood up against Israel, and moved David to take a ___ of Israel.", "answer": "census"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what Gad directed David to build on Ornan''s threshing floor.', '1 Chronicles 21:18', 'Yahweh''s angel commanded Gad to tell David that David should go up and raise an altar to Yahweh on the threshing floor of Ornan the Jebusite.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh''s angel commanded Gad to tell David that David should go up and raise an ___ to Yahweh on the threshing floor of Ornan the Jebusite.", "answer": "altar"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: the stated reason Yahweh''s word gave David for why he could not build the temple.', '1 Chronicles 22:7-8', 'As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my sight.''', 'WEB', 3,
   '{"type": "recall", "template": "As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my ___.''", "answer": "sight"}', true, 4),
  ((select id from w), 'recall', 'Fill in the missing word from David''s charge to Solomon to be strong and courageous.', '1 Chronicles 28:20', 'Be strong and courageous, and do it. Don''t be afraid, nor be dismayed, for Yahweh God, even my God, is with you.', 'WEB', 1,
   '{"type": "recall", "template": "Be strong and courageous, and do it. Don''t be ___, nor be dismayed, for Yahweh God, even my God, is with you.", "answer": "afraid"}', false, 5),
  ((select id from w), 'sequence', 'Put these temple-preparation beats in the order they happen in 1 Chronicles.', '1 Chronicles 22:7-8; 22:14; 28:9-10; 29:14', 'As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my sight.''; In my affliction I have prepared for Yahweh''s house one hundred thousand talents of gold, one million talents of silver, and bronze and iron without weight... I have also prepared timber and stone.; You, Solomon my son, know the God of your father, and serve him with a perfect heart and with a willing mind... Take heed now, for Yahweh has chosen you to build a house for the sanctuary. Be strong, and do it.; But who am I, and what is my people, that we should be able to offer so willingly as this? For all things come from you, and we have given you of your own.', 'WEB', 3,
   '{"type": "sequence", "items": ["David is told by Yahweh''s own word that he cannot build the temple because he is a man of war", "David gathers massive quantities of gold, silver, bronze, iron, timber, and stone for Solomon to use", "David charges Solomon publicly before the assembly of Israel to build the temple", "The people give generously toward the temple, and David prays that all things come from Yahweh"], "correct_order": [0, 1, 2, 3]}', true, 6)
;

with w as (select id from public.world where book_slug = '2-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 7:1, what happened right after Solomon finished praying at the temple dedication?', '2 Chronicles 7:1', 'Now when Solomon had finished praying, fire came down from heaven and consumed the burnt offering and the sacrifices; and Yahweh''s glory filled the house.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Fire came down from heaven and consumed the sacrifice", "The ark disappeared from the temple", "An earthquake shook Jerusalem", "The priests began to sing a new song"], "correct_index": 0}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what filled God''s house at Solomon''s temple dedication.', '2 Chronicles 5:13-14', 'The trumpeters and singers were as one, to make one sound to be heard in praising and thanking Yahweh... the house was filled with a cloud, even Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled God''s house.', 'WEB', 1,
   '{"type": "recall", "template": "The trumpeters and singers were as one, to make one sound to be heard in praising and thanking Yahweh... the house was filled with a cloud, even Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s ___ filled God''s house.", "answer": "glory"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word from the people''s song of thanks when the fire fell on Solomon''s altar.', '2 Chronicles 7:3', 'All the children of Israel looked on, when the fire came down, and Yahweh''s glory was on the house. They bowed themselves with their faces to the ground on the pavement, worshiped, and gave thanks to Yahweh, saying, ''For he is good, for his loving kindness endures forever!''', 'WEB', 2,
   '{"type": "recall", "template": "All the children of Israel looked on, when the fire came down, and Yahweh''s glory was on the house. They bowed themselves with their faces to the ground on the pavement, worshiped, and gave thanks to Yahweh, saying, ''For he is good, for his loving kindness endures ___!''", "answer": "forever"}', true, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what Hezekiah did to the doors of Yahweh''s house in the first year of his reign.', '2 Chronicles 29:3', 'In the first year of his reign, in the first month, he opened the doors of Yahweh''s house and repaired them.', 'WEB', 1,
   '{"type": "recall", "template": "In the first year of his reign, in the first month, he opened the doors of Yahweh''s house and ___ them.", "answer": "repaired"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what stood on the table alongside its vessels in the cleansed temple.', '2 Chronicles 29:18', 'We have cleansed all Yahweh''s house, including the altar of burnt offering with all its vessels, and the table of show bread with all its vessels.', 'WEB', 2,
   '{"type": "recall", "template": "We have cleansed all Yahweh''s house, including the altar of burnt offering with all its vessels, and the table of show ___ with all its vessels.", "answer": "bread"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what Hilkiah told Shaphan he had found in Yahweh''s house.', '2 Chronicles 34:15', 'Hilkiah answered Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' So Hilkiah delivered the book to Shaphan.', 'WEB', 1,
   '{"type": "recall", "template": "Hilkiah answered Shaphan the scribe, ''I have found the book of the ___ in Yahweh''s house.'' So Hilkiah delivered the book to Shaphan.", "answer": "law"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: when in the first month Josiah''s Passover was killed.', '2 Chronicles 35:1', 'Josiah kept a Passover to Yahweh in Jerusalem. They killed the Passover on the fourteenth day of the first month.', 'WEB', 1,
   '{"type": "recall", "template": "Josiah kept a Passover to Yahweh in Jerusalem. They killed the Passover on the fourteenth day of the first ___.", "answer": "month"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what the text says had not been kept like this since the days of Samuel the prophet.', '2 Chronicles 35:18', 'There was no Passover like that kept in Israel from the days of Samuel the prophet, nor did any of the kings of Israel keep such a Passover as Josiah kept.', 'WEB', 3,
   '{"type": "recall", "template": "There was no ___ like that kept in Israel from the days of Samuel the prophet, nor did any of the kings of Israel keep such a Passover as Josiah kept.", "answer": "Passover"}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word: where the escaped survivors were carried after Jerusalem fell.', '2 Chronicles 36:19-20', 'They burned God''s house, broke down the wall of Jerusalem, burned all its palaces with fire, and destroyed all of its valuable vessels. He carried those who had escaped from the sword away to Babylon.', 'WEB', 1,
   '{"type": "recall", "template": "They burned God''s house, broke down the wall of Jerusalem, burned all its palaces with fire, and destroyed all of its valuable vessels. He carried those who had escaped from the sword away to ___.", "answer": "Babylon"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 36:22-23, which foreign king does the text say Yahweh ''stirred up'' to let the exiles return?', '2 Chronicles 36:22-23', 'In the first year of Cyrus king of Persia... Yahweh stirred up the spirit of Cyrus king of Persia, so that he made a proclamation throughout all his kingdom, and put it also in writing.; Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go up.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Cyrus of Persia", "Nebuchadnezzar of Babylon", "Darius of Persia", "Sennacherib of Assyria"], "correct_index": 0}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word closing Cyrus''s decree permitting the exiles to return.', '2 Chronicles 36:23', 'Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go up.''', 'WEB', 2,
   '{"type": "recall", "template": "Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go ___.''", "answer": "up"}', false, 11),
  ((select id from w), 'sequence', 'Put these four scenes of 2 Chronicles in the order they happen in the book.', '2 Chronicles 7:1; 29:3; 35:1; 36:23', 'Now when Solomon had finished praying, fire came down from heaven and consumed the burnt offering and the sacrifices; and Yahweh''s glory filled the house.; In the first year of his reign, in the first month, he opened the doors of Yahweh''s house and repaired them.; Josiah kept a Passover to Yahweh in Jerusalem. They killed the Passover on the fourteenth day of the first month.; Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go up.''', 'WEB', 5,
   '{"type": "sequence", "items": ["Solomon dedicates the temple; fire falls from heaven and the people worship (2 Chronicles 5, 7)", "Hezekiah reopens and cleanses the temple in the first year of his reign (2 Chronicles 29)", "Josiah''s workers rediscover the book of the law, and Josiah keeps a great Passover (2 Chronicles 34-35)", "Babylon burns Jerusalem and the temple, and later Cyrus of Persia decrees that the exiles may return and rebuild (2 Chronicles 36)"], "correct_order": [0, 1, 2, 3]}', true, 12)
;
