-- Gen2Rev challenge ingest: 1 Samuel (World 9) and 2 Samuel (World 10)
-- Generated from docs/content/1-samuel.md and docs/content/2-samuel.md
-- Both books: theological review approved-with-changes/approved, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md, docs/QA_SIGNOFF.md, both dated 2026-08-08)

with w as (select id from public.world where book_slug = '1-samuel')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: whose name was Eli''s instructed response to Samuel about, when Yahweh called him?', '1 Samuel 3:9', 'Therefore Eli said to Samuel, ''Go, lie down. It shall be, if he calls you, that you shall say, Speak, Yahweh; for your servant hears.''', 'WEB', 1,
   '{"type": "recall", "template": "Therefore Eli said to Samuel, ''Go, lie down. It shall be, if he calls you, that you shall say, Speak, ___; for your servant hears.''", "answer": "Yahweh"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to 1 Samuel 8:5, what did the elders of Israel ask Samuel to do?', '1 Samuel 8:5', 'They said to him, ''Behold, you are old, and your sons don''t walk in your ways. Now make us a king to judge us like all the nations.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Make us a king to judge us like all the nations", "Appoint new judges to replace his sons", "Anoint his son as the next judge", "Build a permanent house for the ark"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word from Samuel''s question as he anointed Saul.', '1 Samuel 10:1', 'Then Samuel took the vial of oil and poured it on his head, then kissed him and said, ''Hasn''t Yahweh anointed you to be prince over his inheritance?''', 'WEB', 1,
   '{"type": "recall", "template": "Then Samuel took the vial of oil and poured it on his head, then kissed him and said, ''Hasn''t Yahweh anointed you to be ___ over his inheritance?''", "answer": "prince"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from Samuel''s statement to Saul about obedience.', '1 Samuel 15:22', 'Has Yahweh as great delight in burnt offerings and sacrifices, as in obeying Yahweh''s voice? Behold, to obey is better than sacrifice, and to listen than the fat of rams.', 'WEB', 1,
   '{"type": "recall", "template": "Has Yahweh as great delight in burnt offerings and sacrifices, as in obeying Yahweh''s voice? Behold, to obey is better than ___, and to listen than the fat of rams.", "answer": "sacrifice"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to 1 Samuel 16:7, what does Yahweh say he looks at, in contrast to outward appearance?', '1 Samuel 16:7', 'Don''t look on his face, or on the height of his stature, because I have rejected him; for I don''t see as man sees. For man looks at the outward appearance, but Yahweh looks at the heart.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The heart", "The strength", "The wealth", "The lineage"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what came mightily on David from the day Samuel anointed him?', '1 Samuel 16:13', 'Then Samuel took the horn of oil and anointed him in the middle of his brothers. Then Yahweh''s Spirit came mightily on David from that day forward. So Samuel rose up and went to Ramah.', 'WEB', 2,
   '{"type": "recall", "template": "Then Samuel took the horn of oil and anointed him in the middle of his brothers. Then Yahweh''s ___ came mightily on David from that day forward. So Samuel rose up and went to Ramah.", "answer": "Spirit"}', false, 6),
  ((select id from w), 'multiple_choice', 'According to 1 Samuel 17:49-50, what did David use to defeat Goliath?', '1 Samuel 17:49-50', 'David put his hand in his bag, took a stone and slung it, and struck the Philistine in his forehead. The stone sank into his forehead, and he fell on his face to the earth. So David prevailed over the Philistine with a sling and with a stone, and struck the Philistine and killed him; but there was no sword in David''s hand.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["A sling and a stone", "A sword and a spear", "A bow and arrows", "His bare hands"], "correct_index": 0}', true, 7),
  ((select id from w), 'sequence', 'Put these beats of David''s rise in the order they happen in the text.', '1 Samuel 16:13; 17:49-50; 18:1,3; 24:6', '1 Samuel 16:13; 1 Samuel 17:49-50; 1 Samuel 18:1,3; 1 Samuel 24:6', 'WEB', 3,
   '{"type": "sequence", "items": ["David is anointed by Samuel in the middle of his brothers", "David defeats Goliath with a sling and a stone", "Jonathan makes a covenant with David", "Saul pursues David, but David spares Saul''s life in a cave"], "correct_order": [0, 1, 2, 3]}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word: whose soul was knit with David''s soul, per 1 Samuel 18:1?', '1 Samuel 18:1', 'When he had finished speaking to Saul, the soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul.', 'WEB', 2,
   '{"type": "recall", "template": "When he had finished speaking to Saul, the soul of ___ was knit with the soul of David, and Jonathan loved him as his own soul.", "answer": "Jonathan"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to 1 Samuel 24:17, what did Saul say about David after David spared his life in the cave?', '1 Samuel 24:17', 'He said to David, ''You are more righteous than I; for you have done good to me, whereas I have done evil to you.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["That David was more righteous than he was", "That David should be executed for treason", "That David was unfit to be king", "That David had betrayed him"], "correct_index": 0}', true, 10),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', '1 Samuel 8:5; 15:22; 16:7', 'They said to him, ''Behold, you are old, and your sons don''t walk in your ways. Now make us a king to judge us like all the nations.''; Has Yahweh as great delight in burnt offerings and sacrifices, as in obeying Yahweh''s voice? Behold, to obey is better than sacrifice, and to listen than the fat of rams.; Don''t look on his face, or on the height of his stature, because I have rejected him; for I don''t see as man sees. For man looks at the outward appearance, but Yahweh looks at the heart.', 'WEB', 4,
   '{"type": "sequence", "items": ["“Now make us a king to judge us like all the nations.” — the elders'' request to Samuel (1 Samuel 8:5)", "“To obey is better than sacrifice, and to listen than the fat of rams.” — Samuel to Saul (1 Samuel 15:22)", "“For man looks at the outward appearance, but Yahweh looks at the heart.” — Yahweh to Samuel (1 Samuel 16:7)"], "correct_order": [0, 1, 2]}', false, 11)
;

with w as (select id from public.world where book_slug = '2-samuel')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did the tribes of Israel call David, besides their own bone, when they came to him at Hebron?', '2 Samuel 5:1', 'Then all the tribes of Israel came to David at Hebron and spoke, saying, ''Behold, we are your bone and your flesh.''', 'WEB', 1,
   '{"type": "recall", "template": "Then all the tribes of Israel came to David at Hebron and spoke, saying, ''Behold, we are your bone and your ___.''", "answer": "flesh"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to 2 Samuel 5:4, how old was David when he began to reign, and how long did he reign?', '2 Samuel 5:4', 'David was thirty years old when he began to reign, and he reigned forty years.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Thirty years old; reigned forty years", "Twenty years old; reigned thirty years", "Forty years old; reigned twenty years", "Seventeen years old; reigned forty years"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what was David clothed in as he danced before Yahweh?', '2 Samuel 6:14', 'David danced before Yahweh with all his might; and David was clothed in a linen ephod.', 'WEB', 1,
   '{"type": "recall", "template": "David danced before Yahweh with all his might; and David was clothed in a linen ___.", "answer": "ephod"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what will be established forever, per Yahweh''s promise in 2 Samuel 7:13?', '2 Samuel 7:13', 'He will build a house for my name, and I will establish the throne of his kingdom forever.', 'WEB', 2,
   '{"type": "recall", "template": "He will build a house for my name, and I will establish the throne of his ___ forever.", "answer": "kingdom"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word closing Yahweh''s covenant promise to David.', '2 Samuel 7:16', 'Your house and your kingdom will be made sure forever before you. Your throne will be established forever.', 'WEB', 2,
   '{"type": "recall", "template": "Your house and your kingdom will be made sure forever before you. Your throne will be established ___.", "answer": "forever"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nathan call David, confronting him with the parable''s meaning?', '2 Samuel 12:7', 'Nathan said to David, ''You are the man! This is what Yahweh, the God of Israel, says: I anointed you king over Israel, and I delivered you out of the hand of Saul.''', 'WEB', 3,
   '{"type": "recall", "template": "Nathan said to David, ''You are the ___! This is what Yahweh, the God of Israel, says: I anointed you king over Israel, and I delivered you out of the hand of Saul.''", "answer": "man"}', true, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nathan say Yahweh had put away, after David confessed?', '2 Samuel 12:13', 'David said to Nathan, ''I have sinned against Yahweh.'' Nathan said to David, ''Yahweh also has put away your sin. You will not die.''', 'WEB', 2,
   '{"type": "recall", "template": "David said to Nathan, ''I have sinned against Yahweh.'' Nathan said to David, ''Yahweh also has put away your ___. You will not die.''", "answer": "sin"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to 2 Samuel 12:1, whom did Yahweh send to David?', '2 Samuel 12:1', 'Yahweh sent Nathan to David. He came to him, and said to him, ''There were two men in one city: the one rich, and the other poor.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Nathan", "Gad", "Samuel", "Abiathar"], "correct_index": 0}', false, 8),
  ((select id from w), 'sequence', 'Put these beats of David''s reign in the order they happen in the text.', '2 Samuel 5:1-4; 6:12-15; 7:12-16; 12:1-13; 15:1-18:33', '2 Samuel 5; 2 Samuel 6; 2 Samuel 7; 2 Samuel 12; 2 Samuel 15-18', 'WEB', 3,
   '{"type": "sequence", "items": ["David is anointed king over all Israel at Hebron", "The ark is brought up to Jerusalem with celebration", "Yahweh gives David the covenant promise through Nathan", "Nathan confronts David, and David confesses", "Absalom rebels against his father"], "correct_order": [0, 1, 2, 3, 4]}', true, 9),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the text.', '2 Samuel 5:1; 7:16; 12:7', 'Then all the tribes of Israel came to David at Hebron and spoke, saying, ''Behold, we are your bone and your flesh.''; Your house and your kingdom will be made sure forever before you. Your throne will be established forever.; Nathan said to David, ''You are the man! This is what Yahweh, the God of Israel, says: I anointed you king over Israel, and I delivered you out of the hand of Saul.''', 'WEB', 4,
   '{"type": "sequence", "items": ["“Behold, we are your bone and your flesh.” — the tribes of Israel to David (2 Samuel 5:1)", "“Your throne will be established forever.” — Yahweh''s covenant promise through Nathan (2 Samuel 7:16)", "“You are the man!” — Nathan to David (2 Samuel 12:7)"], "correct_order": [0, 1, 2]}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did David tell his servants Absalom would strike the city with, if they didn''t flee?', '2 Samuel 15:14', 'David said to all his servants who were with him at Jerusalem, ''Arise! Let''s flee, or else none of us will escape from Absalom. Hurry to depart, lest he overtake us quickly and bring down evil on us, and strike the city with the edge of the sword.''', 'WEB', 2,
   '{"type": "recall", "template": "David said to all his servants who were with him at Jerusalem, ''Arise! Let''s flee, or else none of us will escape from Absalom. Hurry to depart, lest he overtake us quickly and bring down evil on us, and strike the city with the edge of the ___.''", "answer": "sword"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what did David cry out as he wept over Absalom''s death?', '2 Samuel 18:33', 'The king was much moved, and went up to the room over the gate and wept. As he went, he said, ''My son Absalom! My son, my son Absalom! I wish I had died instead of you, Absalom, my son, my son!''', 'WEB', 3,
   '{"type": "recall", "template": "The king was much moved, and went up to the room over the gate and wept. As he went, he said, ''My son Absalom! My son, my son Absalom! I wish I had died instead of you, Absalom, my son, my ___!''", "answer": "son"}', true, 12)
;
