-- Gen2Rev challenge ingest: Exodus (World 2) and Leviticus (World 3)
-- Generated from docs/content/exodus.md and docs/content/leviticus.md
-- Both books: theological review approved-with-changes, verbatim QA pass (docs/CONTENT_REVIEW_LOG.md, docs/QA_SIGNOFF.md)

with w as (select id from public.world where book_slug = 'exodus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did God tell Moses to take off at the burning bush?', 'Exodus 3:5', 'He said, ''Don''t come close. Take off your sandals, for the place you are standing on is holy ground.''', 'WEB', 1,
   '{"type": "recall", "template": "He said, ''Don''t come close. Take off your ___, for the place you are standing on is holy ground.''", "answer": "sandals"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing words: God''s self-designation, which Moses is to tell Israel sent him.', 'Exodus 3:14', 'God said to Moses, ''I AM WHO I AM,'' and he said, ''You shall tell the children of Israel this: "I AM has sent me to you."''', 'WEB', 2,
   '{"type": "recall", "template": "God said to Moses, ''I AM WHO I AM,'' and he said, ''You shall tell the children of Israel this: \"___ has sent me to you.\"''", "answer": "I AM"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word from Yahweh''s instruction about the Passover memorial.', 'Exodus 12:14', '''This day shall be a memorial for you. You shall keep it as a feast to Yahweh. You shall keep it as a feast throughout your generations by an ordinance forever.''', 'WEB', 1,
   '{"type": "recall", "template": "''This day shall be a memorial for you. You shall keep it as a ___ to Yahweh. You shall keep it as a feast throughout your generations by an ordinance forever.''", "answer": "feast"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what would the blood be for the Israelites on the night of the tenth plague?', 'Exodus 12:12-13', '''For I will go through the land of Egypt in that night, and will strike all the firstborn in the land of Egypt, both man and animal. I will execute judgments against all the gods of Egypt. I am Yahweh. The blood shall be to you for a token on the houses where you are. When I see the blood, I will pass over you, and no plague will be on you to destroy you when I strike the land of Egypt.''', 'WEB', 2,
   '{"type": "recall", "template": "''For I will go through the land of Egypt in that night, and will strike all the firstborn in the land of Egypt, both man and animal. I will execute judgments against all the gods of Egypt. I am Yahweh. The blood shall be to you for a ___ on the houses where you are. When I see the blood, I will pass over you, and no plague will be on you to destroy you when I strike the land of Egypt.''", "answer": "token"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word describing who was struck throughout Egypt at midnight.', 'Exodus 12:29-30', 'At midnight, Yahweh struck all the firstborn in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.', 'WEB', 3,
   '{"type": "recall", "template": "At midnight, Yahweh struck all the ___ in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.", "answer": "firstborn"}', true, 5),
  ((select id from w), 'multiple_choice', 'According to Exodus 14:21, what did Yahweh use to divide the sea?', 'Exodus 14:21-22', 'Moses stretched out his hand over the sea, and Yahweh caused the sea to go back by a strong east wind all night, and made the sea dry land, and the waters were divided. The children of Israel went into the middle of the sea on the dry ground; and the waters were a wall to them on their right hand and on their left.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["A strong east wind", "Moses'' staff alone", "An earthquake", "A pillar of fire"], "correct_index": 0}', true, 6),
  ((select id from w), 'sequence', 'Put these events of the Red Sea crossing in the order they happen in the text.', 'Exodus 14:21-22; 14:30-31', 'Moses stretched out his hand over the sea, and Yahweh caused the sea to go back by a strong east wind all night, and made the sea dry land, and the waters were divided. The children of Israel went into the middle of the sea on the dry ground; and the waters were a wall to them on their right hand and on their left.; Thus Yahweh saved Israel that day out of the hand of the Egyptians... Israel saw the great work which Yahweh did to the Egyptians, and the people feared Yahweh; and they believed in Yahweh and in his servant Moses.', 'WEB', 3,
   '{"type": "sequence", "items": ["Moses stretches out his hand over the sea", "Yahweh drives the sea back with a strong east wind and the waters are divided", "The children of Israel go into the middle of the sea on dry ground, with the waters a wall on their right and left", "Israel is saved and the people believe in Yahweh and in his servant Moses"], "correct_order": [0, 1, 2, 3]}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what would Israel be to God if they kept the covenant?', 'Exodus 19:5-6', '''Now therefore, if you will indeed obey my voice and keep my covenant, then you shall be my own possession from among all peoples; for all the earth is mine; and you shall be to me a kingdom of priests and a holy nation.''', 'WEB', 2,
   '{"type": "recall", "template": "''Now therefore, if you will indeed obey my voice and keep my covenant, then you shall be my own possession from among all peoples; for all the earth is mine; and you shall be to me a kingdom of priests and a holy ___.''", "answer": "nation"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: the people''s response when Moses relayed Yahweh''s covenant proposal.', 'Exodus 19:8', 'All the people answered together, and said, ''All that Yahweh has spoken we will do.''', 'WEB', 1,
   '{"type": "recall", "template": "All the people answered together, and said, ''All that Yahweh has spoken we will ___.''", "answer": "do"}', false, 9),
  ((select id from w), 'multiple_choice', 'Which of these instructions appears in Exodus 20:12-15?', 'Exodus 20:12-15', '''Honor your father and your mother, that your days may be long in the land which Yahweh your God gives you. You shall not murder. You shall not commit adultery. You shall not steal.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Honor your father and your mother", "Remember the Sabbath day to keep it holy", "You shall not covet your neighbor''s house", "You shall make no idols"], "correct_index": 0}', false, 10),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Exodus 3:14; 19:8; 20:2-3', 'God said to Moses, ''I AM WHO I AM,'' and he said, ''You shall tell the children of Israel this: "I AM has sent me to you."''; All the people answered together, and said, ''All that Yahweh has spoken we will do.''; ''I am Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage. You shall have no other gods before me.''', 'WEB', 4,
   '{"type": "sequence", "items": ["“I AM WHO I AM” — God''s self-revelation to Moses (Exodus 3:14)", "“All that Yahweh has spoken we will do.” — the people''s answer at Sinai (Exodus 19:8)", "“I am Yahweh your God, who brought you out of the land of Egypt... You shall have no other gods before me.” — the opening of the Ten Commandments (Exodus 20:2-3)"], "correct_order": [0, 1, 2]}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what did Moses throw and break when he saw the golden calf?', 'Exodus 32:19-20', 'As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the tablets out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.', 'WEB', 2,
   '{"type": "recall", "template": "As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the ___ out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.", "answer": "tablets"}', true, 12)
;

with w as (select id from public.world where book_slug = 'leviticus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did the burnt offering accomplish for the worshiper, per the text?', 'Leviticus 1:3-4', '''If his offering is a burnt offering from the herd, he shall offer a male without defect. He shall offer it at the door of the Tent of Meeting, that he may be accepted before Yahweh. He shall lay his hand on the head of the burnt offering, and it shall be accepted for him to make atonement for him.''', 'WEB', 1,
   '{"type": "recall", "template": "''If his offering is a burnt offering from the herd, he shall offer a male without defect. He shall offer it at the door of the Tent of Meeting, that he may be accepted before Yahweh. He shall lay his hand on the head of the burnt offering, and it shall be accepted for him to make ___ for him.''", "answer": "atonement"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: by reason of what does the blood make atonement, per Leviticus 17:11?', 'Leviticus 17:11', '''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the life.''', 'WEB', 2,
   '{"type": "recall", "template": "''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the ___.''", "answer": "life"}', true, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh say he would be, before all the people, after the deaths of Nadab and Abihu?', 'Leviticus 10:1-3', 'Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered strange fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, "I will show myself holy to those who come near me, and before all the people I will be glorified."''', 'WEB', 3,
   '{"type": "recall", "template": "Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered strange fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, \"I will show myself holy to those who come near me, and before all the people I will be ___.\"''", "answer": "glorified"}', true, 3),
  ((select id from w), 'sequence', 'Put these passages in the order they appear in the book of Leviticus.', 'Leviticus 1,17; 10; 16; 19; 25', 'Leviticus 1,17; Leviticus 10; Leviticus 16; Leviticus 19; Leviticus 25', 'WEB', 3,
   '{"type": "sequence", "items": ["Instructions for sacrifice and the meaning of blood in atonement", "Nadab and Abihu offer unauthorized fire and die before Yahweh, who says through Moses that he will show himself holy", "The Day of Atonement ritual for the whole people", "The holiness code, including the command to love your neighbor", "The Year of Jubilee, when land returns and debts are released"], "correct_order": [0, 1, 2, 3, 4]}', true, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what was made for the people on the Day of Atonement, per the text?', 'Leviticus 16:29-30', '''It shall be a statute to you forever: in the seventh month, on the tenth day of the month, you shall afflict your souls, and shall do no kind of work, whether native-born or a stranger who lives as a foreigner among you; for on this day shall atonement be made for you, to cleanse you. You shall be clean from all your sins before Yahweh.''', 'WEB', 2,
   '{"type": "recall", "template": "''It shall be a statute to you forever: in the seventh month, on the tenth day of the month, you shall afflict your souls, and shall do no kind of work, whether native-born or a stranger who lives as a foreigner among you; for on this day shall ___ be made for you, to cleanse you. You shall be clean from all your sins before Yahweh.''", "answer": "atonement"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Leviticus 16:29, in which month and on which day was the Day of Atonement observed?', 'Leviticus 16:29', '''It shall be a statute to you forever: in the seventh month, on the tenth day of the month, you shall afflict your souls, and shall do no kind of work, whether native-born or a stranger who lives as a foreigner among you; for on this day shall atonement be made for you, to cleanse you. You shall be clean from all your sins before Yahweh.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["The seventh month, the tenth day", "The first month, the fourteenth day", "The tenth month, the first day", "The seventh month, the first day"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word from the holiness code''s best-known command.', 'Leviticus 19:18', '''You shall not take vengeance, nor bear any grudge against the children of your people; but you shall love your neighbor as yourself. I am Yahweh.''', 'WEB', 1,
   '{"type": "recall", "template": "''You shall not take vengeance, nor bear any grudge against the children of your people; but you shall love your ___ as yourself. I am Yahweh.''", "answer": "neighbor"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Leviticus 19:15, how are Israel''s judges instructed to treat the poor and the powerful in judgment?', 'Leviticus 19:15', '''You shall do no injustice in judgment. You shall not be partial to the poor, nor show favoritism to the great; but you shall judge your neighbor in righteousness.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Show no partiality to either — judge in righteousness", "Always favor the poor", "Always favor the powerful", "Let the elders decide case by case"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what was proclaimed throughout the land in the fiftieth year?', 'Leviticus 25:10', '''You shall make the fiftieth year holy, and proclaim liberty throughout the land to all its inhabitants. It shall be a jubilee to you; and each of you shall return to his own property, and each of you shall return to his family.''', 'WEB', 1,
   '{"type": "recall", "template": "''You shall make the fiftieth year holy, and proclaim ___ throughout the land to all its inhabitants. It shall be a jubilee to you; and each of you shall return to his own property, and each of you shall return to his family.''", "answer": "liberty"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word closing Yahweh''s instruction about how to treat the foreigner living among Israel.', 'Leviticus 19:33-34', '''If a stranger lives as a foreigner with you in your land, you shall not do him wrong... you shall love him as yourself; for you lived as foreigners in the land of Egypt. I am Yahweh your God.''', 'WEB', 2,
   '{"type": "recall", "template": "''If a stranger lives as a foreigner with you in your land, you shall not do him wrong... you shall love him as yourself; for you lived as foreigners in the land of Egypt. I am Yahweh your ___.''", "answer": "God"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: whose God does the text say Yahweh is, closing the Jubilee instructions?', 'Leviticus 25:17', '''You shall not wrong one another, but you shall fear your God; for I am Yahweh your God.''', 'WEB', 1,
   '{"type": "recall", "template": "''You shall not wrong one another, but you shall fear your God; for I am Yahweh your ___.''", "answer": "God"}', false, 11)
;
