-- Gen2Rev challenge ingest: Exodus (World 2) and Leviticus (World 3) -- difficulty tiers (easy/hard)
-- Generated from docs/content/exodus-easy.md, docs/content/exodus-hard.md,
-- docs/content/leviticus-easy.md, docs/content/leviticus-hard.md
-- All four briefs: theological review approved-with-changes, verbatim QA pass
-- (see docs/reviews/*-review.md, docs/qa/*-verbatim-qa.md). Medium-tier rows
-- (difficulty_tier = 'medium') already in the DB are untouched by this file.
-- Schema/syntax template: docs/ingest/exodus-leviticus.sql (original medium ingest).


-- Exodus: easy tier (12 rows: 8 regular + 4 boss)

with w as (select id from public.world where book_slug = 'exodus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'What did God tell Moses to take off at the burning bush?', 'Exodus 3:5', 'He said, ''Don''t come close. Take off your sandals, for the place you are standing on is holy ground.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["his sandals", "his cloak", "his staff", "his ring"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Exodus 3:7-8, what did God say he had come down to do?', 'Exodus 3:7-8', 'Yahweh said, ''I have surely seen the affliction of my people who are in Egypt, and have heard their cry because of their taskmasters, for I know their sorrows. I have come down to deliver them out of the hand of the Egyptians, and to bring them up out of that land to a good and large land, to a land flowing with milk and honey...''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["deliver his people out of the hand of the Egyptians", "punish Moses", "build a temple", "crown a new king"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Exodus 12:13, what would happen when God saw the blood on the houses?', 'Exodus 12:12-13', '''For I will go through the land of Egypt in that night, and will strike all the firstborn in the land of Egypt, both man and animal. I will execute judgments against all the gods of Egypt. I am Yahweh. The blood shall be to you for a token on the houses where you are. When I see the blood, I will pass over you, and no plague will be on you to destroy you when I strike the land of Egypt.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["he would pass over them", "he would send another plague", "he would take the firstborn anyway", "he would ignore the sign"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word describing who was struck throughout Egypt at midnight.', 'Exodus 12:29-30', 'At midnight, Yahweh struck all the firstborn in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.', 'WEB', 1, 'easy', '{"type": "recall", "template": "At midnight, Yahweh struck all the ___ in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.", "answer": "firstborn"}', false, 4),
  ((select id from w), 'multiple_choice', 'How did the Israelites respond after seeing what Yahweh did to the Egyptians?', 'Exodus 14:30-31', 'Thus Yahweh saved Israel that day out of the hand of the Egyptians... Israel saw the great work which Yahweh did to the Egyptians, and the people feared Yahweh; and they believed in Yahweh and in his servant Moses.', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["they believed in Yahweh and in his servant Moses", "they returned to Egypt", "they built an altar to the sea", "they complained to Aaron"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Exodus 19:5-6, what did God say Israel would be to him if they kept the covenant?', 'Exodus 19:5-6', '''Now therefore, if you will indeed obey my voice and keep my covenant, then you shall be my own possession from among all peoples; for all the earth is mine; and you shall be to me a kingdom of priests and a holy nation...''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["his own possession, a kingdom of priests and a holy nation", "a tribe of judges", "a nation of prophets", "nothing different"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'Which of these instructions is given in the verses shown?', 'Exodus 20:12-15', '''Honor your father and your mother, that your days may be long in the land which Yahweh your God gives you. You shall not murder. You shall not commit adultery. You shall not steal.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["Honor your father and your mother", "Remember the Sabbath day", "You shall not covet", "You shall make no idols"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'What did the people ask Aaron to make?', 'Exodus 32:1', '...the people gathered themselves together to Aaron, and said to him, ''Come, make us gods, which shall go before us; for as for this Moses, the man who brought us up out of the land of Egypt, we don''t know what has become of him.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["gods to go before them", "a new law", "a tabernacle", "sandals"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Exodus 14:21, what did Yahweh use to divide the sea?', 'Exodus 14:21-22', 'Moses stretched out his hand over the sea, and Yahweh caused the sea to go back by a strong east wind all night, and made the sea dry land, and the waters were divided. The children of Israel went into the middle of the sea on the dry ground; and the waters were a wall to them on their right hand and on their left.', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["A strong east wind", "Moses'' staff alone", "An earthquake", "A pillar of fire"], "correct_index": 0}', true, 9),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Exodus 3:14; 19:8; 20:2-3', 'God said to Moses, ''I AM WHO I AM,'' and he said, ''You shall tell the children of Israel this: "I AM has sent me to you."''; All the people answered together, and said, ''All that Yahweh has spoken we will do.''; ''I am Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage. You shall have no other gods before me.''', 'WEB', 1, 'easy', '{"type": "sequence", "items": ["“I AM WHO I AM” — God''s self-revelation to Moses (Exodus 3:14)", "“All that Yahweh has spoken we will do.” — the people''s answer at Sinai (Exodus 19:8)", "“I am Yahweh your God, who brought you out of the land of Egypt... You shall have no other gods before me.” — the opening of the Ten Commandments (Exodus 20:2-3)"], "correct_order": [0, 1, 2]}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did Moses throw and break when he saw the golden calf?', 'Exodus 32:19-20', 'As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the tablets out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.', 'WEB', 1, 'easy', '{"type": "recall", "template": "As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the ___ out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.", "answer": "tablets"}', true, 11),
  ((select id from w), 'multiple_choice', 'What did Moses ask God to do if he would not forgive the people''s sin?', 'Exodus 32:31-32', 'Moses returned to Yahweh, and said, ''Oh, this people have sinned a great sin, and have made themselves gods of gold. Yet now, if you will, forgive their sin—and if not, please blot me out of your book which you have written.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["blot me out of your book which you have written", "punish Aaron instead of me", "destroy the calf without me", "give the people up entirely"], "correct_index": 0}', true, 12)
;



-- Exodus: hard tier (12 rows: 8 regular + 4 boss)

with w as (select id from public.world where book_slug = 'exodus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: the bush burned with fire, but what did it not do?', 'Exodus 3:2', 'Yahweh''s angel appeared to him in a flame of fire out of the middle of a bush. He looked, and behold, the bush burned with fire, and the bush was not consumed.', 'WEB', 5, 'hard', '{"type": "recall", "template": "...He looked, and behold, the bush burned with fire, and the bush was not ___.", "answer": "consumed"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: to whom did Moses say God was sending him?', 'Exodus 3:11', 'Moses said to God, ''Who am I, that I should go to Pharaoh, and that I should bring the children of Israel out of Egypt?''', 'WEB', 5, 'hard', '{"type": "recall", "template": "Moses said to God, ''Who am I, that I should go to ___, and that I should bring the children of Israel out of Egypt?''", "answer": "Pharaoh"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what kind of herbs was the Passover meat to be eaten with?', 'Exodus 12:8', 'They shall eat the meat in that night, roasted with fire, with unleavened bread. They shall eat it with bitter herbs.', 'WEB', 5, 'hard', '{"type": "recall", "template": "They shall eat the meat in that night, roasted with fire, with unleavened bread. They shall eat it with bitter ___.", "answer": "herbs"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: how were the Israelites to eat the Passover meal, according to the text?', 'Exodus 12:11', 'This is how you shall eat it: with your belt on your waist, your sandals on your feet, and your staff in your hand; and you shall eat it in haste: it is Yahweh''s Passover.', 'WEB', 5, 'hard', '{"type": "recall", "template": "...and you shall eat it in ___: it is Yahweh''s Passover.", "answer": "haste"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: where did the pillar of cloud move to, relative to the Israelites?', 'Exodus 14:19', '...and the pillar of cloud moved from before them, and stood behind them.', 'WEB', 5, 'hard', '{"type": "recall", "template": "...and the pillar of cloud moved from before them, and stood ___ them.", "answer": "behind"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does this commandment say to do with the Sabbath day?', 'Exodus 20:8', 'Remember the Sabbath day, to keep it holy.', 'WEB', 5, 'hard', '{"type": "recall", "template": "Remember the Sabbath day, to keep it ___.", "answer": "holy"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: how did the people in the camp react to the thunder, lightning, and trumpet?', 'Exodus 19:16', 'On the third day, when it was morning, there were thunders and lightnings, and a thick cloud on the mountain, and the sound of an exceedingly loud trumpet; and all the people who were in the camp trembled.', 'WEB', 5, 'hard', '{"type": "recall", "template": "...and the sound of an exceedingly loud trumpet; and all the people who were in the camp ___.", "answer": "trembled"}', false, 7),
  ((select id from w), 'recall', 'Complete Aaron''s explanation to Moses:', 'Exodus 32:24', '...So they gave it to me; and I threw it into the fire, and out came this calf.', 'WEB', 5, 'hard', '{"type": "recall", "template": "''So they gave it to me; and I threw it into the fire, and out came this ___.''", "answer": "calf"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word describing who was struck throughout Egypt at midnight.', 'Exodus 12:29-30', 'At midnight, Yahweh struck all the firstborn in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.', 'WEB', 5, 'hard', '{"type": "recall", "template": "At midnight, Yahweh struck all the ___ in the land of Egypt, from the firstborn of Pharaoh who sat on his throne to the firstborn of the captive who was in the dungeon, and all the firstborn of livestock. Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt, for there was not a house where there was not one dead.", "answer": "firstborn"}', true, 9),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Exodus 3:14; 19:8; 20:2-3', 'God said to Moses, ''I AM WHO I AM,'' and he said, ''You shall tell the children of Israel this: "I AM has sent me to you."''; All the people answered together, and said, ''All that Yahweh has spoken we will do.''; ''I am Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage. You shall have no other gods before me.''', 'WEB', 5, 'hard', '{"type": "sequence", "items": ["“I AM WHO I AM” — God''s self-revelation to Moses (Exodus 3:14)", "“All that Yahweh has spoken we will do.” — the people''s answer at Sinai (Exodus 19:8)", "“I am Yahweh your God, who brought you out of the land of Egypt... You shall have no other gods before me.” — the opening of the Ten Commandments (Exodus 20:2-3)"], "correct_order": [0, 1, 2]}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did Moses throw and break when he saw the golden calf?', 'Exodus 32:19-20', 'As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the tablets out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.', 'WEB', 5, 'hard', '{"type": "recall", "template": "As soon as he came near to the camp, he saw the calf and the dancing. Then Moses'' anger grew hot, and he threw the ___ out of his hands, and broke them beneath the mountain. He took the calf which they had made, and burned it with fire, ground it to powder, and scattered it on the water, and made the children of Israel drink it.", "answer": "tablets"}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what were the people afraid would happen if God spoke with them directly?', 'Exodus 20:18-19', 'All the people perceived the thunderings, the lightnings, the sound of the trumpet, and the mountain smoking. When the people saw it, they trembled, and stayed at a distance. They said to Moses, ''Speak with us yourself, and we will listen; but don''t let God speak with us, lest we die.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "...but don''t let God speak with us, lest we ___.", "answer": "die"}', true, 12)
;



-- Leviticus: easy tier (11 rows: 8 regular + 3 boss)

with w as (select id from public.world where book_slug = 'leviticus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'According to Leviticus 1:3-4, what did the worshiper do to the burnt offering before it was accepted?', 'Leviticus 1:3-4', '''If his offering is a burnt offering from the herd, he shall offer a male without defect. He shall offer it at the door of the Tent of Meeting, that he may be accepted before Yahweh. He shall lay his hand on the head of the burnt offering, and it shall be accepted for him to make atonement for him.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["lay his hand on its head", "pour oil on it", "cut off its horns", "carry it around the altar seven times"], "correct_index": 0}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what kind of fire did Nadab and Abihu offer before Yahweh?', 'Leviticus 10:1-3', 'Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered strange fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, "I will show myself holy to those who come near me, and before all the people I will be glorified."''', 'WEB', 1, 'easy', '{"type": "recall", "template": "Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered ___ fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, \"I will show myself holy to those who come near me, and before all the people I will be glorified.\"''", "answer": "strange"}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Leviticus 16:34, how often was this atonement to be made for the people?', 'Leviticus 16:34', '''This shall be an everlasting statute for you, to make atonement for the children of Israel once in the year because of all their sins.'' It was done as Yahweh commanded Moses.', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["once in the year", "once a month", "every day", "once in a lifetime"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Leviticus 16:29-30, what does the text say is to happen on the Day of Atonement?', 'Leviticus 16:29-30', '''It shall be a statute to you forever: in the seventh month, on the tenth day of the month, you shall afflict your souls, and shall do no kind of work, whether native-born or a stranger who lives as a foreigner among you; for on this day shall atonement be made for you, to cleanse you. You shall be clean from all your sins before Yahweh.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["atonement is to be made and the people are to be cleansed from their sins", "a new law is to be given", "a king is to be crowned", "the tabernacle is to be rebuilt"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Leviticus 19:2, what reason does the text give for the command to be holy?', 'Leviticus 19:2', '''Speak to all the congregation of the children of Israel, and tell them, "You shall be holy; for I, Yahweh your God, am holy."''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["for I, Yahweh your God, am holy", "because the priests required it", "to prepare for battle", "to inherit the land"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Leviticus 19:18, what does God tell the people to do instead of taking vengeance or bearing a grudge?', 'Leviticus 19:18', '''You shall not take vengeance, nor bear any grudge against the children of your people; but you shall love your neighbor as yourself. I am Yahweh.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["love your neighbor as yourself", "seek justice from the judges", "bring your case before the priest", "bring an offering"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: how were Israel''s judges to judge their neighbor?', 'Leviticus 19:15', '''You shall do no injustice in judgment. You shall not be partial to the poor, nor show favoritism to the great; but you shall judge your neighbor in righteousness.''', 'WEB', 1, 'easy', '{"type": "recall", "template": "''You shall do no injustice in judgment. You shall not be partial to the poor, nor show favoritism to the great; but you shall judge your neighbor in ___.''", "answer": "righteousness"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Leviticus 25:10, what was to happen in the fiftieth year?', 'Leviticus 25:10', '''You shall make the fiftieth year holy, and proclaim liberty throughout the land to all its inhabitants. It shall be a jubilee to you; and each of you shall return to his own property, and each of you shall return to his family.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["liberty was to be proclaimed throughout the land, and each person was to return to his own property and family", "a new king was to be crowned", "all debts were to double", "the tabernacle was to be moved"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: by reason of what does the blood make atonement, per Leviticus 17:11?', 'Leviticus 17:11', '''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the life.''', 'WEB', 1, 'easy', '{"type": "recall", "template": "''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the ___.''", "answer": "life"}', true, 9),
  ((select id from w), 'sequence', 'Put these passages in the order they appear in the book of Leviticus.', 'Leviticus 1,17; 10; 16; 19; 25', 'Leviticus 1,17; Leviticus 10; Leviticus 16; Leviticus 19; Leviticus 25', 'WEB', 1, 'easy', '{"type": "sequence", "items": ["Instructions for sacrifice and the meaning of blood in atonement", "Nadab and Abihu offer strange fire and die before Yahweh, who says through Moses that he will show himself holy", "The Day of Atonement ritual for the whole people", "The holiness code, including the command to love your neighbor", "The Year of Jubilee, when land returns and debts are released"], "correct_order": [0, 1, 2, 3, 4]}', true, 10),
  ((select id from w), 'multiple_choice', 'According to Leviticus 25:17, what does God tell the people to do instead of wronging one another?', 'Leviticus 25:17', '''You shall not wrong one another, but you shall fear your God; for I am Yahweh your God.''', 'WEB', 1, 'easy', '{"type": "multiple_choice", "options": ["fear your God", "build an altar", "go to war", "offer a sacrifice"], "correct_index": 0}', true, 11)
;



-- Leviticus: hard tier (11 rows: 8 regular + 3 boss)

with w as (select id from public.world where book_slug = 'leviticus')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what two kinds of livestock could the offering come from?', 'Leviticus 1:2', '"Speak to the children of Israel, and tell them, ''When anyone of you offers an offering to Yahweh, you shall offer your offering of the livestock, from the herd and from the flock.', 'WEB', 5, 'hard', '{"type": "recall", "template": "\"Speak to the children of Israel, and tell them, ''When anyone of you offers an offering to Yahweh, you shall offer your offering of the livestock, from the herd and from the ___.", "answer": "flock"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from the statute about the Day of Atonement.', 'Leviticus 16:34', '''This shall be an everlasting statute for you, to make atonement for the children of Israel once in the year because of all their sins.'' It was done as Yahweh commanded Moses.', 'WEB', 5, 'hard', '{"type": "recall", "template": "''This shall be an ___ statute for you, to make atonement for the children of Israel once in the year because of all their sins.'' It was done as Yahweh commanded Moses.", "answer": "everlasting"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: for whom did the high priest make atonement, besides himself and his household?', 'Leviticus 16:17', 'No one shall be in the Tent of Meeting when he enters to make atonement in the Holy Place, until he comes out, and has made atonement for himself and for his household, and for all the assembly of Israel.', 'WEB', 5, 'hard', '{"type": "recall", "template": "...and has made atonement for himself and for his household, and for all the ___ of Israel.", "answer": "assembly"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word completing the third instruction.', 'Leviticus 19:11', '"You shall not steal. "You shall not lie. "You shall not deceive one another."', 'WEB', 5, 'hard', '{"type": "recall", "template": "\"You shall not steal. \"You shall not lie. \"You shall not deceive one ___.\"", "answer": "another"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: before whom were the people not to put a stumbling block?', 'Leviticus 19:14', '''You shall not curse the deaf, nor put a stumbling block before the blind; but you shall fear your God. I am Yahweh.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "''You shall not curse the deaf, nor put a stumbling block before the ___; but you shall fear your God. I am Yahweh.''", "answer": "blind"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: who were the people to honor by rising up before the gray head?', 'Leviticus 19:32 (WEB)', '''You shall rise up before the gray head and honor the face of the elderly; and you shall fear your God. I am Yahweh.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "''You shall rise up before the gray head and honor the face of the ___; and you shall fear your God. I am Yahweh.''", "answer": "elderly"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word describing the trumpet sounded on the Day of Atonement.', 'Leviticus 25:9', 'Then you shall sound the loud trumpet on the tenth day of the seventh month. On the Day of Atonement you shall sound the trumpet throughout all your land.', 'WEB', 5, 'hard', '{"type": "recall", "template": "Then you shall sound the ___ trumpet on the tenth day of the seventh month. On the Day of Atonement you shall sound the trumpet throughout all your land.", "answer": "loud"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: whose is the land, per Leviticus 25:23?', 'Leviticus 25:23', '''The land shall not be sold in perpetuity, for the land is mine; for you are strangers and live as foreigners with me.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "''The land shall not be sold in perpetuity, for the land is ___; for you are strangers and live as foreigners with me.''", "answer": "mine"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: by reason of what does the blood make atonement, per Leviticus 17:11?', 'Leviticus 17:11', '''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the life.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "''For the life of the flesh is in the blood. I have given it to you on the altar to make atonement for your souls; for it is the blood that makes atonement by reason of the ___.''", "answer": "life"}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh say he would be, before all the people, after the deaths of Nadab and Abihu?', 'Leviticus 10:1-3', 'Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered strange fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, "I will show myself holy to those who come near me, and before all the people I will be glorified."''', 'WEB', 5, 'hard', '{"type": "recall", "template": "Nadab and Abihu, the sons of Aaron, each took his censer, and put fire in it, and laid incense on it, and offered strange fire before Yahweh, which he had not commanded them. Fire came out from before Yahweh, and devoured them, and they died before Yahweh. Then Moses said to Aaron, ''This is what Yahweh spoke of, saying, \"I will show myself holy to those who come near me, and before all the people I will be ___.\"''", "answer": "glorified"}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what would happen to Aaron if he entered the Most Holy Place at just any time?', 'Leviticus 16:2', 'Yahweh said to Moses, ''Tell Aaron your brother not to come at just any time into the Most Holy Place within the veil, before the mercy seat which is on the ark; lest he die; for I will appear in the cloud on the mercy seat.''', 'WEB', 5, 'hard', '{"type": "recall", "template": "Yahweh said to Moses, ''Tell Aaron your brother not to come at just any time into the Most Holy Place within the veil, before the mercy seat which is on the ark; lest he ___; for I will appear in the cloud on the mercy seat.''", "answer": "die"}', true, 11)
;

