-- Gen2Rev challenge ingest: Ezekiel (World 26) and Daniel (World 27)
-- Generated from docs/content/ezekiel.md and docs/content/daniel.md
-- Both books: theological review approved-with-changes, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md rows 26-27, docs/QA_SIGNOFF.md)
-- Ezekiel 16, 23, 38, 39 and Daniel 7-12 are permanently excluded per each book's brief;
-- see docs/content/ezekiel.md and docs/content/daniel.md "Contested Territory" sections.

with w as (select id from public.world where book_slug = 'ezekiel')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Ezekiel see, by the river Chebar, when the heavens were opened?', 'Ezekiel 1:1-3', 'Now in the thirtieth year, in the fourth month, in the fifth day of the month, as I was among the captives by the river Chebar, the heavens were opened, and I saw visions of God.', 'WEB', 1,
   '{"type": "recall", "template": "Now in the thirtieth year, in the fourth month, in the fifth day of the month, as I was among the captives by the river Chebar, the heavens were opened, and I saw ___ of God.", "answer": "visions"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what was written on the scroll shown to Ezekiel?', 'Ezekiel 2:9-10', 'When I looked, behold, a hand was stretched out to me; and behold, a scroll of a book was in it. He spread it before me. It was written within and without; and lamentations, mourning, and woe were written in it.', 'WEB', 2,
   '{"type": "recall", "template": "When I looked, behold, a hand was stretched out to me; and behold, a scroll of a book was in it. He spread it before me. It was written within and without; and lamentations, mourning, and ___ were written in it.", "answer": "woe"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: how did the scroll taste in Ezekiel''s mouth?', 'Ezekiel 3:1-3', 'He said to me, ''Son of man, eat what you find. Eat this scroll, and go, speak to the house of Israel.'' So I opened my mouth, and he caused me to eat the scroll. He said to me, ''Son of man, eat this scroll that I give you and fill your belly and your bowels with it.'' Then I ate it. It was as sweet as honey in my mouth.', 'WEB', 1,
   '{"type": "recall", "template": "He said to me, ''Son of man, eat what you find. Eat this scroll, and go, speak to the house of Israel.'' So I opened my mouth, and he caused me to eat the scroll. Then I ate it. It was as sweet as ___ in my mouth.", "answer": "honey"}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Ezekiel 4:4-5, what did Ezekiel lie on his left side to represent?', 'Ezekiel 4:4-5', 'Moreover lie on your left side, and lay the iniquity of the house of Israel on it. According to the number of the days that you shall lie on it, you shall bear their iniquity. For I have appointed the years of their iniquity to be to you a number of days, even three hundred ninety days. So you shall bear the iniquity of the house of Israel.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The iniquity of the house of Israel", "The iniquity of the house of Judah", "The years of the exile in Babylon", "The days of the siege of Jerusalem"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Ezekiel 4:5-6, how many days did Ezekiel lie on his left side, and how many on his right?', 'Ezekiel 4:5-6', 'For I have appointed the years of their iniquity to be to you a number of days, even three hundred ninety days. So you shall bear the iniquity of the house of Israel. Again, when you have accomplished these, you shall lie on your right side, and shall bear the iniquity of the house of Judah. I have appointed forty days, each day for a year, to you.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["390 days, then 40 days", "40 days, then 390 days", "70 days, then 40 days", "390 days, then 70 days"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh make Ezekiel to the house of Israel?', 'Ezekiel 3:17-19', '''Son of man, I have made you a watchman to the house of Israel. Therefore hear the word from my mouth, and warn them from me. When I tell the wicked, "You will surely die," and you give him no warning, nor speak to warn the wicked from his wicked way, to save his life, that wicked man will die in his iniquity; but I will require his blood at your hand.''', 'WEB', 1,
   '{"type": "recall", "template": "''Son of man, I have made you a ___ to the house of Israel. Therefore hear the word from my mouth, and warn them from me.''", "answer": "watchman"}', true, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say he has no pleasure in?', 'Ezekiel 33:11', '''"As I live," says the Lord Yahweh, "I have no pleasure in the death of the wicked, but that the wicked turn from his way and live. Turn, turn from your evil ways! For why will you die, house of Israel?"''', 'WEB', 1,
   '{"type": "recall", "template": "''\"As I live,\" says the Lord Yahweh, \"I have no pleasure in the ___ of the wicked, but that the wicked turn from his way and live. Turn, turn from your evil ways! For why will you die, house of Israel?\"''", "answer": "death"}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: who does Ezekiel 18:20 say shall die?', 'Ezekiel 18:20', 'The soul who sins, he shall die. The son shall not bear the iniquity of the father, neither shall the father bear the iniquity of the son.', 'WEB', 1,
   '{"type": "recall", "template": "The soul who ___, he shall die. The son shall not bear the iniquity of the father, neither shall the father bear the iniquity of the son.", "answer": "sins"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: who does Yahweh say will search for his sheep himself?', 'Ezekiel 34:11-12', '''For the Lord Yahweh says: "Behold, I myself, even I, will search for my sheep, and will seek them out. As a shepherd seeks out his flock in the day that he is among his sheep that are scattered abroad, so I will seek out my sheep."''', 'WEB', 2,
   '{"type": "recall", "template": "''For the Lord Yahweh says: \"Behold, I myself, even I, will search for my ___, and will seek them out. As a shepherd seeks out his flock in the day that he is among his sheep that are scattered abroad, so I will seek out my sheep.\"''", "answer": "sheep"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: who will Yahweh set up as one shepherd over his people?', 'Ezekiel 34:23-24', '''I will set up one shepherd over them, and he will feed them, even my servant David. He will feed them, and he will be their shepherd. I, Yahweh, will be their God, and my servant David prince among them. I, Yahweh, have spoken it.''', 'WEB', 2,
   '{"type": "recall", "template": "''I will set up one shepherd over them, and he will feed them, even my servant ___. He will feed them, and he will be their shepherd. I, Yahweh, will be their God, and my servant David prince among them. I, Yahweh, have spoken it.''", "answer": "David"}', false, 10),
  ((select id from w), 'multiple_choice', 'According to Ezekiel 37:1-3, what did Ezekiel see filling the valley Yahweh set him down in?', 'Ezekiel 37:1-3', 'Yahweh''s hand was on me, and he brought me out in Yahweh''s Spirit, and set me down in the middle of the valley; and it was full of bones. He caused me to pass by them all around; and behold, there were very many in the open valley, and behold, they were very dry. He said to me, ''Son of man, can these bones live?'' I answered, ''Lord Yahweh, you know.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Very many bones, very dry", "Ashes and rubble", "Broken pottery", "Dead trees"], "correct_index": 0}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh say he would cause to enter the dry bones?', 'Ezekiel 37:4-6', '''Prophesy over these bones, and tell them, "You dry bones, hear Yahweh''s word. The Lord Yahweh says to these bones: Behold, I will cause breath to enter into you, and you will live. I will lay sinews on you, and will bring up flesh on you, and cover you with skin, and put breath in you, and you will live."''', 'WEB', 1,
   '{"type": "recall", "template": "''Prophesy over these bones, and tell them, \"You dry bones, hear Yahweh''s word. The Lord Yahweh says to these bones: Behold, I will cause ___ to enter into you, and you will live.\"''", "answer": "breath"}', true, 12),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its setting.', 'Ezekiel 3:17-19; 18:20; 37:4-6', 'The watchman appointment; individual responsibility; the dry bones prophecy', 'WEB', 4,
   '{"type": "sequence", "items": ["\"I have made you a watchman to the house of Israel... warn them from me.\" — Ezekiel appointed watchman (3:17-19)", "\"The soul who sins, he shall die. The son shall not bear the iniquity of the father...\" — individual responsibility (18:20)", "\"Behold, I will cause breath to enter into you, and you will live.\" — the dry bones prophecy (37:4-6)"], "correct_order": [0, 1, 2]}', true, 13),
  ((select id from w), 'sequence', 'Put these pivotal passages in the order they appear in the book of Ezekiel.', 'Ezekiel 1-3; 4; 3:16-21; 18; 34; 37', 'The call vision and commissioning; the sign-act; the watchman; individual responsibility; the shepherd of Israel; the valley of dry bones', 'WEB', 3,
   '{"type": "sequence", "items": ["The call vision and commissioning by the river Chebar", "The sign-act of lying on his side to bear Israel and Judah''s iniquity", "The watchman appointed to warn the house of Israel", "\"The soul who sins, he shall die\" — individual responsibility", "The shepherd of Israel who will search for and gather his sheep", "The valley of dry bones brought to life"], "correct_order": [0, 1, 2, 3, 4, 5]}', true, 14)
;

with w as (select id from public.world where book_slug = 'daniel')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Daniel purpose in his heart not to do?', 'Daniel 1:8', 'But Daniel purposed in his heart that he would not defile himself with the king''s delicacies, nor with the wine which he drank. Therefore he requested of the prince of the eunuchs that he might not defile himself.', 'WEB', 1,
   '{"type": "recall", "template": "But Daniel purposed in his ___ that he would not defile himself with the king''s delicacies, nor with the wine which he drank. Therefore he requested of the prince of the eunuchs that he might not defile himself.", "answer": "heart"}', false, 1),
  ((select id from w), 'multiple_choice', 'What did Daniel and his friends ask to eat instead of the king''s food?', 'Daniel 1:12', '''Test your servants, I beg you, ten days; and let them give us vegetables to eat and water to drink.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Vegetables and water", "Bread and wine", "Fruit and milk", "Meat and water"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: how did Daniel and his friends appear at the end of the ten-day test?', 'Daniel 1:15', 'At the end of ten days, their faces appeared fairer and they were fatter in flesh than all the youths who ate of the king''s delicacies.', 'WEB', 1,
   '{"type": "recall", "template": "At the end of ten days, their faces appeared fairer and they were fatter in flesh than all the youths who ate of the king''s ___.", "answer": "delicacies"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: to whom did Daniel give thanks when the secret of the king''s dream was revealed to him?', 'Daniel 2:19', 'Then the secret was revealed to Daniel in a vision of the night. Then Daniel blessed the God of heaven.', 'WEB', 1,
   '{"type": "recall", "template": "Then the secret was revealed to Daniel in a vision of the night. Then Daniel blessed the God of ___.", "answer": "heaven"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Daniel 2:27-28, who did Daniel say could reveal the king''s secret when none of the wise men could?', 'Daniel 2:27-28', 'The secret which the king has demanded can''t be shown to the king by wise men, enchanters, magicians, or soothsayers; but there is a God in heaven who reveals secrets.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A God in heaven who reveals secrets", "The oldest of the king''s magicians", "No one — the secret was never revealed", "An angel who appeared to the king himself"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Shadrach, Meshach, and Abednego say their God was able to do?', 'Daniel 3:16-18', 'Shadrach, Meshach, and Abednego answered the king, ''Nebuchadnezzar, we have no need to answer you in this matter. If it happens, our God whom we serve is able to deliver us from the burning fiery furnace... But if not, let it be known to you, O king, that we will not serve your gods or worship the golden image which you have set up.''', 'WEB', 1,
   '{"type": "recall", "template": "Shadrach, Meshach, and Abednego answered the king, ''Nebuchadnezzar, we have no need to answer you in this matter. If it happens, our God whom we serve is able to ___ us from the burning fiery furnace... But if not, let it be known to you, O king, that we will not serve your gods or worship the golden image which you have set up.''", "answer": "deliver"}', true, 6),
  ((select id from w), 'multiple_choice', 'According to Daniel 3:25, how many men did the king see walking unharmed in the fire?', 'Daniel 3:25', '''Look, I see four men loose, walking in the middle of the fire, and they are unharmed. The appearance of the fourth is like a son of the gods.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Four", "Three", "Two", "One"], "correct_index": 0}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: whose God did the king bless for sending an angel to deliver Shadrach, Meshach, and Abednego?', 'Daniel 3:28', '''Blessed be the God of Shadrach, Meshach, and Abednego, who has sent his angel and delivered his servants who trusted in him... that they might not serve nor worship any god except their own God.''', 'WEB', 1,
   '{"type": "recall", "template": "''Blessed be the ___ of Shadrach, Meshach, and Abednego, who has sent his angel and delivered his servants who trusted in him... that they might not serve nor worship any god except their own God.''", "answer": "God"}', true, 8),
  ((select id from w), 'sequence', 'Put these beats of the fiery furnace scene in the order they happen in the text.', 'Daniel 3:16-18; 3:19-23; 3:25; 3:26-28', 'Refusal to worship; thrown into the furnace; found unharmed with a fourth figure; called out and God praised by the king', 'WEB', 3,
   '{"type": "sequence", "items": ["Shadrach, Meshach, and Abednego refuse to worship the golden image", "They are thrown into the burning fiery furnace", "The king sees four men walking unharmed in the fire, the fourth like a son of the gods", "The king calls them out and blesses the God who delivered them"], "correct_order": [0, 1, 2, 3]}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nebuchadnezzar claim he had built Babylon by?', 'Daniel 4:30', 'The king spoke and said, ''Is not this great Babylon, which I have built for the royal dwelling place by the might of my power and for the glory of my majesty?''', 'WEB', 1,
   '{"type": "recall", "template": "The king spoke and said, ''Is not this great Babylon, which I have built for the royal dwelling place by the might of my power and for the glory of my ___?''", "answer": "majesty"}', false, 10),
  ((select id from w), 'multiple_choice', 'According to Daniel 4:31, what did the voice from the sky declare about Nebuchadnezzar''s kingdom?', 'Daniel 4:31', 'While the word was in the king''s mouth, a voice came from the sky, saying, ''O King Nebuchadnezzar, to you it is spoken: The kingdom has departed from you.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The kingdom has departed from you", "The kingdom will be doubled", "The kingdom will pass to your son", "The kingdom will never end"], "correct_index": 0}', false, 11),
  ((select id from w), 'multiple_choice', 'According to Daniel 5:30, what happened to Belshazzar that same night?', 'Daniel 5:30', 'In that night Belshazzar the Chaldean King was slain.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["He was slain", "He fled the city", "He repented and was spared", "He abdicated the throne"], "correct_index": 0}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Daniel 6:10, how many times a day did Daniel pray, even after the decree was signed?', 'Daniel 6:10', 'When Daniel knew that the writing was signed, he went into his house...and he kneeled on his knees three times a day, and prayed, and gave thanks before his God, as he did before.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Three times", "Once", "Five times", "Seven times"], "correct_index": 0}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what did Daniel say God had shut, so the lions did not hurt him?', 'Daniel 6:21-22', '''O king, live forever! My God has sent his angel, and has shut the lions'' mouths, and they have not hurt me, because innocence was found in me before him; and also before you, O king, I have done no harm.''', 'WEB', 1,
   '{"type": "recall", "template": "''O king, live forever! My God has sent his angel, and has shut the lions'' ___, and they have not hurt me, because innocence was found in me before him; and also before you, O king, I have done no harm.''", "answer": "mouths"}', true, 14),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its scene.', 'Daniel 3:16-18; 5:25-28; 6:21-22', 'The fiery furnace defiance; the writing on the wall interpretation; the lions'' den deliverance', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Our God whom we serve is able to deliver us from the burning fiery furnace...\" — Shadrach, Meshach, and Abednego before the furnace (3:16-18)", "\"MENE, MENE, TEKEL, UPHARSIN... your kingdom is divided, and given to the Medes and Persians.\" — Daniel interprets the writing on the wall (5:25-28)", "\"My God has sent his angel, and has shut the lions'' mouths...\" — Daniel after a night in the lions'' den (6:21-22)"], "correct_order": [0, 1, 2]}', true, 15),
  ((select id from w), 'sequence', 'Put these six pivotal scenes in the order they appear in the book of Daniel.', 'Daniel 1; 2; 3; 4; 5; 6', 'The king''s food refused; the dream and interpretation; the fiery furnace; Nebuchadnezzar''s pride and restoration; the writing on the wall; the lions'' den', 'WEB', 3,
   '{"type": "sequence", "items": ["Daniel and his friends refuse the king''s food", "Nebuchadnezzar''s dream and Daniel''s interpretation", "The fiery furnace", "Nebuchadnezzar''s pride and restoration", "Belshazzar''s feast and the writing on the wall", "Daniel in the lions'' den"], "correct_order": [0, 1, 2, 3, 4, 5]}', true, 16)
;
