-- Gen2Rev challenge ingest: Ezra (World 15), Nehemiah (World 16), Esther (World 17)
-- Generated from docs/content/ezra.md, docs/content/nehemiah.md, docs/content/esther.md
-- All three books: theological review approved-with-changes, verbatim QA pass-with-corrections
-- (docs/CONTENT_REVIEW_LOG.md rows 15-17, docs/QA_SIGNOFF.md). World rows already live for
-- book_slug 'ezra' / 'nehemiah' / 'esther'.
--
-- Ezra note: per the brief's status header, Kachi's resolution of the Scene 5 escalation permanently
-- excludes only Ezra 9:1-2, 10:3, 10:10-12, and 10:44 from challenge-ready content -- the scene's own
-- listed challenge-ready verses (9:3, 9:6, 10:1) are used below as regular (non-boss) items. The boss
-- battle itself is drawn only from Scenes 1-4, per the brief's Difficulty Ladder note.

with w as (select id from public.world where book_slug = 'ezra')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Cyrus''s proclamation authorize the exiles to do with Yahweh''s house?', 'Ezra 1:3', 'Whoever there is among you of all his people, may his God be with him, and let him go up to Jerusalem, which is in Judah, and build the house of Yahweh, the God of Israel (he is God), which is in Jerusalem.', 'WEB', 1,
   '{"type": "recall", "template": "Whoever there is among you of all his people, may his God be with him, and let him go up to Jerusalem, which is in Judah, and ___ the house of Yahweh, the God of Israel (he is God), which is in Jerusalem.", "answer": "build"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Ezra 1:3, what did Cyrus''s decree authorize the exiles to do?', 'Ezra 1:3', 'Whoever there is among you of all his people, may his God be with him, and let him go up to Jerusalem, which is in Judah, and build the house of Yahweh, the God of Israel (he is God), which is in Jerusalem.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Return to Jerusalem and build the house of Yahweh", "Rebuild the walls of Babylon", "Serve as officials in the Persian court", "Return the temple vessels only"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word describing the exiles'' feeling as they rebuilt the altar, per Ezra 3:3.', 'Ezra 3:3', 'In spite of their fear because of the peoples of the surrounding lands, they set the altar on its base; and they offered burnt offerings on it to Yahweh, even burnt offerings morning and evening.', 'WEB', 1,
   '{"type": "recall", "template": "In spite of their ___ because of the peoples of the surrounding lands, they set the altar on its base; and they offered burnt offerings on it to Yahweh, even burnt offerings morning and evening.", "answer": "fear"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from the song sung when the temple''s foundation was laid, per Ezra 3:11.', 'Ezra 3:11', 'They sang to one another in praising and giving thanks to Yahweh, ''For he is good, for his loving kindness endures forever toward Israel.'' All the people shouted with a great shout, when they praised Yahweh, because the foundation of Yahweh''s house had been laid.', 'WEB', 2,
   '{"type": "recall", "template": "They sang to one another in praising and giving thanks to Yahweh, ''For he is ___, for his loving kindness endures forever toward Israel.'' All the people shouted with a great shout, when they praised Yahweh, because the foundation of Yahweh''s house had been laid.", "answer": "good"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: how did the returned exiles keep the dedication of the finished temple, per Ezra 6:16?', 'Ezra 6:16', 'The children of Israel, the priests, the Levites, and the rest of the children of the captivity, kept the dedication of this house of God with joy.', 'WEB', 2,
   '{"type": "recall", "template": "The children of Israel, the priests, the Levites, and the rest of the children of the captivity, kept the dedication of this house of God with ___.", "answer": "joy"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing name: which prophet, alongside Zechariah, spurred the elders of the Jews to finish the temple, per Ezra 6:14?', 'Ezra 6:14', 'The elders of the Jews built and prospered, through the prophesying of Haggai the prophet and Zechariah the son of Iddo. They built and finished it, according to the commandment of the God of Israel, and according to the decree of Cyrus, Darius, and Artaxerxes king of Persia.', 'WEB', 3,
   '{"type": "recall", "template": "The elders of the Jews built and prospered, through the prophesying of ___ the prophet and Zechariah the son of Iddo. They built and finished it, according to the commandment of the God of Israel, and according to the decree of Cyrus, Darius, and Artaxerxes king of Persia.", "answer": "Haggai"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what had Ezra set his heart to seek, according to Ezra 7:10?', 'Ezra 7:10', 'For Ezra had set his heart to seek Yahweh''s law, and to do it, and to teach statutes and ordinances in Israel.', 'WEB', 1,
   '{"type": "recall", "template": "For Ezra had set his heart to seek Yahweh''s ___, and to do it, and to teach statutes and ordinances in Israel.", "answer": "law"}', false, 7),
  ((select id from w), 'multiple_choice', 'What was Ezra''s defining characteristic, according to Ezra 7:6?', 'Ezra 7:6', '...this Ezra went up from Babylon. He was a skilled scribe in the law of Moses, which Yahweh, the God of Israel, had given; and the king granted him all his request, according to Yahweh his God''s hand on him.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["He was a skilled scribe in the law of Moses", "He was a military commander", "He was the king''s cupbearer", "He was a builder of walls"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: in which month did Ezra arrive in Jerusalem, per Ezra 7:9?', 'Ezra 7:9', '...on the first day of the first month he began to go up from Babylon; and on the first day of the fifth month he came to Jerusalem, according to the good hand of his God on him.', 'WEB', 2,
   '{"type": "recall", "template": "...on the first day of the first month he began to go up from Babylon; and on the first day of the ___ month he came to Jerusalem, according to the good hand of his God on him.", "answer": "fifth"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what state did Ezra sit down in after hearing of the intermarriage, per Ezra 9:3?', 'Ezra 9:3', 'When I heard this thing, I tore my garment and my robe, and pulled the hair out of my head and of my beard, and sat down confounded.', 'WEB', 2,
   '{"type": "recall", "template": "When I heard this thing, I tore my garment and my robe, and pulled the hair out of my head and of my beard, and sat down ___.", "answer": "confounded"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: how did Ezra describe himself at the start of his prayer of confession, per Ezra 9:6?', 'Ezra 9:6', 'My God, I am ashamed and blush to lift up my face to you, my God, for our iniquities have increased over our head...', 'WEB', 3,
   '{"type": "recall", "template": "My God, I am ___ and blush to lift up my face to you, my God, for our iniquities have increased over our head...", "answer": "ashamed"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: how did the assembled people weep, per Ezra 10:1?', 'Ezra 10:1', 'Now while Ezra prayed and made confession, weeping and casting himself down before God''s house, there was gathered together to him out of Israel a very great assembly of men and women and children; for the people wept very bitterly.', 'WEB', 2,
   '{"type": "recall", "template": "Now while Ezra prayed and made confession, weeping and casting himself down before God''s house, there was gathered together to him out of Israel a very great assembly of men and women and children; for the people wept very ___.", "answer": "bitterly"}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Ezra 3:13, why couldn''t the people tell the shout of joy from the sound of weeping?', 'Ezra 3:13', '...so that the people could not discern the noise of the shout of joy from the noise of the weeping of the people; for the people shouted with a loud shout, and the noise was heard far away.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Both sounds were loud and mixed together as the foundation was laid", "The weeping stopped before the shouting began", "Only the priests were allowed to make noise", "The text does not say"], "correct_index": 0}', true, 13),
  ((select id from w), 'sequence', 'Put these events of the temple''s rebuilding in the order they occur in the text.', 'Ezra 3:3; 3:11-13; 4-6; 6:14-16', 'Ezra 3:3; Ezra 3:11-13; Ezra 4-6; Ezra 6:14-16', 'WEB', 3,
   '{"type": "sequence", "items": ["The altar is rebuilt in spite of fear of the surrounding peoples", "The temple''s foundation is laid with singing and shouting, joy and weeping mixed together", "Opposition halts the work for years, until Haggai and Zechariah spur the people to resume", "The temple is finished and dedicated with joy"], "correct_order": [0, 1, 2, 3]}', true, 14),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Ezra 1:3; 3:11; 7:10', 'Ezra 1:3; Ezra 3:11; Ezra 7:10', 'WEB', 4,
   '{"type": "sequence", "items": ["“...let him go up to Jerusalem, which is in Judah, and build the house of Yahweh...” — Cyrus''s decree (Ezra 1:3)", "“For he is good, for his loving kindness endures forever toward Israel.” — sung as the temple''s foundation was laid (Ezra 3:11)", "“For Ezra had set his heart to seek Yahweh''s law, and to do it, and to teach statutes and ordinances in Israel.” (Ezra 7:10)"], "correct_order": [0, 1, 2]}', true, 15)
;

with w as (select id from public.world where book_slug = 'nehemiah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word describing the state of Jerusalem''s wall, per Nehemiah 1:3.', 'Nehemiah 1:3', 'The remnant who are left of the captivity there in the province are in great affliction and reproach. The wall of Jerusalem is also broken down, and its gates are burned with fire.', 'WEB', 2,
   '{"type": "recall", "template": "The remnant who are left of the captivity there in the province are in great affliction and reproach. The wall of Jerusalem is also ___ down, and its gates are burned with fire.", "answer": "broken"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nehemiah do when he heard the news, per Nehemiah 1:4?', 'Nehemiah 1:4', 'When I heard these words, I sat down and wept, and mourned several days; and I fasted and prayed before the God of heaven.', 'WEB', 1,
   '{"type": "recall", "template": "When I heard these words, I sat down and ___, and mourned several days; and I fasted and prayed before the God of heaven.", "answer": "wept"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nehemiah ask the king''s permission to do, per Nehemiah 2:4-5?', 'Nehemiah 2:4-5', 'The king said to me, ''What is your request?'' So I prayed to the God of heaven. I said to the king, ''...I ask that you would send me to Judah, to the city of my fathers'' tombs, that I may build it.''', 'WEB', 2,
   '{"type": "recall", "template": "The king said to me, ''What is your request?'' So I prayed to the God of heaven. I said to the king, ''...I ask that you would send me to Judah, to the city of my fathers'' tombs, that I may ___ it.''", "answer": "build"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what did the people say they would avoid by rebuilding the wall, per Nehemiah 2:17-18?', 'Nehemiah 2:17-18', '''Come, let''s build up the wall of Jerusalem, that we won''t be disgraced.'' ...They said, ''Let''s rise up and build.'' So they strengthened their hands for the good work.', 'WEB', 1,
   '{"type": "recall", "template": "''Come, let''s build up the wall of Jerusalem, that we won''t be ___.'' ...They said, ''Let''s rise up and build.'' So they strengthened their hands for the good work.", "answer": "disgraced"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what did the builders hold in their other hand while working, per Nehemiah 4:17?', 'Nehemiah 4:17', 'Those who built the wall, and those who bore burdens loaded themselves; everyone with one of his hands did the work, and with the other held his weapon.', 'WEB', 3,
   '{"type": "recall", "template": "Those who built the wall, and those who bore burdens loaded themselves; everyone with one of his hands did the work, and with the other held his ___.", "answer": "weapon"}', false, 5),
  ((select id from w), 'multiple_choice', 'How many days did it take to finish rebuilding Jerusalem''s wall, according to Nehemiah 6:15?', 'Nehemiah 6:15', 'So the wall was finished in the twenty-fifth day of Elul, in fifty-two days. When all our enemies heard of it, all the nations that were around us were afraid, and they lost their confidence; for they perceived that this work was done by our God.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Fifty-two", "Forty", "Seventy", "One hundred"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nehemiah and Ezra say the joy of Yahweh was, per Nehemiah 8:9-10?', 'Nehemiah 8:9-10', '''Today is holy to Yahweh your God. Don''t mourn, nor weep.'' ... ''Don''t be grieved, for the joy of Yahweh is your strength.''', 'WEB', 1,
   '{"type": "recall", "template": "''Today is holy to Yahweh your God. Don''t mourn, nor weep.'' ... ''Don''t be grieved, for the joy of Yahweh is your ___.''", "answer": "strength"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: until what time of day did Ezra read the Law, per Nehemiah 8:3?', 'Nehemiah 8:3', 'He read from it before the wide place that was in front of the water gate from early morning until midday, in the presence of the men and the women, and of those who could understand.', 'WEB', 2,
   '{"type": "recall", "template": "He read from it before the wide place that was in front of the water gate from early morning until ___, in the presence of the men and the women, and of those who could understand.", "answer": "midday"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word describing how the people assembled, per Nehemiah 9:1-2.', 'Nehemiah 9:1-2', 'Now in the twenty-fourth day of this month the children of Israel were assembled with fasting, with sackcloth, and dirt on them. ...and stood and confessed their sins and the iniquities of their fathers.', 'WEB', 2,
   '{"type": "recall", "template": "Now in the twenty-fourth day of this month the children of Israel were assembled with ___, with sackcloth, and dirt on them. ...and stood and confessed their sins and the iniquities of their fathers.", "answer": "fasting"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what did the people make and seal, per Nehemiah 9:38?', 'Nehemiah 9:38', 'Yet for all this, we make a sure covenant, and write it; and our princes, our Levites, and our priests, seal it.', 'WEB', 2,
   '{"type": "recall", "template": "Yet for all this, we make a sure ___, and write it; and our princes, our Levites, and our priests, seal it.", "answer": "covenant"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did Nehemiah command be done to Jerusalem''s gates before the Sabbath, per Nehemiah 13:19?', 'Nehemiah 13:19', 'It came to pass that when the gates of Jerusalem began to be dark before the Sabbath, I commanded that the doors should be shut, and commanded that they should not be opened until after the Sabbath...', 'WEB', 2,
   '{"type": "recall", "template": "It came to pass that when the gates of Jerusalem began to be dark before the Sabbath, I commanded that the doors should be ___, and commanded that they should not be opened until after the Sabbath...", "answer": "shut"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: who did Nehemiah command to purify themselves and keep the gates, per Nehemiah 13:22?', 'Nehemiah 13:22', 'I commanded the Levites that they should purify themselves, and that they should come and keep the gates, to sanctify the Sabbath day...', 'WEB', 1,
   '{"type": "recall", "template": "I commanded the ___ that they should purify themselves, and that they should come and keep the gates, to sanctify the Sabbath day...", "answer": "Levites"}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Nehemiah 8:9-10, why did Nehemiah and Ezra tell the people not to weep?', 'Nehemiah 8:9-10', '''Today is holy to Yahweh your God. Don''t mourn, nor weep.'' ... ''Don''t be grieved, for the joy of Yahweh is your strength.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["The day was holy, and the joy of Yahweh was their strength", "The wall was not yet finished", "Ezra had not read the whole Law yet", "The king had ordered a celebration"], "correct_index": 0}', true, 13),
  ((select id from w), 'sequence', 'Put these events of the wall''s rebuilding in the order they occur in the text.', 'Nehemiah 1:4; 2:5; 4:17; 6:15', 'Nehemiah 1:4; Nehemiah 2:5; Nehemiah 4:17; Nehemiah 6:15', 'WEB', 3,
   '{"type": "sequence", "items": ["Nehemiah hears the news of Jerusalem''s broken wall and mourns", "Nehemiah asks the king''s permission to go rebuild", "The people rebuild the wall while holding a weapon in one hand", "The wall is finished in fifty-two days"], "correct_order": [0, 1, 2, 3]}', true, 14),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Nehemiah 1:3; 2:5; 6:16', 'Nehemiah 1:3; Nehemiah 2:5; Nehemiah 6:16', 'WEB', 4,
   '{"type": "sequence", "items": ["“The wall of Jerusalem is also broken down, and its gates are burned with fire.” — Nehemiah 1:3", "“...I ask that you would send me to Judah, to the city of my fathers'' tombs, that I may build it.” — Nehemiah 2:5", "“...for they perceived that this work was done by our God.” — Nehemiah 6:16"], "correct_order": [0, 1, 2]}', true, 15)
;

with w as (select id from public.world where book_slug = 'esther')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing name: who took Esther as his own daughter, per Esther 2:7?', 'Esther 2:7', 'He brought up Hadassah, that is, Esther, his uncle''s daughter; for she had neither father nor mother. The maiden was fair and beautiful; and when her father and mother were dead, Mordecai took her for his own daughter.', 'WEB', 1,
   '{"type": "recall", "template": "He brought up Hadassah, that is, Esther, his uncle''s daughter; for she had neither father nor mother. The maiden was fair and beautiful; and when her father and mother were dead, ___ took her for his own daughter.", "answer": "Mordecai"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what did Esther obtain in the sight of all who looked at her, per Esther 2:15?', 'Esther 2:15', 'Now when the turn of Esther... came to go in to the king, she required nothing but what Hegai the king''s eunuch, the keeper of the women, advised. Esther obtained favor in the sight of all those who looked at her.', 'WEB', 2,
   '{"type": "recall", "template": "Now when the turn of Esther... came to go in to the king, she required nothing but what Hegai the king''s eunuch, the keeper of the women, advised. Esther obtained ___ in the sight of all those who looked at her.", "answer": "favor"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing name: whom did Esther replace as queen, per Esther 2:17?', 'Esther 2:17', 'The king loved Esther more than all the women, and she obtained favor and kindness in his sight more than all the virgins; so that he set the royal crown on her head, and made her queen instead of Vashti.', 'WEB', 1,
   '{"type": "recall", "template": "The king loved Esther more than all the women, and she obtained favor and kindness in his sight more than all the virgins; so that he set the royal crown on her head, and made her queen instead of ___.", "answer": "Vashti"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what was Haman full of when Mordecai wouldn''t bow to him, per Esther 3:5-6?', 'Esther 3:5-6', 'When Haman saw that Mordecai didn''t bow down nor pay him homage, Haman was full of wrath... Haman sought to destroy all the Jews who were throughout the whole kingdom of Ahasuerus, even Mordecai''s people.', 'WEB', 2,
   '{"type": "recall", "template": "When Haman saw that Mordecai didn''t bow down nor pay him homage, Haman was full of ___... Haman sought to destroy all the Jews who were throughout the whole kingdom of Ahasuerus, even Mordecai''s people.", "answer": "wrath"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Esther 3:13, who did the king''s decree target?', 'Esther 3:13', 'Letters were sent by couriers into all the king''s provinces, to destroy, to kill, and to cause to perish, all Jews, both young and old, little children and women, in one day, even on the thirteenth day of the twelfth month, which is the month Adar, and to plunder their possessions.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["All Jews, young and old, throughout the kingdom", "Only Mordecai and his family", "Only the officials who refused to bow", "The people of Susa only"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Haman ask the king to have written, per Esther 3:9?', 'Esther 3:9', '''If it pleases the king, let it be written that they be destroyed; and I will pay ten thousand talents of silver into the hands of those who are in charge of the king''s business...''', 'WEB', 2,
   '{"type": "recall", "template": "''If it pleases the king, let it be written that they be ___; and I will pay ten thousand talents of silver into the hands of those who are in charge of the king''s business...''", "answer": "destroyed"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing words from Mordecai''s famous appeal to Esther, per Esther 4:13-14.', 'Esther 4:13-14', 'Don''t think to yourself that you will escape in the king''s house any more than all the Jews. For if you remain silent now, then relief and deliverance will come to the Jews from another place, but you and your father''s house will perish. Who knows if you haven''t come to the kingdom for such a time as this?', 'WEB', 1,
   '{"type": "recall", "template": "Don''t think to yourself that you will escape in the king''s house any more than all the Jews. For if you remain silent now, then relief and deliverance will come to the Jews from another place, but you and your father''s house will perish. Who knows if you haven''t come to the kingdom for ___?", "answer": "such a time as this"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word closing Esther''s resolve, per Esther 4:16.', 'Esther 4:16', 'Go, gather together all the Jews who are present in Susa, and fast for me, and neither eat nor drink three days, night or day. I and my maidens will also fast the same way. Then I will go in to the king, which is against the law; and if I perish, I perish.', 'WEB', 2,
   '{"type": "recall", "template": "Go, gather together all the Jews who are present in Susa, and fast for me, and neither eat nor drink three days, night or day. I and my maidens will also fast the same way. Then I will go in to the king, which is against the law; and if I perish, I ___.", "answer": "perish"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what did Esther ask for herself, per Esther 7:3-4?', 'Esther 7:3-4', 'Esther the queen answered, ''If I have found favor in your sight, O king, and if it pleases the king, let my life be given me at my petition, and my people at my request. For we are sold, I and my people, to be destroyed, to be slain, and to perish...''', 'WEB', 2,
   '{"type": "recall", "template": "Esther the queen answered, ''If I have found favor in your sight, O king, and if it pleases the king, let my life be given me at my ___, and my people at my request. For we are sold, I and my people, to be destroyed, to be slain, and to perish...''", "answer": "petition"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what word does ''Purim'' come from, per Esther 9:26?', 'Esther 9:26', 'Therefore they called these days ''Purim,'' from the word ''Pur.''', 'WEB', 1,
   '{"type": "recall", "template": "Therefore they called these days ''Purim,'' from the word ''___.''", "answer": "Pur"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what was the month turned to, from sorrow, per Esther 9:22?', 'Esther 9:22', '...the days in which the Jews had rest from their enemies, and the month which was turned to them from sorrow to gladness, and from mourning into a holiday; that they should make them days of feasting and gladness, and of sending presents of food to one another, and gifts to the needy.', 'WEB', 2,
   '{"type": "recall", "template": "...the days in which the Jews had rest from their enemies, and the month which was turned to them from sorrow to ___, and from mourning into a holiday; that they should make them days of feasting and gladness, and of sending presents of food to one another, and gifts to the needy.", "answer": "gladness"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: throughout every what should the days of Purim be kept, per Esther 9:28?', 'Esther 9:28', '...these days should be remembered and kept throughout every generation, every family, every province, and every city; and that these days of Purim should not fail from among the Jews, nor their memory perish from their offspring.', 'WEB', 2,
   '{"type": "recall", "template": "...these days should be remembered and kept throughout every ___, every family, every province, and every city; and that these days of Purim should not fail from among the Jews, nor their memory perish from their offspring.", "answer": "generation"}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Esther 7:9-10, what happened to the gallows Haman built for Mordecai?', 'Esther 7:9-10', 'Harbonah... said, ''Behold, the gallows fifty cubits high, which Haman has made for Mordecai... is standing at Haman''s house.'' The king said, ''Hang him on it!'' So they hanged Haman on the gallows that he had prepared for Mordecai...', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Haman himself was hanged on it", "It was torn down before use", "Mordecai was hanged on it", "The king ordered it burned"], "correct_index": 0}', true, 13),
  ((select id from w), 'sequence', 'Put these events of the story in the order they occur in the text.', 'Esther 2:17; 3:13; 4:16; 7:9-10; 9:26', 'Esther 2:17; Esther 3:13; Esther 4:16; Esther 7:9-10; Esther 9:26', 'WEB', 3,
   '{"type": "sequence", "items": ["Esther becomes queen in place of Vashti", "Haman''s decree against the Jews is issued", "Esther decides to approach the king despite the danger", "Haman is hanged on the gallows he built for Mordecai", "The Jews are delivered, and the festival of Purim is established"], "correct_order": [0, 1, 2, 3, 4]}', true, 14),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text.', 'Esther 4:14; 4:16; 7:3-4', 'Esther 4:14; Esther 4:16; Esther 7:3-4', 'WEB', 4,
   '{"type": "sequence", "items": ["“Who knows if you haven''t come to the kingdom for such a time as this?” — Mordecai''s appeal (Esther 4:14)", "“...if I perish, I perish.” — Esther''s resolve (Esther 4:16)", "“For we are sold, I and my people, to be destroyed, to be slain, and to perish...” — Esther''s plea to the king (Esther 7:3-4)"], "correct_order": [0, 1, 2]}', true, 15)
;
