-- Gen2Rev challenge ingest: Habakkuk (World 35), Zephaniah (World 36), Haggai (World 37)
-- Generated from docs/content/habakkuk.md, docs/content/zephaniah.md, docs/content/haggai.md
-- All three books: theological review approved, independent verbatim-text QA complete
-- (docs/CONTENT_REVIEW_LOG.md rows 35-37, docs/QA_SIGNOFF.md rows 35-37).
-- Habakkuk 1:5-11/1:12-17 (Chaldean detail beyond the complaint itself), Zephaniah 1:16-18
-- (graphic judgment imagery) and 2:4-15 (oracles against the nations), and Haggai 2:10-19
-- (ritual-purity dialogue) and 2:20-23 (the signet-ring oracle) are permanently excluded per
-- each book's brief; see docs/content/habakkuk.md, docs/content/zephaniah.md, and
-- docs/content/haggai.md "Contested Territory" sections.

with w as (select id from public.world where book_slug = 'habakkuk')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: in his opening complaint, what does Habakkuk say Yahweh will not do, despite his cry?', 'Habakkuk 1:2', 'Yahweh, how long will I cry, and you will not hear? I cry out to you ''Violence!'' and will you not save?', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh, how long will I cry, and you will not ___? I cry out to you ''Violence!'' and will you not save?", "answer": "hear"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what does Habakkuk say Yahweh shows him, alongside perversity?', 'Habakkuk 1:3', 'Why do you show me iniquity, and look at perversity? For destruction and violence are before me.', 'WEB', 2,
   '{"type": "recall", "template": "Why do you show me ___, and look at perversity? For destruction and violence are before me.", "answer": "iniquity"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what does Habakkuk say happens to the law because the wicked surround the righteous?', 'Habakkuk 1:4', 'Therefore the law is paralyzed, and justice never prevails; for the wicked surround the righteous; therefore justice comes out perverted.', 'WEB', 3,
   '{"type": "recall", "template": "Therefore the law is ___, and justice never prevails; for the wicked surround the righteous; therefore justice comes out perverted.", "answer": "paralyzed"}', false, 3),
  ((select id from w), 'multiple_choice', 'Where does Habakkuk say he will stand to watch for Yahweh''s answer?', 'Habakkuk 2:1', 'I will stand at my watch and set myself on the ramparts, and will look out to see what he will say to me, and what I will answer concerning my complaint.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["At his watch, on the ramparts", "At the city gate", "On the mountain", "In the temple courtyard"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh tell Habakkuk to write the vision plainly on?', 'Habakkuk 2:2', 'Yahweh answered me, ''Write the vision, and make it plain on tablets, that he who runs may read it.''', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh answered me, ''Write the vision, and make it plain on ___, that he who runs may read it.''", "answer": "tablets"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Habakkuk 2:3, what does Yahweh say to do about the vision, even if it takes time to come true?', 'Habakkuk 2:3', 'For the vision is yet for the appointed time, and it hurries toward the end, and won''t prove false. Though it takes time, wait for it, because it will surely come. It won''t delay.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["Wait for it, because it will surely come", "Forget it and move on", "Ask a different prophet to confirm it", "Rewrite it every year"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: according to Habakkuk 2:4, the righteous will live by his what?', 'Habakkuk 2:4', 'Behold, his soul is puffed up. It is not upright in him, but the righteous will live by his faith.', 'WEB', 1,
   '{"type": "recall", "template": "Behold, his soul is puffed up. It is not upright in him, but the righteous will live by his ___.", "answer": "faith"}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: according to Habakkuk 2:14, what will the earth be filled with the knowledge of?', 'Habakkuk 2:14', 'For the earth will be filled with the knowledge of Yahweh''s glory, as the waters cover the sea.', 'WEB', 2,
   '{"type": "recall", "template": "For the earth will be filled with the knowledge of Yahweh''s ___, as the waters cover the sea.", "answer": "glory"}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Habakkuk 3:17, which of these is NOT listed as a source of provision that may fail?', 'Habakkuk 3:17', 'For even though the fig tree doesn''t flourish, nor fruit be in the vines, the labor of the olive fails, the fields yield no food, the flocks are cut off from the fold, and there is no herd in the stalls,', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["The fig tree and vines", "The flocks and the herd", "Silver and gold", "The olive and the fields"], "correct_index": 2}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: even though every source of provision fails, what does Habakkuk say he will do in Yahweh?', 'Habakkuk 3:18', 'yet I will rejoice in Yahweh. I will be joyful in the God of my salvation!', 'WEB', 1,
   '{"type": "recall", "template": "yet I will ___ in Yahweh. I will be joyful in the God of my salvation!", "answer": "rejoice"}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what does Habakkuk call Yahweh, the Lord, in 3:19?', 'Habakkuk 3:19', 'Yahweh, the Lord, is my strength. He makes my feet like deer''s feet, and enables me to go in high places.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh, the Lord, is my ___. He makes my feet like deer''s feet, and enables me to go in high places.", "answer": "strength"}', false, 11),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Habakkuk 1:2; 2:4; 3:18', 'The prophet''s complaint; the righteous will live by his faith; rejoicing in Yahweh', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Yahweh, how long will I cry, and you will not hear?\" — the prophet''s opening complaint (1:2)", "\"The righteous will live by his faith.\" — Yahweh''s answer (2:4)", "\"Yet I will rejoice in Yahweh.\" — the closing resolution (3:18)"], "correct_order": [0, 1, 2]}', false, 12),
  ((select id from w), 'sequence', 'Put these pivotal passages in the order they appear in the book of Habakkuk.', 'Habakkuk 1:2-4; 2:1-4; 2:14; 3:17-19', 'The prophet''s complaint; Yahweh''s answer; the earth filled with glory; rejoicing despite total loss', 'WEB', 3,
   '{"type": "sequence", "items": ["The prophet''s complaint (1:2-4)", "Yahweh''s answer: \"the righteous will live by his faith\" (2:1-4)", "The earth filled with the knowledge of Yahweh''s glory (2:14)", "Rejoicing despite total loss (3:17-19)"], "correct_order": [0, 1, 2, 3]}', true, 13)
;

with w as (select id from public.world where book_slug = 'zephaniah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: according to Zephaniah 1:14, how does the text describe the great day of Yahweh drawing close?', 'Zephaniah 1:14', 'The great day of Yahweh is near. It is near and hurries greatly, the voice of the day of Yahweh. The mighty man cries there bitterly.', 'WEB', 2,
   '{"type": "recall", "template": "The great day of Yahweh is ___. It is near and hurries greatly, the voice of the day of Yahweh. The mighty man cries there bitterly.", "answer": "near"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what is the first thing Zephaniah 1:15 calls that day a day of?', 'Zephaniah 1:15', 'That day is a day of wrath, a day of distress and anguish, a day of trouble and ruin, a day of darkness and gloom, a day of clouds and blackness,', 'WEB', 2,
   '{"type": "recall", "template": "That day is a day of ___, a day of distress and anguish, a day of trouble and ruin, a day of darkness and gloom, a day of clouds and blackness,", "answer": "wrath"}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Zephaniah 1:14, what does the passage say is near and hurries greatly?', 'Zephaniah 1:14', 'The great day of Yahweh is near. It is near and hurries greatly, the voice of the day of Yahweh. The mighty man cries there bitterly.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The great day of Yahweh", "The rebuilding of the temple", "The coronation of Josiah", "The fall of Nineveh"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: besides Yahweh and righteousness, what does Zephaniah 2:3 tell the humble of the land to seek?', 'Zephaniah 2:3', 'Seek Yahweh, all you humble of the land, who have kept his ordinances. Seek righteousness. Seek humility. It may be that you will be hidden in the day of Yahweh''s anger.', 'WEB', 1,
   '{"type": "recall", "template": "Seek Yahweh, all you humble of the land, who have kept his ordinances. Seek righteousness. Seek ___. It may be that you will be hidden in the day of Yahweh''s anger.", "answer": "humility"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Zephaniah 2:3, besides seeking Yahweh, what two things are the humble of the land told to seek?', 'Zephaniah 2:3', 'Seek Yahweh, all you humble of the land, who have kept his ordinances. Seek righteousness. Seek humility. It may be that you will be hidden in the day of Yahweh''s anger.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["Righteousness and humility", "Wisdom and courage", "Peace and unity", "Mercy and justice"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does Zephaniah 3:14 tell the daughter of Zion to be glad and do?', 'Zephaniah 3:14', 'Sing, daughter of Zion! Shout, Israel! Be glad and rejoice with all your heart, daughter of Jerusalem.', 'WEB', 1,
   '{"type": "recall", "template": "Sing, daughter of Zion! Shout, Israel! Be glad and ___ with all your heart, daughter of Jerusalem.", "answer": "rejoice"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: according to Zephaniah 3:15, what has Yahweh thrown out?', 'Zephaniah 3:15', 'Yahweh has taken away your judgments. He has thrown out your enemy. The King of Israel, Yahweh, is among you. You will not be afraid of evil any more.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh has taken away your judgments. He has thrown out your ___. The King of Israel, Yahweh, is among you. You will not be afraid of evil any more.", "answer": "enemy"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: according to Zephaniah 3:17, how does Yahweh rejoice over his people a second time in the verse?', 'Zephaniah 3:17', 'Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with ___.", "answer": "singing"}', true, 8),
  ((select id from w), 'multiple_choice', 'According to Zephaniah 3:17, how is Yahweh described?', 'Zephaniah 3:17', 'Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A mighty one who will save", "A distant judge", "A silent witness", "An angry king"], "correct_index": 0}', false, 9),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Zephaniah 1:14; 2:3; 3:17', 'The day of Yahweh announced; the call to seek Yahweh; Yahweh rejoices over his people', 'WEB', 4,
   '{"type": "sequence", "items": ["\"The great day of Yahweh is near.\" — the day of Yahweh announced (1:14)", "\"Seek Yahweh, all you humble of the land...\" — the call to seek Yahweh (2:3)", "\"He will rejoice over you with singing.\" — Yahweh rejoices over his people (3:17)"], "correct_order": [0, 1, 2]}', false, 10),
  ((select id from w), 'sequence', 'Put these pivotal passages in the order they appear in the book of Zephaniah.', 'Zephaniah 1:14-15; 2:3; 3:14-15; 3:17', 'The day of Yahweh announced; the call to seek Yahweh; Zion''s coming joy; Yahweh rejoices over his people', 'WEB', 3,
   '{"type": "sequence", "items": ["The Day of Yahweh announced (1:14-15)", "The call to seek Yahweh (2:3)", "Zion''s coming joy (3:14-15)", "Yahweh rejoices over his people (3:17)"], "correct_order": [0, 1, 2, 3]}', true, 11)
;

with w as (select id from public.world where book_slug = 'haggai')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: according to Haggai 1:2, what excuse do the people give about the time for Yahweh''s house?', 'Haggai 1:2', 'This is what Yahweh of Armies says: These people say, ''The time hasn''t yet come, the time for Yahweh''s house to be built.''', 'WEB', 2,
   '{"type": "recall", "template": "This is what Yahweh of Armies says: These people say, ''The time hasn''t yet ___, the time for Yahweh''s house to be built.''", "answer": "come"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: in Haggai 1:4, what condition does Yahweh say his house is in while the people live in paneled houses?', 'Haggai 1:4', 'Is it a time for you yourselves to dwell in your paneled houses, while this house lies waste?', 'WEB', 2,
   '{"type": "recall", "template": "Is it a time for you yourselves to dwell in your paneled houses, while this house lies ___?", "answer": "waste"}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Haggai 1:2, what excuse did the people give for not building Yahweh''s house?', 'Haggai 1:2', 'This is what Yahweh of Armies says: These people say, ''The time hasn''t yet come, the time for Yahweh''s house to be built.''', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["That the time had not yet come", "That they lacked wood", "That the king had forbidden it", "That Zerubbabel was ill"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: in Haggai 1:8, what does Yahweh command the people to go up to the mountain and build?', 'Haggai 1:8', '''Go up to the mountain, bring wood, and build the house. I will take pleasure in it, and I will be glorified,'' says Yahweh.', 'WEB', 1,
   '{"type": "recall", "template": "''Go up to the mountain, bring wood, and build the ___. I will take pleasure in it, and I will be glorified,'' says Yahweh.", "answer": "house"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Haggai 1:8, what does Yahweh promise if the people build the house?', 'Haggai 1:8', '''Go up to the mountain, bring wood, and build the house. I will take pleasure in it, and I will be glorified,'' says Yahweh.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["He will take pleasure in it and be glorified", "He will send rain and an abundant harvest", "He will double the size of Jerusalem", "He will restore the ark of the covenant"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: according to Haggai 1:12, what did the people do toward Yahweh after they obeyed?', 'Haggai 1:12', 'Then Zerubbabel the son of Shealtiel and Joshua the son of Jehozadak, the high priest, with all the remnant of the people, obeyed Yahweh their God''s voice, and the words of Haggai the prophet, as Yahweh their God had sent him; and the people feared Yahweh.', 'WEB', 2,
   '{"type": "recall", "template": "Then Zerubbabel the son of Shealtiel and Joshua the son of Jehozadak, the high priest, with all the remnant of the people, obeyed Yahweh their God''s voice, and the words of Haggai the prophet, as Yahweh their God had sent him; and the people ___ Yahweh.", "answer": "feared"}', false, 6),
  ((select id from w), 'multiple_choice', 'According to Haggai 1:12, who obeyed Yahweh''s voice and the words of Haggai the prophet?', 'Haggai 1:12', 'Then Zerubbabel the son of Shealtiel and Joshua the son of Jehozadak, the high priest, with all the remnant of the people, obeyed Yahweh their God''s voice, and the words of Haggai the prophet, as Yahweh their God had sent him; and the people feared Yahweh.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Zerubbabel, Joshua the high priest, and the remnant of the people", "Only the priests", "Only Zerubbabel", "The prophets Zechariah and Malachi"], "correct_index": 0}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: in Haggai 1:13, what reassurance does Yahweh send the people through Haggai?', 'Haggai 1:13', 'Then Haggai, Yahweh''s messenger, spoke Yahweh''s message to the people, saying, ''I am with you,'' says Yahweh.', 'WEB', 1,
   '{"type": "recall", "template": "Then Haggai, Yahweh''s messenger, spoke Yahweh''s message to the people, saying, ''I am ___ you,'' says Yahweh.", "answer": "with"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: in Haggai 2:4, what does Yahweh repeatedly tell Zerubbabel, Joshua, and the people of the land to be?', 'Haggai 2:4', '''Yet now be strong, Zerubbabel,'' says Yahweh. ''Be strong, Joshua son of Jehozadak, the high priest. Be strong, all you people of the land,'' says Yahweh, ''and work, for I am with you,'' says Yahweh of Armies.', 'WEB', 1,
   '{"type": "recall", "template": "''Yet now be ___, Zerubbabel,'' says Yahweh. ''Be strong, Joshua son of Jehozadak, the high priest. Be strong, all you people of the land,'' says Yahweh, ''and work, for I am with you,'' says Yahweh of Armies.", "answer": "strong"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: according to Haggai 2:9, how does Yahweh say the latter glory of the house compares to the former?', 'Haggai 2:9', '''The latter glory of this house will be greater than the former,'' says Yahweh of Armies; ''and in this place I will give peace,'' says Yahweh of Armies.', 'WEB', 1,
   '{"type": "recall", "template": "''The latter glory of this house will be ___ than the former,'' says Yahweh of Armies; ''and in this place I will give peace,'' says Yahweh of Armies.", "answer": "greater"}', true, 10),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Haggai 1:4; 1:13; 2:9', 'The Lord''s rebuke; reassurance after the people obey; the promise of latter glory', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Is it a time for you yourselves to dwell in your paneled houses, while this house lies waste?\" — the Lord''s rebuke (1:4)", "\"I am with you,\" says Yahweh. — reassurance after the people obey (1:13)", "\"The latter glory of this house will be greater than the former.\" — the promise of latter glory (2:9)"], "correct_order": [0, 1, 2]}', false, 11),
  ((select id from w), 'sequence', 'Put these pivotal passages in the order they appear in the book of Haggai.', 'Haggai 1:2, 1:4; 1:8; 1:12-13; 2:4, 2:9', 'The people''s excuse and the Lord''s rebuke; the command to rebuild; the people obey; be strong and the latter glory', 'WEB', 3,
   '{"type": "sequence", "items": ["The people''s excuse and the Lord''s rebuke (1:2, 1:4)", "The command to rebuild (1:8)", "The people obey (1:12-13)", "Be strong, and the latter glory (2:4, 2:9)"], "correct_order": [0, 1, 2, 3]}', true, 12)
;
