-- Gen2Rev challenge ingest: Hosea (World 28), Joel (World 29), Amos (World 30), Obadiah (World 31)
-- Generated from docs/content/hosea.md, docs/content/joel.md, docs/content/amos.md, docs/content/obadiah.md
-- All four books: theological review complete, independent verbatim-text QA pass complete
-- (docs/CONTENT_REVIEW_LOG.md rows 28-31, docs/QA_SIGNOFF.md rows 28-31).
-- Hosea 1:2, 1:10, 3:1, 3:5, and 6:1-3 are restricted to recall/fill-in-blank format only
-- (never multiple_choice), per docs/content/hosea.md's Contested Territory structural rules.
-- Amos 9:11-12 and the second sentence of Amos 2:7 are permanently excluded per
-- docs/content/amos.md's Contested Territory section.

with w as (select id from public.world where book_slug = 'hosea')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say the land is committing, in forsaking him?', 'Hosea 1:2', 'When Yahweh spoke at first by Hosea, Yahweh said to Hosea, ''Go, take for yourself a wife of prostitution and children of unfaithfulness; for the land commits great adultery, forsaking Yahweh.''', 'WEB', 1,
   '{"type": "recall", "template": "When Yahweh spoke at first by Hosea, Yahweh said to Hosea, ''Go, take for yourself a wife of prostitution and children of unfaithfulness; for the land commits great ___, forsaking Yahweh.''", "answer": "adultery"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what name was Hosea told to give his son, meaning judgment on the house of Jehu?', 'Hosea 1:4', 'Yahweh said to him, ''Call his name Jezreel, for yet a little while, and I will avenge the blood of Jezreel on the house of Jehu, and will cause the kingdom of the house of Israel to cease.''', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh said to him, ''Call his name ___, for yet a little while, and I will avenge the blood of Jezreel on the house of Jehu, and will cause the kingdom of the house of Israel to cease.''", "answer": "Jezreel"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what name was Hosea told to give his daughter, meaning "not pitied"?', 'Hosea 1:6', 'She conceived again, and bore a daughter. Then he said to him, ''Call her name Lo-Ruhamah, for I will no longer have mercy on the house of Israel, that I should in any way pardon them.''', 'WEB', 1,
   '{"type": "recall", "template": "She conceived again, and bore a daughter. Then he said to him, ''Call her name ___, for I will no longer have mercy on the house of Israel, that I should in any way pardon them.''", "answer": "Lo-Ruhamah"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what name was Hosea told to give this son, meaning "not my people"?', 'Hosea 1:9', 'He said, ''Call his name Lo-Ammi, for you are not my people, and I will not be yours.''', 'WEB', 1,
   '{"type": "recall", "template": "He said, ''Call his name ___, for you are not my people, and I will not be yours.''", "answer": "Lo-Ammi"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what will the children of Israel be called, reversing "you are not my people"?', 'Hosea 1:10', 'Yet the number of the children of Israel will be as the sand of the sea, which can''t be measured or counted; and it will come to pass that, in the place where it was said to them, ''You are not my people,'' they will be called ''sons of the living God.''', 'WEB', 2,
   '{"type": "recall", "template": "Yet the number of the children of Israel will be as the sand of the sea, which can''t be measured or counted; and it will come to pass that, in the place where it was said to them, ''You are not my people,'' they will be called ''sons of the living ___.''", "answer": "God"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: where does the text say Israel came up out of, in the days of her youth?', 'Hosea 2:14-15', 'Therefore behold, I will allure her, and bring her into the wilderness, and speak tenderly to her. I will give her vineyards from there, and the valley of Achor for a door of hope; and she will respond there as in the days of her youth, and as in the day when she came up out of the land of Egypt.', 'WEB', 2,
   '{"type": "recall", "template": "Therefore behold, I will allure her, and bring her into the wilderness, and speak tenderly to her. I will give her vineyards from there, and the valley of Achor for a door of hope; and she will respond there as in the days of her youth, and as in the day when she came up out of the land of ___.", "answer": "Egypt"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what will Israel call Yahweh, no longer calling him "my master"?', 'Hosea 2:16', '"It will be in that day," says Yahweh, "that you will call me ''my husband,'' and no longer call me ''my master.''"', 'WEB', 2,
   '{"type": "recall", "template": "\"It will be in that day,\" says Yahweh, \"that you will call me ''my ___,'' and no longer call me ''my master.''\"", "answer": "husband"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Hosea 2:19-20, in what does Yahweh say he will betroth Israel to himself forever?', 'Hosea 2:19-20', 'I will betroth you to me forever. Yes, I will betroth you to me in righteousness, in justice, in loving kindness, and in compassion. I will even betroth you to me in faithfulness; and you shall know Yahweh.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["Righteousness, justice, loving kindness, and faithfulness", "Wisdom, strength, glory, and honor", "Mercy, grace, peace, and hope", "Obedience, sacrifice, fasting, and prayer"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say Israel loves, along with turning to other gods?', 'Hosea 3:1', 'Yahweh said to me, ''Go again, love a woman loved by another, and an adulteress, even as Yahweh loves the children of Israel, though they turn to other gods, and love cakes of raisins.''', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh said to me, ''Go again, love a woman loved by another, and an adulteress, even as Yahweh loves the children of Israel, though they turn to other gods, and love cakes of ___.''", "answer": "raisins"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Hosea 3:2, what price did Hosea pay to buy back his wife?', 'Hosea 3:2-3', 'So I bought her for myself for fifteen pieces of silver and a homer and a half of barley. I said to her, ''You shall stay with me many days. You shall not play the prostitute, and you shall not be with any other man. I will also be so toward you.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Fifteen pieces of silver and a homer and a half of barley", "Thirty pieces of silver", "Fifty shekels of silver and a lamb", "Twenty pieces of gold and a measure of wheat"], "correct_index": 0}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: how does the text say Israel will come to Yahweh and his blessings in the last days?', 'Hosea 3:5', 'Afterward the children of Israel shall return and seek Yahweh their God, and David their king, and shall come with trembling to Yahweh and to his blessings in the last days.', 'WEB', 2,
   '{"type": "recall", "template": "Afterward the children of Israel shall return and seek Yahweh their God, and David their king, and shall come with ___ to Yahweh and to his blessings in the last days.", "answer": "trembling"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh''s charge say is missing from the land?', 'Hosea 4:1', 'Hear Yahweh''s word, you children of Israel, for Yahweh has a charge against the inhabitants of the land: ''Indeed there is no truth, nor goodness, nor knowledge of God in the land.''', 'WEB', 2,
   '{"type": "recall", "template": "Hear Yahweh''s word, you children of Israel, for Yahweh has a charge against the inhabitants of the land: ''Indeed there is no truth, nor goodness, nor ___ of God in the land.''", "answer": "knowledge"}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Hosea 4:2, which of these does the text name as evidence of Israel''s guilt?', 'Hosea 4:2', 'There is cursing, lying, murder, stealing, and committing adultery; they break boundaries, and bloodshed causes bloodshed.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["Cursing, lying, murder, stealing, and adultery", "Idolatry, drunkenness, and slander only", "Neglecting the Sabbath and tithes", "Foreign alliances and false weights"], "correct_index": 0}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say Israel may no longer be to him, for rejecting knowledge?', 'Hosea 4:6', 'My people are destroyed for lack of knowledge. Because you have rejected knowledge, I will also reject you, that you may be no priest to me. Because you have forgotten your God''s law, I will also forget your children.', 'WEB', 2,
   '{"type": "recall", "template": "My people are destroyed for lack of knowledge. Because you have rejected knowledge, I will also reject you, that you may be no ___ to me. Because you have forgotten your God''s law, I will also forget your children.", "answer": "priest"}', false, 14),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say Yahweh will do to the people "after two days"?', 'Hosea 6:1-3', 'Come! Let''s return to Yahweh; for he has torn us to pieces, and he will heal us; he has injured us, and he will bind up our wounds. After two days he will revive us. On the third day he will raise us up, and we will live before him. Let''s acknowledge Yahweh. Let''s press on to know Yahweh. As surely as the sun rises, Yahweh will appear. He will come to us like the rain, like the spring rain that waters the earth.', 'WEB', 2,
   '{"type": "recall", "template": "Come! Let''s return to Yahweh; for he has torn us to pieces, and he will heal us; he has injured us, and he will bind up our wounds. After two days he will ___ us. On the third day he will raise us up, and we will live before him. Let''s acknowledge Yahweh. Let''s press on to know Yahweh. As surely as the sun rises, Yahweh will appear. He will come to us like the rain, like the spring rain that waters the earth.", "answer": "revive"}', false, 15),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text compare Ephraim and Judah''s love to?', 'Hosea 6:4', 'Ephraim, what shall I do to you? Judah, what shall I do to you? For your love is like a morning cloud, and like the dew that disappears early.', 'WEB', 1,
   '{"type": "recall", "template": "Ephraim, what shall I do to you? Judah, what shall I do to you? For your love is like a morning ___, and like the dew that disappears early.", "answer": "cloud"}', false, 16),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say he desires, and not sacrifice?', 'Hosea 6:6', 'For I desire mercy, and not sacrifice; and the knowledge of God more than burnt offerings.', 'WEB', 1,
   '{"type": "recall", "template": "For I desire ___, and not sacrifice; and the knowledge of God more than burnt offerings.", "answer": "mercy"}', true, 17),
  ((select id from w), 'recall', 'Fill in the missing word: where does the text say Yahweh called Israel, his son, out of?', 'Hosea 11:1', 'When Israel was a child, then I loved him, and called my son out of Egypt.', 'WEB', 1,
   '{"type": "recall", "template": "When Israel was a child, then I loved him, and called my son out of ___.", "answer": "Egypt"}', false, 18),
  ((select id from w), 'recall', 'Fill in the missing word: with what did Yahweh say he drew Ephraim, "with cords of a man"?', 'Hosea 11:3-4', 'Yet I taught Ephraim to walk. I took them by their arms, but they didn''t know that I healed them. I drew them with cords of a man, with ties of love; and I was to them like those who lift up the yoke on their necks; and I bent down to him and I fed him.', 'WEB', 2,
   '{"type": "recall", "template": "Yet I taught Ephraim to walk. I took them by their arms, but they didn''t know that I healed them. I drew them with cords of a man, with ties of ___; and I was to them like those who lift up the yoke on their necks; and I bent down to him and I fed him.", "answer": "love"}', false, 19),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say is "aroused" when he considers giving Ephraim up?', 'Hosea 11:8', 'How can I give you up, Ephraim? How can I hand you over, Israel? How can I make you like Admah? How can I make you like Zeboiim? My heart is turned within me, my compassion is aroused.', 'WEB', 1,
   '{"type": "recall", "template": "How can I give you up, Ephraim? How can I hand you over, Israel? How can I make you like Admah? How can I make you like Zeboiim? My heart is turned within me, my ___ is aroused.", "answer": "compassion"}', true, 20),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say he will not come in, toward Ephraim?', 'Hosea 11:9', 'I will not execute the fierceness of my anger. I will not return to destroy Ephraim, for I am God, and not man—the Holy One among you. I will not come in wrath.', 'WEB', 2,
   '{"type": "recall", "template": "I will not execute the fierceness of my anger. I will not return to destroy Ephraim, for I am God, and not man—the Holy One among you. I will not come in ___.", "answer": "wrath"}', false, 21),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say Israel has fallen because of?', 'Hosea 14:1-2', 'Israel, return to Yahweh your God; for you have fallen because of your sin. Take words with you, and return to Yahweh. Tell him, ''Forgive all our sins, and accept that which is good; so we offer bulls as we vowed of our lips.''', 'WEB', 2,
   '{"type": "recall", "template": "Israel, return to Yahweh your God; for you have fallen because of your ___. Take words with you, and return to Yahweh. Tell him, ''Forgive all our sins, and accept that which is good; so we offer bulls as we vowed of our lips.''", "answer": "sin"}', false, 22),
  ((select id from w), 'recall', 'Fill in the missing word: what does Israel promise it will no longer ride on?', 'Hosea 14:3', 'Assyria can''t save us. We won''t ride on horses; neither will we say any more to the work of our hands, ''Our gods!'' for in you the fatherless finds mercy.', 'WEB', 2,
   '{"type": "recall", "template": "Assyria can''t save us. We won''t ride on ___; neither will we say any more to the work of our hands, ''Our gods!'' for in you the fatherless finds mercy.", "answer": "horses"}', false, 23),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh promise to heal?', 'Hosea 14:4', 'I will heal their waywardness. I will love them freely; for my anger is turned away from them.', 'WEB', 1,
   '{"type": "recall", "template": "I will heal their ___. I will love them freely; for my anger is turned away from them.", "answer": "waywardness"}', false, 24),
  ((select id from w), 'multiple_choice', 'According to Hosea 14:9, what happens to the rebellious, in contrast to the righteous who walk in Yahweh''s ways?', 'Hosea 14:9', 'Who is wise, that he may understand these things? Who is prudent, that he may know them? For the ways of Yahweh are right, and the righteous walk in them, but the rebellious stumble in them.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["They stumble in the ways of Yahweh", "They are healed and restored immediately", "They are given a new heart", "They are cast out of Israel forever"], "correct_index": 0}', false, 25),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Hosea 2:16; 6:6; 11:8', 'The husband/master promise; I desire mercy, not sacrifice; How can I give you up, Ephraim?', 'WEB', 4,
   '{"type": "sequence", "items": ["\"...that you will call me ''my husband,'' and no longer call me ''my master.''\" — the betrothal promise (2:16)", "\"For I desire mercy, and not sacrifice; and the knowledge of God more than burnt offerings.\" — the call to return (6:6)", "\"How can I give you up, Ephraim?... My heart is turned within me, my compassion is aroused.\" — divine compassion (11:8)"], "correct_order": [0, 1, 2]}', false, 26),
  ((select id from w), 'sequence', 'Put these seven pivotal passages in the order they appear in the book of Hosea.', 'Hosea 1-3; 2:14-20; 3:1-5; 4:1-6; 6:1-6; 11:1-9; 14:1-9', 'Marriage commanded; wilderness betrothal; wife bought back; indictment; call to return; divine compassion; promise of healing', 'WEB', 3,
   '{"type": "sequence", "items": ["Hosea''s marriage commanded and the symbolic children", "The wilderness allurement and the betrothal promise", "Hosea buys back his wife", "The indictment: no knowledge of God in the land", "\"I desire mercy, not sacrifice\" — the call to return", "Divine compassion: \"How can I give you up, Ephraim?\"", "The promise of healing"], "correct_order": [0, 1, 2, 3, 4, 5, 6]}', true, 27)
;

with w as (select id from public.world where book_slug = 'joel')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: Joel asks whether this locust plague has ever happened in living memory, or in the days of whose?', 'Joel 1:2', 'Hear this, you elders, and listen, all you inhabitants of the land! Has this ever happened in your days, or in the days of your fathers?', 'WEB', 1,
   '{"type": "recall", "template": "Hear this, you elders, and listen, all you inhabitants of the land! Has this ever happened in your days, or in the days of your ___?", "answer": "fathers"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Joel 1:4, which four creatures are named in the locust plague''s successive waves?', 'Joel 1:4', 'What the swarming locust has left, the great locust has eaten. What the great locust has left, the grasshopper has eaten. What the grasshopper has left, the caterpillar has eaten.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The swarming locust, the great locust, the grasshopper, and the caterpillar", "Locusts, beetles, ants, and worms", "The swarming locust, the hornet, the moth, and the weevil", "Grasshoppers, crickets, cicadas, and locusts"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what does Joel tell the priests and elders to sanctify?', 'Joel 1:14', 'Sanctify a fast. Call a solemn assembly. Gather the elders and all the inhabitants of the land to the house of Yahweh, your God, and cry to Yahweh.', 'WEB', 1,
   '{"type": "recall", "template": "Sanctify a ___. Call a solemn assembly. Gather the elders and all the inhabitants of the land to the house of Yahweh, your God, and cry to Yahweh.", "answer": "fast"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: from whom does the text say the day of Yahweh will come as destruction?', 'Joel 1:15', 'Alas for the day! For the day of Yahweh is at hand, and it will come as destruction from the Almighty.', 'WEB', 1,
   '{"type": "recall", "template": "Alas for the day! For the day of Yahweh is at hand, and it will come as destruction from the ___.", "answer": "Almighty"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh call the people to turn to him with?', 'Joel 2:12', '''Yet even now,'' says Yahweh, ''turn to me with all your heart, and with fasting, and with weeping, and with mourning.''', 'WEB', 2,
   '{"type": "recall", "template": "''Yet even now,'' says Yahweh, ''turn to me with all your ___, and with fasting, and with weeping, and with mourning.''", "answer": "heart"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say Yahweh relents from sending?', 'Joel 2:13', 'Tear your heart and not your garments, and turn to Yahweh, your God; for he is gracious and merciful, slow to anger, and abundant in loving kindness, and relents from sending calamity.', 'WEB', 2,
   '{"type": "recall", "template": "Tear your heart and not your garments, and turn to Yahweh, your God; for he is gracious and merciful, slow to anger, and abundant in loving kindness, and relents from sending ___.", "answer": "calamity"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh promise to pour out on all flesh?', 'Joel 2:28', 'It will happen afterward, that I will pour out my Spirit on all flesh; and your sons and your daughters will prophesy. Your old men will dream dreams. Your young men will see visions.', 'WEB', 1,
   '{"type": "recall", "template": "It will happen afterward, that I will pour out my ___ on all flesh; and your sons and your daughters will prophesy. Your old men will dream dreams. Your young men will see visions.", "answer": "Spirit"}', true, 7),
  ((select id from w), 'multiple_choice', 'According to Joel 2:29, besides sons and daughters, old men, and young men, who else does Yahweh say he will pour out his Spirit on?', 'Joel 2:29', 'And also on the servants and on the handmaids in those days, I will pour out my Spirit.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["The servants and the handmaids", "The priests and the elders", "The kings and the princes", "The strangers and the foreigners"], "correct_index": 0}', false, 8),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Joel 1:15; 2:13; 2:28', 'The day of Yahweh at hand; the call to genuine repentance; the promise of the Spirit', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Alas for the day! For the day of Yahweh is at hand, and it will come as destruction from the Almighty.\" — the locust plague''s felt significance (1:15)", "\"Tear your heart and not your garments, and turn to Yahweh, your God...\" — the call to genuine repentance (2:13)", "\"I will pour out my Spirit on all flesh...\" — the promise of the Spirit (2:28)"], "correct_order": [0, 1, 2]}', false, 9),
  ((select id from w), 'sequence', 'Put these three pivotal passages in the order they occur in the book of Joel.', 'Joel 1:2-15; 2:12-13; 2:28-29', 'The locust plague and the call to lament; the call to return; the promise of the Spirit', 'WEB', 3,
   '{"type": "sequence", "items": ["The locust plague and the call to lament", "\"Turn to me with all your heart\" — the call to genuine repentance", "\"I will pour out my Spirit on all flesh\" — the promise of the Spirit"], "correct_order": [0, 1, 2]}', true, 10)
;

with w as (select id from public.world where book_slug = 'amos')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what region does the text say Damascus threshed with instruments of iron?', 'Amos 1:3', 'For three transgressions of Damascus, yes, for four, I will not turn away its punishment, because they have threshed Gilead with threshing instruments of iron.', 'WEB', 2,
   '{"type": "recall", "template": "For three transgressions of Damascus, yes, for four, I will not turn away its punishment, because they have threshed ___ with threshing instruments of iron.", "answer": "Gilead"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Amos 2:6, what did Israel do that the text names as its transgression?', 'Amos 2:6', 'For three transgressions of Israel, yes, for four, I will not turn away its punishment, because they have sold the righteous for silver, and the needy for a pair of sandals.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Sold the righteous for silver, and the needy for a pair of sandals", "Built houses of cut stone and planted vineyards", "Worshiped foreign gods in the temple", "Made false measures and unjust scales"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say is denied to the oppressed?', 'Amos 2:7', 'They trample the heads of the poor into the dust of the earth and deny justice to the oppressed.', 'WEB', 2,
   '{"type": "recall", "template": "They trample the heads of the poor into the dust of the earth and deny ___ to the oppressed.", "answer": "justice"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what crop does the text say unjust taxes were taken from the poor in?', 'Amos 5:11', 'Therefore, because you trample on the poor and take taxes from him of wheat, you have built houses of cut stone, but you will not dwell in them.', 'WEB', 2,
   '{"type": "recall", "template": "Therefore, because you trample on the poor and take taxes from him of ___, you have built houses of cut stone, but you will not dwell in them.", "answer": "wheat"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say the guilty take, alongside afflicting the just?', 'Amos 5:12', 'For I know how many are your offenses, and how great are your sins—you who afflict the just, who take a bribe, and who turn away the needy in the courts.', 'WEB', 2,
   '{"type": "recall", "template": "For I know how many are your offenses, and how great are your sins—you who afflict the just, who take a ___, and who turn away the needy in the courts.", "answer": "bribe"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: besides hating them, what does Yahweh say he does to Israel''s feasts?', 'Amos 5:21', 'I hate, I despise your feasts, and I can''t stand your solemn assemblies.', 'WEB', 1,
   '{"type": "recall", "template": "I hate, I ___ your feasts, and I can''t stand your solemn assemblies.", "answer": "despise"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what instrument''s music does Yahweh say he will not listen to?', 'Amos 5:23', 'Take away from me the noise of your songs! I will not listen to the music of your harps.', 'WEB', 1,
   '{"type": "recall", "template": "Take away from me the noise of your songs! I will not listen to the music of your ___.", "answer": "harps"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what does Amos say should roll on like rivers?', 'Amos 5:24', 'But let justice roll on like rivers, and righteousness like a mighty stream.', 'WEB', 1,
   '{"type": "recall", "template": "But let ___ roll on like rivers, and righteousness like a mighty stream.", "answer": "justice"}', true, 8),
  ((select id from w), 'multiple_choice', 'What was Amos''s occupation before Yahweh called him to prophesy?', 'Amos 7:14', 'I was no prophet, neither was I a prophet''s son, but I was a herdsman, and a farmer of sycamore figs.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A herdsman and a farmer of sycamore figs", "A priest at Bethel", "A royal scribe in Jerusalem", "A shepherd and a fisherman"], "correct_index": 0}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what was Amos following when Yahweh took him to prophesy?', 'Amos 7:15', 'and Yahweh took me from following the flock, and Yahweh said to me, ''Go, prophesy to my people Israel.''', 'WEB', 1,
   '{"type": "recall", "template": "and Yahweh took me from following the ___, and Yahweh said to me, ''Go, prophesy to my people Israel.''", "answer": "flock"}', false, 10),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Amos 2:6; 5:24; 7:14', 'The oracle turns on Israel; let justice roll on like rivers; Amos''s own call', 'WEB', 4,
   '{"type": "sequence", "items": ["\"...they have sold the righteous for silver, and the needy for a pair of sandals.\" — the oracle turns onto Israel itself (2:6)", "\"But let justice roll on like rivers, and righteousness like a mighty stream.\" — the book''s best-known line (5:24)", "\"I was no prophet, neither was I a prophet''s son, but I was a herdsman...\" — Amos''s own call (7:14)"], "correct_order": [0, 1, 2]}', false, 11),
  ((select id from w), 'sequence', 'Put these four pivotal passages in the order they appear in the book of Amos.', 'Amos 1-2; 5:11-12; 5:21-24; 7:14-15', 'The judgment oracles against the nations and Israel; economic injustice named directly; let justice roll on like rivers; Amos''s own call', 'WEB', 3,
   '{"type": "sequence", "items": ["The judgment oracles against the nations — and Israel itself", "Economic injustice named directly", "\"Let justice roll on like rivers\"", "Amos''s own call — \"I was no prophet\""], "correct_order": [0, 1, 2, 3]}', true, 12)
;

with w as (select id from public.world where book_slug = 'obadiah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say has deceived Edom?', 'Obadiah 1:3', 'The pride of your heart has deceived you, you who dwell in the clefts of the rock, whose habitation is high, who says in his heart, ''Who will bring me down to the ground?''', 'WEB', 1,
   '{"type": "recall", "template": "The ___ of your heart has deceived you, you who dwell in the clefts of the rock, whose habitation is high, who says in his heart, ''Who will bring me down to the ground?''", "answer": "pride"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: where does the text say Edom''s nest is set, in its pride?', 'Obadiah 1:4', '"Though you mount on high as the eagle, and though your nest is set among the stars, I will bring you down from there," says Yahweh.', 'WEB', 2,
   '{"type": "recall", "template": "\"Though you mount on high as the eagle, and though your nest is set among the ___, I will bring you down from there,\" says Yahweh.", "answer": "stars"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: whose violence does the text say will bring shame on Edom?', 'Obadiah 1:10', 'For the violence done to your brother Jacob, shame will cover you, and you will be cut off forever.', 'WEB', 1,
   '{"type": "recall", "template": "For the violence done to your brother ___, shame will cover you, and you will be cut off forever.", "answer": "Jacob"}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Obadiah 1:12, what does the text say Edom should not have done regarding Judah''s disaster?', 'Obadiah 1:12', 'But don''t look down on your brother in the day of his disaster, and don''t rejoice over the children of Judah in the day of their destruction.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Looked down on their brother, or rejoiced over Judah''s destruction", "Entered Jerusalem''s gates and cast lots for the city", "Sent an army to help Judah", "Refused to shelter Judah''s refugees"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: the day of Yahweh is near all the what?', 'Obadiah 1:15', 'For the day of Yahweh is near all the nations! As you have done, it will be done to you. Your deeds will return upon your own head.', 'WEB', 1,
   '{"type": "recall", "template": "For the day of Yahweh is near all the ___! As you have done, it will be done to you. Your deeds will return upon your own head.", "answer": "nations"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say those on Mount Zion will do?', 'Obadiah 1:17', 'But in Mount Zion, there will be those who escape, and it will be holy. The house of Jacob will possess their possessions.', 'WEB', 1,
   '{"type": "recall", "template": "But in Mount Zion, there will be those who ___, and it will be holy. The house of Jacob will possess their possessions.", "answer": "escape"}', false, 6),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Obadiah 1:4; 1:10; 1:15', 'Edom''s pride; Edom''s offense against Judah; the day of Yahweh', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Though you mount on high as the eagle... I will bring you down from there,\" says Yahweh. — Edom''s pride condemned (1:4)", "\"For the violence done to your brother Jacob, shame will cover you...\" — Edom''s offense against Judah (1:10)", "\"For the day of Yahweh is near all the nations!...\" — the day of Yahweh and deliverance on Mount Zion (1:15)"], "correct_order": [0, 1, 2]}', false, 7),
  ((select id from w), 'sequence', 'Put these three pivotal passages in the order they occur in the book of Obadiah.', 'Obadiah 1:3-4; 1:10-12; 1:15-17', 'Edom''s pride condemned; Edom''s offense against Judah; the day of Yahweh and deliverance on Mount Zion', 'WEB', 2,
   '{"type": "sequence", "items": ["Edom''s pride condemned", "Edom''s offense against Judah", "The day of Yahweh and deliverance on Mount Zion"], "correct_order": [0, 1, 2]}', true, 8)
;
