-- Gen2Rev challenge ingest: Isaiah (World 23)
-- Generated from docs/content/isaiah.md
-- Theological review: approved-with-changes (docs/CONTENT_REVIEW_LOG.md row 23, docs/reviews/isaiah-review.md)
-- Verbatim QA: pass (docs/QA_SIGNOFF.md) -- 7:14/9:6-7/53 exclusion confirmed absent via grep
-- Medium tier only (difficulty_tier column left to its default), per docs/CANON_STRUCTURE.md §6 phasing

with w as (select id from public.world where book_slug = 'isaiah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say confessed sin will become, though it is as scarlet?', 'Isaiah 1:18', '''Come now, and let''s reason together,'' says Yahweh: ''Though your sins are as scarlet, they shall be as white as snow. Though they are red like crimson, they shall be as wool.''', 'WEB', 1,
   '{"type": "recall", "template": "''Come now, and let''s reason together,'' says Yahweh: ''Though your sins are as scarlet, they shall be as ___ as snow. Though they are red like crimson, they shall be as wool.''", "answer": "white"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from Yahweh''s call to repentance.', 'Isaiah 1:16-17', '''Wash yourselves. Make yourself clean. Put away the evil of your doings from before my eyes. Cease to do evil. Learn to do well. Seek justice. Relieve the oppressed. Defend the fatherless. Plead for the widow.''', 'WEB', 2,
   '{"type": "recall", "template": "''Wash yourselves. Make yourself clean. Put away the evil of your doings from before my eyes. Cease to do evil. Learn to do well. Seek justice. Relieve the oppressed. Defend the ___. Plead for the widow.''", "answer": "fatherless"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what will the nations beat their swords into, per this vision?', 'Isaiah 2:4', '''He will judge between the nations, and will decide concerning many peoples. They shall beat their swords into plowshares, and their spears into pruning hooks. Nation shall not lift up sword against nation, neither shall they learn war any more.''', 'WEB', 1,
   '{"type": "recall", "template": "''He will judge between the nations, and will decide concerning many peoples. They shall beat their swords into ___, and their spears into pruning hooks. Nation shall not lift up sword against nation, neither shall they learn war any more.''", "answer": "plowshares"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what did Isaiah see, high and lifted up, in the year King Uzziah died?', 'Isaiah 6:1', '''In the year that King Uzziah died, I saw the Lord sitting on a throne, high and lifted up; and his train filled the temple.''', 'WEB', 1,
   '{"type": "recall", "template": "''In the year that King Uzziah died, I saw the Lord sitting on a ___, high and lifted up; and his train filled the temple.''", "answer": "throne"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Isaiah 6:6-7, what did the seraph touch to Isaiah''s lips?', 'Isaiah 6:6-7', '''Then one of the seraphim flew to me, having a live coal in his hand, which he had taken with the tongs from off the altar. He touched my mouth with it, and said, "Behold, this has touched your lips; and your iniquity is taken away, and your sin forgiven."''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A live coal from the altar", "A scroll from the temple", "A cup of water", "A branch of hyssop"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing words: Isaiah''s response when Yahweh asked whom he should send.', 'Isaiah 6:8', '''I heard the Lord''s voice, saying, "Whom shall I send, and who will go for us?" Then I said, "Here I am. Send me!"''', 'WEB', 1,
   '{"type": "recall", "template": "''I heard the Lord''s voice, saying, \"Whom shall I send, and who will go for us?\" Then I said, \"___ I am. Send me!\"''", "answer": "Here"}', false, 6),
  ((select id from w), 'sequence', 'Put these moments of Isaiah''s call vision in the order they happen in the text.', 'Isaiah 6:1-8', 'In the year that King Uzziah died, I saw the Lord sitting on a throne, high and lifted up; and his train filled the temple.; One called to another, and said, ''Holy, holy, holy, is Yahweh of Armies! The whole earth is full of his glory!''; Then I said, ''Woe is me! For I am undone, because I am a man of unclean lips and I live among a people of unclean lips, for my eyes have seen the King, Yahweh of Armies!''; He touched my mouth with it, and said, ''Behold, this has touched your lips; and your iniquity is taken away, and your sin forgiven.''; I heard the Lord''s voice, saying, ''Whom shall I send, and who will go for us?'' Then I said, ''Here I am. Send me!''', 'WEB', 3,
   '{"type": "sequence", "items": ["Isaiah sees the Lord high and lifted up on a throne, his train filling the temple", "The seraphim call to one another, \"Holy, holy, holy, is Yahweh of Armies!\"", "Isaiah cries out, \"Woe is me!... I am a man of unclean lips\"", "A seraph touches a live coal to his lips and says his iniquity is taken away", "Isaiah answers Yahweh''s call: \"Here I am. Send me!\""], "correct_order": [0, 1, 2, 3, 4]}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say Yahweh has become, in this thanksgiving hymn?', 'Isaiah 12:2', '''Behold, God is my salvation. I will trust, and will not be afraid; for Yah, Yahweh, is my strength and song; and he has become my salvation.''', 'WEB', 1,
   '{"type": "recall", "template": "''Behold, God is my salvation. I will trust, and will not be afraid; for Yah, Yahweh, is my strength and song; and he has become my ___.''", "answer": "salvation"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what will the inhabitant of Zion do, per this hymn''s closing line?', 'Isaiah 12:6', '''Cry aloud and shout, you inhabitant of Zion, for the Holy One of Israel is great among you!''', 'WEB', 1,
   '{"type": "recall", "template": "''Cry aloud and shout, you inhabitant of Zion, for the Holy One of Israel is great among ___!''", "answer": "you"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Isaiah 38:5, how many years did Yahweh add to Hezekiah''s life?', 'Isaiah 38:5', '''Go, and tell Hezekiah, "Yahweh, the God of David your father, says, \''I have heard your prayer. I have seen your tears. Behold, I will add fifteen years to your life.\''"''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Fifteen years", "Ten years", "Twenty years", "Seven years"], "correct_index": 0}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did Hezekiah do after turning his face to the wall to pray?', 'Isaiah 38:2-3', '''Then Hezekiah turned his face to the wall and prayed to Yahweh, and said, "Remember now, Yahweh, I beg you, how I have walked before you in truth and with a perfect heart, and have done that which is good in your sight." Then Hezekiah wept bitterly.''', 'WEB', 2,
   '{"type": "recall", "template": "''Then Hezekiah turned his face to the wall and prayed to Yahweh, and said, \"Remember now, Yahweh, I beg you, how I have walked before you in truth and with a perfect heart, and have done that which is good in your sight.\" Then Hezekiah wept ___.''", "answer": "bitterly"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what will those who wait for Yahweh mount up with, per this passage?', 'Isaiah 40:31', '''but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.''', 'WEB', 1,
   '{"type": "recall", "template": "''but those who wait for Yahweh will renew their strength. They will mount up with wings like ___. They will run, and not be weary. They will walk, and not faint.''", "answer": "eagles"}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: what does the text say the Creator of the ends of the earth does not do?', 'Isaiah 40:28', '''Haven''t you known? Haven''t you heard? The everlasting God, Yahweh, the Creator of the ends of the earth, doesn''t faint. He isn''t weary. His understanding is unsearchable.''', 'WEB', 2,
   '{"type": "recall", "template": "''Haven''t you known? Haven''t you heard? The everlasting God, Yahweh, the Creator of the ends of the earth, doesn''t faint. He isn''t ___. His understanding is unsearchable.''", "answer": "weary"}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say he will uphold you with?', 'Isaiah 41:10', '''Don''t you be afraid, for I am with you. Don''t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.''', 'WEB', 2,
   '{"type": "recall", "template": "''Don''t you be afraid, for I am with you. Don''t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my ___.''", "answer": "righteousness"}', false, 14),
  ((select id from w), 'multiple_choice', 'According to Isaiah 55:8, whose thoughts and ways does the text say are not like Yahweh''s?', 'Isaiah 55:8', '''For my thoughts are not your thoughts, and your ways are not my ways," says Yahweh.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Yours", "The nations''", "The wicked man''s alone", "The prophets''"], "correct_index": 0}', false, 15),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur across the book of Isaiah.', 'Isaiah 6:8; 40:31; 55:8', 'I heard the Lord''s voice, saying, ''Whom shall I send, and who will go for us?'' Then I said, ''Here I am. Send me!''; but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.; For my thoughts are not your thoughts, and your ways are not my ways, says Yahweh.', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Here I am. Send me!\" -- Isaiah''s response to Yahweh''s call (Isaiah 6:8)", "\"They will mount up with wings like eagles.\" -- the promise to those who wait for Yahweh (Isaiah 40:31)", "\"My thoughts are not your thoughts, and your ways are not my ways.\" -- Yahweh''s closing word on his transcendence (Isaiah 55:8)"], "correct_order": [0, 1, 2]}', true, 16)
;
