-- Gen2Rev challenge ingest: Jeremiah (World 24) and Lamentations (World 25)
-- Generated from docs/content/jeremiah.md and docs/content/lamentations.md
-- Both books: theological review approved-with-changes, verbatim QA pass (docs/CONTENT_REVIEW_LOG.md rows 24-25, docs/QA_SIGNOFF.md)
-- Medium tier only, per both briefs' phasing note.
-- World rows already exist live (book_slug 'jeremiah' / 'lamentations').

with w as (select id from public.world where book_slug = 'jeremiah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh tell Jeremiah he did before Jeremiah was even born?', 'Jeremiah 1:5', 'Before I formed you in the womb, I knew you. Before you were born, I sanctified you. I have appointed you a prophet to the nations.', 'WEB', 1,
   '{"type": "recall", "template": "Before I formed you in the womb, I ___ you. Before you were born, I sanctified you. I have appointed you a prophet to the nations.", "answer": "knew"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what excuse did Jeremiah give Yahweh for why he could not speak?', 'Jeremiah 1:6-7', 'Then I said, ''Ah, Lord Yahweh! Behold, I don''t know how to speak; for I am a child.'' But Yahweh said to me, ''Don''t say, "I am a child;" for you must go to whomever I send you, and you must say whatever I command you.''', 'WEB', 1,
   '{"type": "recall", "template": "Then I said, ''Ah, Lord Yahweh! Behold, I don''t know how to speak; for I am a ___.'' But Yahweh said to me, ''Don''t say, \"I am a child;\" for you must go to whomever I send you, and you must say whatever I command you.''", "answer": "child"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing words: the four pairs of Jeremiah''s mission, first two given.', 'Jeremiah 1:9-10', 'Then Yahweh stretched out his hand and touched my mouth. Then Yahweh said to me, ''Behold, I have put my words in your mouth. Behold, I have today set you over the nations and over the kingdoms, to uproot and to tear down, to destroy and to overthrow, to build and to plant.''', 'WEB', 2,
   '{"type": "recall", "template": "Then Yahweh stretched out his hand and touched my mouth. Then Yahweh said to me, ''Behold, I have put my words in your mouth. Behold, I have today set you over the nations and over the kingdoms, to ___ and to tear down, to destroy and to overthrow, to build and to plant.''", "answer": "uproot"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh promise Jeremiah he would do, despite the fight against him?', 'Jeremiah 1:19', '''They will fight against you, but they will not prevail against you; for I am with you,'' says Yahweh, ''to rescue you.''', 'WEB', 1,
   '{"type": "recall", "template": "''They will fight against you, but they will not prevail against you; for I am with you,'' says Yahweh, ''to ___ you.''", "answer": "rescue"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: the phrase Jeremiah says the people repeat three times as a lying trust.', 'Jeremiah 7:3-4', '''Amend your ways and your doings, and I will cause you to dwell in this place. Don''t trust in lying words, saying, "Yahweh''s temple, Yahweh''s temple, Yahweh''s temple, are these."''', 'WEB', 2,
   '{"type": "recall", "template": "''Amend your ways and your doings, and I will cause you to dwell in this place. Don''t trust in lying words, saying, \"Yahweh''s ___, Yahweh''s temple, Yahweh''s temple, are these.\"''", "answer": "temple"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Jeremiah 7:11, what does Yahweh call the temple, given how the people are treating it?', 'Jeremiah 7:9-11', '''Will you steal, murder, commit adultery, swear falsely, burn incense to Baal, and walk after other gods that you have not known, then come and stand before me in this house, which is called by my name... Has this house, which is called by my name, become a den of robbers in your eyes? Behold, I myself have seen it,'' says Yahweh.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A den of robbers", "A house of prayer", "A place of refuge", "A tower of strength"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: the place Yahweh tells Jeremiah to go and see what he did to it.', 'Jeremiah 7:12', '''But go now to my place which was in Shiloh, where I caused my name to dwell at the first, and see what I did to it for the wickedness of my people Israel.''', 'WEB', 2,
   '{"type": "recall", "template": "''But go now to my place which was in ___, where I caused my name to dwell at the first, and see what I did to it for the wickedness of my people Israel.''", "answer": "Shiloh"}', false, 7),
  ((select id from w), 'multiple_choice', 'What did Jeremiah watch the potter do when the vessel he was making was marred?', 'Jeremiah 18:2-4', '''Arise, and go down to the potter''s house, and there I will cause you to hear my words.'' Then I went down to the potter''s house, and behold, he was making something on the wheels. When the vessel that he made of the clay was marred in the hand of the potter, he made it again another vessel, as seemed good to the potter to make it.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["He reshaped it into another vessel", "He threw it away and started with new clay", "He fired it in the kiln anyway", "He gave it to an apprentice to fix"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh compare the house of Israel to, in his hand?', 'Jeremiah 18:6', '''House of Israel, can''t I do with you as this potter?'' says Yahweh. ''Behold, as the clay in the potter''s hand, so are you in my hand, house of Israel.''', 'WEB', 1,
   '{"type": "recall", "template": "''House of Israel, can''t I do with you as this potter?'' says Yahweh. ''Behold, as the ___ in the potter''s hand, so are you in my hand, house of Israel.''", "answer": "clay"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: per Jeremiah 28:9, what confirms that a prophet who proclaims peace was truly sent by Yahweh?', 'Jeremiah 28:9', '''As for the prophet who prophesies of peace, when the word of the prophet happens, then the prophet will be known, that Yahweh has truly sent him.''', 'WEB', 3,
   '{"type": "recall", "template": "''As for the prophet who prophesies of peace, when the word of the prophet happens, then the prophet will be known, that Yahweh has truly ___ him.''", "answer": "sent"}', true, 10),
  ((select id from w), 'multiple_choice', 'What did Hananiah do to Jeremiah as a dramatic sign after his prophecy?', 'Jeremiah 28:10-11', 'Then Hananiah the prophet took the bar from off the prophet Jeremiah''s neck, and broke it. Hananiah spoke in the presence of all the people, saying, ''Yahweh says: "Even so I will break the yoke of Nebuchadnezzar king of Babylon from off the neck of all the nations within two full years."''', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["He broke the bar (yoke) off Jeremiah''s neck", "He tore Jeremiah''s robe", "He poured oil on Jeremiah''s head", "He threw the yoke into the temple courtyard fire"], "correct_index": 0}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what Jeremiah told Hananiah he would do, this same year, per Yahweh''s word.', 'Jeremiah 28:15-17', 'Then the prophet Jeremiah said to Hananiah the prophet, ''Listen, Hananiah! Yahweh has not sent you, but you make this people trust in a lie. Therefore Yahweh says, "Behold, I will send you away from off the surface of the earth. This year you will die..."'' So Hananiah the prophet died the same year in the seventh month.', 'WEB', 3,
   '{"type": "recall", "template": "Then the prophet Jeremiah said to Hananiah the prophet, ''Listen, Hananiah! Yahweh has not sent you, but you make this people trust in a lie. Therefore Yahweh says, \"Behold, I will send you away from off the surface of the earth. This year you will ___...\"'' So Hananiah the prophet died the same year in the seventh month.", "answer": "die"}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: what Ebedmelech told the king was likely to happen to Jeremiah in the dungeon.', 'Jeremiah 38:9', '''My lord the king, these men have done evil in all that they have done to Jeremiah the prophet, whom they have cast into the dungeon. He is likely to die in the place where he is, because of the famine; for there is no more bread in the city.''', 'WEB', 2,
   '{"type": "recall", "template": "''My lord the king, these men have done evil in all that they have done to Jeremiah the prophet, whom they have cast into the dungeon. He is likely to ___ in the place where he is, because of the famine; for there is no more bread in the city.''", "answer": "die"}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: how many men the king commanded Ebedmelech to take to rescue Jeremiah.', 'Jeremiah 38:10', 'Then the king commanded Ebedmelech the Ethiopian, saying, ''Take from here thirty men with you, and take up Jeremiah the prophet out of the dungeon, before he dies.''', 'WEB', 2,
   '{"type": "recall", "template": "Then the king commanded Ebedmelech the Ethiopian, saying, ''Take from here ___ men with you, and take up Jeremiah the prophet out of the dungeon, before he dies.''", "answer": "thirty"}', false, 14),
  ((select id from w), 'multiple_choice', 'According to Jeremiah 39:1-2, in what month of Zedekiah''s eleventh year was the breach made in the city wall?', 'Jeremiah 39:1-2', 'In the ninth year of Zedekiah king of Judah, in the tenth month, Nebuchadnezzar king of Babylon and all his army came against Jerusalem, and besieged it. In the eleventh year of Zedekiah, in the fourth month, the ninth day of the month, a breach was made in the city.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["The fourth month, the ninth day", "The tenth month, the first day", "The seventh month, the tenth day", "The first month, the fourteenth day"], "correct_index": 0}', false, 15),
  ((select id from w), 'recall', 'Fill in the missing word: what Nebuchadnezzar commanded Nebuzaradan to do for Jeremiah.', 'Jeremiah 39:11-12', '''Now Nebuchadnezzar king of Babylon commanded Nebuzaradan the captain of the guard concerning Jeremiah, saying, "Take him and take care of him. Do him no harm; but do to him even as he tells you."''', 'WEB', 2,
   '{"type": "recall", "template": "''Now Nebuchadnezzar king of Babylon commanded Nebuzaradan the captain of the guard concerning Jeremiah, saying, \"Take him and take care of him. Do him no ___; but do to him even as he tells you.\"''", "answer": "harm"}', false, 16),
  ((select id from w), 'recall', 'Fill in the missing word: why Ebedmelech would escape with his life, per Yahweh''s promise.', 'Jeremiah 39:17-18', '''But I will deliver you in that day,'' says Yahweh; ''and you will not be given into the hand of the men of whom you are afraid. For I will surely save you. You won''t fall by the sword, but you will escape with your life, because you have put your trust in me,'' says Yahweh.', 'WEB', 3,
   '{"type": "recall", "template": "''But I will deliver you in that day,'' says Yahweh; ''and you will not be given into the hand of the men of whom you are afraid. For I will surely save you. You won''t fall by the sword, but you will escape with your life, because you have put your ___ in me,'' says Yahweh.", "answer": "trust"}', false, 17),
  ((select id from w), 'recall', 'Fill in the missing word: the two houses Yahweh promises to make a new covenant with.', 'Jeremiah 31:31', '''Behold, the days come,'' says Yahweh, ''that I will make a new covenant with the house of Israel, and with the house of Judah.''', 'WEB', 1,
   '{"type": "recall", "template": "''Behold, the days come,'' says Yahweh, ''that I will make a new ___ with the house of Israel, and with the house of Judah.''", "answer": "covenant"}', false, 18),
  ((select id from w), 'recall', 'Fill in the missing word: where Yahweh says he will write his law, under the new covenant.', 'Jeremiah 31:33', '''But this is the covenant that I will make with the house of Israel after those days,'' says Yahweh: ''I will put my law in their inward parts, and I will write it in their heart. I will be their God, and they shall be my people.''', 'WEB', 2,
   '{"type": "recall", "template": "''But this is the covenant that I will make with the house of Israel after those days,'' says Yahweh: ''I will put my law in their inward parts, and I will write it in their ___. I will be their God, and they shall be my people.''", "answer": "heart"}', false, 19),
  ((select id from w), 'sequence', 'Put these seven scenes in the order they occur in the book of Jeremiah.', 'Jeremiah 1; 7; 18; 28; 37-38; 39; 31', 'Jeremiah 1; Jeremiah 7; Jeremiah 18; Jeremiah 28; Jeremiah 37-38; Jeremiah 39; Jeremiah 31', 'WEB', 4,
   '{"type": "sequence", "items": ["Yahweh calls Jeremiah as a young man and appoints him a prophet to the nations", "Jeremiah stands at the temple gate and confronts the people for trusting in the temple''s mere presence", "Jeremiah watches a potter reshape a marred vessel and hears Yahweh compare Israel to the clay", "Hananiah breaks a yoke off Jeremiah''s neck and falsely prophesies; Jeremiah tells him he will die within the year", "Jeremiah is imprisoned in a dungeon and rescued by Ebedmelech and thirty men", "Nebuchadnezzar''s army breaches Jerusalem''s wall and orders Jeremiah protected and cared for", "Yahweh promises a new covenant written on the heart, for the house of Israel and the house of Judah"], "correct_order": [0, 1, 2, 3, 4, 5, 6]}', true, 20),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text, matching each to its scene.', 'Jeremiah 1:9-10; 18:6; 28:9', 'Then Yahweh stretched out his hand and touched my mouth... to uproot and to tear down, to destroy and to overthrow, to build and to plant.; House of Israel, can''t I do with you as this potter? Behold, as the clay in the potter''s hand, so are you in my hand, house of Israel.; As for the prophet who prophesies of peace, when the word of the prophet happens, then the prophet will be known, that Yahweh has truly sent him.', 'WEB', 4,
   '{"type": "sequence", "items": ["\"I have today set you over the nations and over the kingdoms, to uproot and to tear down...\" — Jeremiah''s call (Jeremiah 1:9-10)", "\"As the clay in the potter''s hand, so are you in my hand, house of Israel.\" — the potter''s house (Jeremiah 18:6)", "\"When the word of the prophet happens, then the prophet will be known, that Yahweh has truly sent him.\" — the test applied to Hananiah (Jeremiah 28:9)"], "correct_order": [0, 1, 2]}', false, 21),
  ((select id from w), 'multiple_choice', 'According to Jeremiah 28:9, when is a prophet who proclaims peace confirmed to have truly been sent by Yahweh?', 'Jeremiah 28:9', '''As for the prophet who prophesies of peace, when the word of the prophet happens, then the prophet will be known, that Yahweh has truly sent him.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["When the word he spoke comes to pass", "When the king agrees with him", "When another prophet confirms it", "When the temple priests approve it"], "correct_index": 0}', true, 22)
;

with w as (select id from public.world where book_slug = 'lamentations')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what the city has become, having once been a princess among the provinces.', 'Lamentations 1:1', 'How the city sits solitary, that was full of people! She has become as a widow, who was great among the nations! She who was a princess among the provinces has become a slave!', 'WEB', 1,
   '{"type": "recall", "template": "How the city sits solitary, that was full of people! She has become as a widow, who was great among the nations! She who was a princess among the provinces has become a ___!", "answer": "slave"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Lamentations 1:1, what is the city compared to, having once been great among the nations?', 'Lamentations 1:1', 'How the city sits solitary, that was full of people! She has become as a widow, who was great among the nations! She who was a princess among the provinces has become a slave!', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A widow", "A beggar", "An orphan", "A prisoner"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: who the city says has dealt treacherously with her and become her enemies.', 'Lamentations 1:2', 'She weeps bitterly in the night. Her tears are on her cheeks. Among all her lovers she has no one to comfort her. All her friends have dealt treacherously with her. They have become her enemies.', 'WEB', 2,
   '{"type": "recall", "template": "She weeps bitterly in the night. Her tears are on her cheeks. Among all her lovers she has no one to comfort her. All her ___ have dealt treacherously with her. They have become her enemies.", "answer": "friends"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what the city asks any passerby to look and see, comparing it to her own.', 'Lamentations 1:12', '''Is it nothing to you, all you who pass by? Look, and see if there is any sorrow like my sorrow, which is brought on me, with which Yahweh has afflicted me in the day of his fierce anger.''', 'WEB', 1,
   '{"type": "recall", "template": "''Is it nothing to you, all you who pass by? Look, and see if there is any sorrow like my sorrow, which is brought on me, with which Yahweh has afflicted me in the day of his fierce ___.''", "answer": "anger"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what the speaker says has perished, along with his expectation from Yahweh.', 'Lamentations 3:18', 'I said, ''My strength has perished, along with my expectation from Yahweh.''', 'WEB', 1,
   '{"type": "recall", "template": "I said, ''My ___ has perished, along with my expectation from Yahweh.''", "answer": "strength"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Lamentations 3:18-21, what does the speaker say happened just before turning to hope?', 'Lamentations 3:18-20', 'I said, ''My strength has perished, along with my expectation from Yahweh.'' Remember my affliction and my misery, the wormwood and the bitterness. My soul still remembers them, and is bowed down within me.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["His strength and his expectation from Yahweh had perished", "He was rescued from the dungeon", "The city walls were rebuilt", "He received a new prophecy"], "correct_index": 0}', true, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what the text says is new every morning, because of Yahweh''s loving kindnesses.', 'Lamentations 3:21-23', 'This I recall to my mind; therefore I have hope. It is because of Yahweh''s loving kindnesses that we are not consumed, because his mercies don''t fail. They are new every morning. Great is your faithfulness.', 'WEB', 1,
   '{"type": "recall", "template": "This I recall to my mind; therefore I have hope. It is because of Yahweh''s loving kindnesses that we are not consumed, because his mercies don''t fail. They are new every ___. Great is your faithfulness.", "answer": "morning"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what the speaker''s soul says it will do in Yahweh, its portion.', 'Lamentations 3:24', '''Yahweh is my portion,'' says my soul. ''Therefore I will hope in him.''', 'WEB', 1,
   '{"type": "recall", "template": "''Yahweh is my portion,'' says my soul. ''Therefore I will ___ in him.''", "answer": "hope"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what the closing prayer says Yahweh''s throne is, from generation to generation.', 'Lamentations 5:19', 'You, Yahweh, remain forever. Your throne is from generation to generation.', 'WEB', 1,
   '{"type": "recall", "template": "You, Yahweh, remain forever. Your ___ is from generation to generation.", "answer": "throne"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what the closing plea asks Yahweh to do to the people''s days, as of old.', 'Lamentations 5:21', 'Turn us to yourself, Yahweh, and we will be turned. Renew our days as of old.', 'WEB', 2,
   '{"type": "recall", "template": "Turn us to yourself, Yahweh, and we will be turned. ___ our days as of old.", "answer": "Renew"}', false, 10),
  ((select id from w), 'sequence', 'Put these three pivotal passages in the order they appear in the book of Lamentations.', 'Lamentations 1:1-12; 3:18-24; 5:19-21', 'Lamentations 1:1-12; Lamentations 3:18-24; Lamentations 5:19-21', 'WEB', 3,
   '{"type": "sequence", "items": ["The opening lament: the city pictured as a widow, once great, now alone", "The turn to hope at the book''s darkest point: strength and hope had perished, then Yahweh''s mercies are new every morning", "The book''s closing plea: Yahweh remains forever, so renew our days as of old"], "correct_order": [0, 1, 2]}', true, 11),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the book, matching each to its passage.', 'Lamentations 1:12; 3:22-23; 5:21', '''Is it nothing to you, all you who pass by? Look, and see if there is any sorrow like my sorrow...''; ''His mercies don''t fail. They are new every morning. Great is your faithfulness.''; ''Turn us to yourself, Yahweh, and we will be turned. Renew our days as of old.''', 'WEB', 4,
   '{"type": "sequence", "items": ["\"Look, and see if there is any sorrow like my sorrow...\" — the opening lament (Lamentations 1:12)", "\"His mercies... are new every morning. Great is your faithfulness.\" — the turn to hope (Lamentations 3:22-23)", "\"Turn us to yourself, Yahweh, and we will be turned. Renew our days as of old.\" — the closing plea (Lamentations 5:21)"], "correct_order": [0, 1, 2]}', false, 12)
;
