-- Gen2Rev challenge ingest: Job (World 18) and Psalms (World 19)
-- Generated from docs/content/job.md and docs/content/psalms.md
-- Both books: theological review pass, verbatim QA pass (docs/CONTENT_REVIEW_LOG.md rows 18-19, docs/QA_SIGNOFF.md)
-- Job and Leviticus precedent: pivotal-passage adaptation for non-narrative material (see docs/CANON_STRUCTURE.md §6)

with w as (select id from public.world where book_slug = 'job')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Job turn away from, according to the opening description of his character?', 'Job 1:1-3', 'There was a man in the land of Uz, whose name was Job. That man was blameless and upright, and one who feared God, and turned away from evil. There were born to him seven sons and three daughters. His possessions also were seven thousand sheep, three thousand camels, five hundred yoke of oxen, five hundred female donkeys, and a very great household; so that this man was the greatest of all the children of the east.', 'WEB', 1,
   '{"type": "recall", "template": "There was a man in the land of Uz, whose name was Job. That man was blameless and upright, and one who feared God, and turned away from ___. There were born to him seven sons and three daughters. His possessions also were seven thousand sheep, three thousand camels, five hundred yoke of oxen, five hundred female donkeys, and a very great household; so that this man was the greatest of all the children of the east.", "answer": "evil"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what limit did Yahweh place on Satan''s test of Job?', 'Job 1:12', 'Yahweh said to Satan, ''Behold, all that he has is in your power. Only on himself don''t stretch out your hand.'' So Satan went out from the presence of Yahweh.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh said to Satan, ''Behold, all that he has is in your power. Only on himself don''t stretch out your ___.'' So Satan went out from the presence of Yahweh.", "answer": "hand"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: Job''s declaration after losing everything in a single day.', 'Job 1:20-21', 'Then Job arose, and tore his robe, and shaved his head, and fell down on the ground, and worshiped. He said, ''Naked I came out of my mother''s womb, and naked will I return there. Yahweh gave, and Yahweh has taken away. Blessed be Yahweh''s name.''', 'WEB', 1,
   '{"type": "recall", "template": "Then Job arose, and tore his robe, and shaved his head, and fell down on the ground, and worshiped. He said, ''Naked I came out of my mother''s womb, and naked will I return there. Yahweh gave, and Yahweh has ___ away. Blessed be Yahweh''s name.''", "answer": "taken"}', true, 3),
  ((select id from w), 'multiple_choice', 'What did Job''s wife suggest he do?', 'Job 2:9-10', 'Then his wife said to him, ''Do you still maintain your integrity? Renounce God, and die.'' But he said to her, ''You speak as one of the foolish women would speak. What? Shall we receive good at the hand of God, and shall we not receive evil?'' In all this Job didn''t sin with his lips.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Renounce God, and die", "Leave Uz and start over", "Curse his three friends", "Offer a sacrifice for his own sins"], "correct_index": 0}', false, 4),
  ((select id from w), 'sequence', 'Put these narrative beats of Job''s story in the order they occur in the book.', 'Job 1:1-3; 1:13-22, 2:7-10; 38-41; 42:1-8, 42:10-17', 'Job 1:1-3; Job 1:13-22, 2:7-10; Job 38-41; Job 42:1-8, 42:10-17', 'WEB', 3,
   '{"type": "sequence", "items": ["Job is introduced as blameless, upright, and the wealthiest man in the region", "Job loses his livestock, servants, and all ten children in a single day, then tears his robe and worships", "Job is struck with painful sores but refuses to curse God, despite his wife''s urging", "Yahweh answers Job out of the whirlwind, then rebukes Job''s three friends and restores Job''s fortunes twofold"], "correct_order": [0, 1, 2, 3]}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: how Job describes his response after Yahweh''s speeches from the whirlwind.', 'Job 42:5-6', '''I had heard of you by the hearing of the ear, but now my eye sees you. Therefore I abhor myself, and repent in dust and ashes.''', 'WEB', 3,
   '{"type": "recall", "template": "''I had heard of you by the hearing of the ear, but now my eye sees you. Therefore I abhor myself, and repent in dust and ___.''", "answer": "ashes"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: to whom, besides Eliphaz, was Yahweh''s rebuke directed?', 'Job 42:7', 'Yahweh said to Eliphaz the Temanite, ''My wrath is kindled against you, and against your two friends; for you have not spoken of me the thing that is right, as my servant Job has.''', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh said to Eliphaz the Temanite, ''My wrath is kindled against you, and against your two ___; for you have not spoken of me the thing that is right, as my servant Job has.''", "answer": "friends"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: how much did Yahweh give Job, compared to before, once he prayed for his friends?', 'Job 42:10', 'Yahweh restored Job''s prosperity when he prayed for his friends. Yahweh gave Job twice as much as he had before.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh restored Job''s prosperity when he prayed for his friends. Yahweh gave Job twice as much as he had ___.", "answer": "before"}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Job 42:12, how many sheep did Job have after his restoration — compared to Job 1:3?', 'Job 42:12; 1:3', 'So Yahweh blessed the latter end of Job more than his beginning. He had fourteen thousand sheep, six thousand camels, one thousand yoke of oxen, and a thousand female donkeys. (Job 1:3: his possessions were seven thousand sheep, three thousand camels, five hundred yoke of oxen, and five hundred female donkeys.)', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Fourteen thousand — twice his original seven thousand", "Seven thousand — the same as before", "Twenty-eight thousand — four times his original amount", "Ten thousand — an increase but not double"], "correct_index": 0}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing word from God''s first question to Job out of the whirlwind.', 'Job 38:4-7', '''Where were you when I laid the foundations of the earth? Declare, if you have understanding. Who determined its measures, if you know? Or who stretched the line on it? What were its foundations fastened on? Or who laid its cornerstone, when the morning stars sang together, and all the sons of God shouted for joy?''', 'WEB', 2,
   '{"type": "recall", "template": "''Where were you when I laid the foundations of the earth? Declare, if you have understanding. Who determined its measures, if you know? Or who stretched the line on it? What were its foundations fastened on? Or who laid its cornerstone, when the morning stars sang together, and all the sons of God shouted for ___?''", "answer": "joy"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what God asks Job about, past the gates of death.', 'Job 38:16-17', '''Have you entered into the springs of the sea? Or have you walked in the recesses of the deep? Have the gates of death been revealed to you? Or have you seen the gates of the shadow of death?''', 'WEB', 3,
   '{"type": "recall", "template": "''Have you entered into the springs of the sea? Or have you walked in the recesses of the deep? Have the gates of death been revealed to you? Or have you seen the gates of the shadow of ___?''", "answer": "death"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what the warhorse does not turn back from, per God''s speech.', 'Job 39:22', '''He mocks at fear, and is not dismayed, neither does he turn back from the sword.''', 'WEB', 1,
   '{"type": "recall", "template": "''He mocks at fear, and is not dismayed, neither does he turn back from the ___.''", "answer": "sword"}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: Job''s declaration of hope in the middle of the dialogue.', 'Job 19:25', 'But as for me, I know that my Redeemer lives. In the end, he will stand upon the earth.', 'WEB', 2,
   '{"type": "recall", "template": "But as for me, I know that my ___ lives. In the end, he will stand upon the earth.", "answer": "Redeemer"}', true, 13),
  ((select id from w), 'recall', 'Fill in the missing word closing Job''s declaration of hope.', 'Job 19:26-27', '''After my skin is destroyed, then I will see God in my flesh, whom I, even I, will see on my side. My eyes will see, and not as a stranger.''', 'WEB', 3,
   '{"type": "recall", "template": "''After my skin is destroyed, then I will see God in my flesh, whom I, even I, will see on my side. My eyes will see, and not as a ___.''", "answer": "stranger"}', false, 14),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the book of Job.', 'Job 1:20-21; 38:4-7; 42:5-6', '''Naked I came out of my mother''s womb, and naked will I return there. Yahweh gave, and Yahweh has taken away. Blessed be Yahweh''s name.''; ''Where were you when I laid the foundations of the earth?''; ''I had heard of you by the hearing of the ear, but now my eye sees you. Therefore I abhor myself, and repent in dust and ashes.''', 'WEB', 4,
   '{"type": "sequence", "items": ["“Yahweh gave, and Yahweh has taken away. Blessed be Yahweh''s name.” — Job''s response after losing everything (Job 1:21)", "“Where were you when I laid the foundations of the earth?” — the opening of Yahweh''s first speech from the whirlwind (Job 38:4)", "“I had heard of you by the hearing of the ear, but now my eye sees you.” — Job''s reply to Yahweh after the whirlwind speeches (Job 42:5)"], "correct_order": [0, 1, 2]}', true, 15)
;

with w as (select id from public.world where book_slug = 'psalms')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: where the blessed person does not sit, per Psalm 1''s opening verse.', 'Psalm 1:1', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers;', 'WEB', 1,
   '{"type": "recall", "template": "Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of ___;", "answer": "scoffers"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what happens to everything the righteous person does, per Psalm 1:3.', 'Psalm 1:3', 'He will be like a tree planted by the streams of water, that produces its fruit in its season, whose leaf also does not wither. Whatever he does shall prosper.', 'WEB', 2,
   '{"type": "recall", "template": "He will be like a tree planted by the streams of water, that produces its fruit in its season, whose leaf also does not wither. Whatever he does shall ___.", "answer": "prosper"}', false, 2),
  ((select id from w), 'multiple_choice', 'Per Psalm 1, what happens to the wicked in the wind?', 'Psalm 1:4', 'The wicked are not so, but are like the chaff which the wind drives away.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["They are driven away like chaff", "They are gathered into bundles", "They take root and grow", "They are scattered like seed"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: Psalm 23''s opening image for Yahweh.', 'Psalm 23:1', 'Yahweh is my shepherd; I shall lack nothing.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh is my ___; I shall lack nothing.", "answer": "shepherd"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what the rod and staff do, per Psalm 23:4.', 'Psalm 23:4', 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.', 'WEB', 2,
   '{"type": "recall", "template": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they ___ me.", "answer": "comfort"}', false, 5),
  ((select id from w), 'sequence', 'Put Psalm 150''s list of instruments in the order they appear in the text.', 'Psalm 150:3-5', 'Praise him with the sounding of the trumpet! Praise him with harp and lyre!; Praise him with tambourine and dancing! Praise him with stringed instruments and flute!; Praise him with loud cymbals! Praise him with resounding cymbals!', 'WEB', 3,
   '{"type": "sequence", "items": ["Trumpet, harp, and lyre (v.3)", "Tambourine and dancing, stringed instruments and flute (v.4)", "Loud cymbals and resounding cymbals (v.5)"], "correct_order": [0, 1, 2]}', true, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what David asks God to blot out, per Psalm 51''s opening plea.', 'Psalm 51:1', 'Have mercy on me, God, according to your loving kindness. According to the multitude of your tender mercies, blot out my transgressions.', 'WEB', 2,
   '{"type": "recall", "template": "Have mercy on me, God, according to your loving kindness. According to the multitude of your tender mercies, blot out my ___.", "answer": "transgressions"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what David asks God to create in him, per Psalm 51:10.', 'Psalm 51:10', 'Create in me a clean heart, O God. Renew a right spirit within me.', 'WEB', 1,
   '{"type": "recall", "template": "Create in me a clean ___, O God. Renew a right spirit within me.", "answer": "heart"}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Psalm 51''s own superscription, who confronted David that occasioned this psalm?', 'Psalm 51, superscription', 'For the Chief Musician. A Psalm by David, when Nathan the prophet came to him, after he had gone in to Bathsheba.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Nathan the prophet", "Samuel the prophet", "Elijah the prophet", "Gad the seer"], "correct_index": 0}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: how we are to come before Yahweh''s presence, per Psalm 100:2.', 'Psalm 100:1-2', 'Shout for joy to Yahweh, all you lands! Serve Yahweh with gladness. Come before his presence with singing.', 'WEB', 1,
   '{"type": "recall", "template": "Shout for joy to Yahweh, all you lands! Serve Yahweh with gladness. Come before his presence with ___.", "answer": "singing"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh made, per Psalm 121:2.', 'Psalm 121:1-2', 'I will lift up my eyes to the hills. Where does my help come from? My help comes from Yahweh, who made heaven and earth.', 'WEB', 1,
   '{"type": "recall", "template": "I will lift up my eyes to the hills. Where does my help come from? My help comes from Yahweh, who made heaven and ___.", "answer": "earth"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what the keeper of Israel does not do, per Psalm 121:4.', 'Psalm 121:4', 'Behold, he who keeps Israel will neither slumber nor sleep.', 'WEB', 2,
   '{"type": "recall", "template": "Behold, he who keeps Israel will neither slumber nor ___.", "answer": "sleep"}', false, 12),
  ((select id from w), 'sequence', 'Put these opening lines in canonical psalm-number order.', 'Psalm 23:1; 100:1; 121:1', 'Yahweh is my shepherd; I shall lack nothing.; Shout for joy to Yahweh, all you lands!; I will lift up my eyes to the hills. Where does my help come from?', 'WEB', 4,
   '{"type": "sequence", "items": ["“Yahweh is my shepherd; I shall lack nothing.” — Psalm 23:1", "“Shout for joy to Yahweh, all you lands!” — Psalm 100:1", "“I will lift up my eyes to the hills. Where does my help come from?” — Psalm 121:1"], "correct_order": [0, 1, 2]}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what Psalm 150 says to praise God for, in its opening call.', 'Psalm 150:1', 'Praise Yah! Praise God in his sanctuary! Praise him in his heavens for his acts of power!', 'WEB', 1,
   '{"type": "recall", "template": "Praise Yah! Praise God in his sanctuary! Praise him in his heavens for his acts of ___!", "answer": "power"}', true, 14),
  ((select id from w), 'recall', 'Fill in the missing word: the Psalter''s own final word, closing Psalm 150 and the whole book.', 'Psalm 150:6', 'Let everything that has breath praise Yah! Praise Yah!', 'WEB', 2,
   '{"type": "recall", "template": "Let everything that has breath praise Yah! Praise ___!", "answer": "Yah"}', true, 15)
;
