-- Gen2Rev challenge ingest: Jonah (World 32), Micah (World 33), Nahum (World 34)
-- Generated from docs/content/jonah.md, docs/content/micah.md, docs/content/nahum.md
-- All three books: theological review approved / approved-with-changes, independent
-- verbatim-text QA pass complete (docs/CONTENT_REVIEW_LOG.md rows 32-34, docs/QA_SIGNOFF.md rows 32-34).
-- Micah 5:1-5 (the "ruler from Bethlehem" oracle unit) is permanently excluded per Micah's brief.
-- Nahum 2-3's graphic destruction imagery (2:1-3:18, incl. 3:3-6 and 3:10) is permanently excluded
-- per Nahum's brief; only Nahum 3:19 is used from chapter 3, at narrative-summary framing.
-- See docs/content/jonah.md, docs/content/micah.md, docs/content/nahum.md "Contested Territory"
-- sections for full rationale.

with w as (select id from public.world where book_slug = 'jonah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what had come up before Yahweh, prompting the call to Nineveh?', 'Jonah 1:1-2', 'Now Yahweh''s word came to Jonah the son of Amittai, saying, ''Arise, go to Nineveh, that great city, and preach against it, for their wickedness has come up before me.''', 'WEB', 1,
   '{"type": "recall", "template": "Now Yahweh''s word came to Jonah the son of Amittai, saying, ''Arise, go to Nineveh, that great city, and preach against it, for their wickedness has come up before ___.''", "answer": "me"}', false, 1),
  ((select id from w), 'multiple_choice', 'Where was Jonah trying to sail to when he fled from Yahweh?', 'Jonah 1:3', 'But Jonah rose up to flee to Tarshish from the presence of Yahweh. He went down to Joppa, and found a ship going to Tarshish; so he paid its fare, and went down into it, to go with them to Tarshish from the presence of Yahweh.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Tarshish", "Nineveh", "Joppa", "Egypt"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: who did Jonah say he feared, when the sailors questioned him?', 'Jonah 1:9', 'He said to them, ''I am a Hebrew, and I fear Yahweh, the God of heaven, who has made the sea and the dry land.''', 'WEB', 1,
   '{"type": "recall", "template": "He said to them, ''I am a Hebrew, and I fear ___, the God of heaven, who has made the sea and the dry land.''", "answer": "Yahweh"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what did Jonah tell the sailors to throw him into?', 'Jonah 1:12', 'He said to them, ''Take me up, and throw me into the sea. Then the sea will be calm for you; for I know that because of me this great storm is on you.''', 'WEB', 2,
   '{"type": "recall", "template": "He said to them, ''Take me up, and throw me into the ___. Then the sea will be calm for you; for I know that because of me this great storm is on you.''", "answer": "sea"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Jonah 1:15-16, what did the sailors do after the sea ceased its raging?', 'Jonah 1:15-16', 'So they took up Jonah and threw him into the sea; and the sea ceased its raging. Then the men feared Yahweh exceedingly; and they offered a sacrifice to Yahweh and made vows.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["They feared Yahweh, offered a sacrifice, and made vows", "They abandoned the ship and swam to shore", "They cast lots again to test the outcome", "They mocked Jonah for causing the storm"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: how long was Jonah in the belly of the fish?', 'Jonah 1:17', 'Yahweh prepared a huge fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three nights.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh prepared a huge fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three ___.", "answer": "nights"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: where did Jonah cry out from, in his prayer?', 'Jonah 2:2', 'He said, ''I called because of my affliction to Yahweh. He answered me. Out of the belly of Sheol I cried. You heard my voice.''', 'WEB', 3,
   '{"type": "recall", "template": "He said, ''I called because of my affliction to Yahweh. He answered me. Out of the belly of ___ I cried. You heard my voice.''", "answer": "Sheol"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: to whom does Jonah say salvation belongs?', 'Jonah 2:9', 'But I will sacrifice to you with the voice of thanksgiving. I will pay that which I have vowed. Salvation belongs to Yahweh.', 'WEB', 2,
   '{"type": "recall", "template": "But I will sacrifice to you with the voice of thanksgiving. I will pay that which I have vowed. Salvation belongs to ___.", "answer": "Yahweh"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: where did the fish vomit Jonah out onto?', 'Jonah 2:10', 'Then Yahweh spoke to the fish, and it vomited out Jonah on the dry land.', 'WEB', 1,
   '{"type": "recall", "template": "Then Yahweh spoke to the fish, and it vomited out Jonah on the dry ___.", "answer": "land"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh tell Jonah to preach, the second time his word came?', 'Jonah 3:1-2', 'Yahweh''s word came to Jonah the second time, saying, ''Arise, go to Nineveh, that great city, and preach to it the message that I give you.''', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh''s word came to Jonah the second time, saying, ''Arise, go to Nineveh, that great city, and preach to it the message that I give ___.''", "answer": "you"}', false, 10),
  ((select id from w), 'multiple_choice', 'According to Jonah 3:4, what did Jonah proclaim would happen to Nineveh in forty days?', 'Jonah 3:4', 'Jonah began to enter into the city a day''s journey, and he cried out, and said, ''In forty days, Nineveh will be overthrown!''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["It would be overthrown", "It would be rebuilt", "It would be spared forever", "It would be renamed"], "correct_index": 0}', false, 11),
  ((select id from w), 'multiple_choice', 'According to Jonah 3:5, who among the Ninevites put on sackcloth and fasted?', 'Jonah 3:5', 'The people of Nineveh believed God; and they proclaimed a fast and put on sackcloth, from their greatest even to their least.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Everyone, from the greatest to the least", "Only the king and his nobles", "Only the prophets and priests", "Only the youngest children"], "correct_index": 0}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: what did God relent of doing to Nineveh?', 'Jonah 3:10', 'God saw their works, that they turned from their evil way. God relented of the disaster which he said he would do to them, and he didn''t do it.', 'WEB', 3,
   '{"type": "recall", "template": "God saw their works, that they turned from their evil way. God relented of the ___ which he said he would do to them, and he didn''t do it.", "answer": "disaster"}', true, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what did Jonah say Yahweh was slow to, in his prayer of complaint?', 'Jonah 4:2', 'He prayed to Yahweh, and said, ''Please, Yahweh, wasn''t this what I said when I was still in my own country? Therefore I hurried to flee to Tarshish, for I knew that you are a gracious God and merciful, slow to anger, and abundant in loving kindness, and you relent of doing harm.''', 'WEB', 3,
   '{"type": "recall", "template": "He prayed to Yahweh, and said, ''Please, Yahweh, wasn''t this what I said when I was still in my own country? Therefore I hurried to flee to Tarshish, for I knew that you are a gracious God and merciful, slow to ___, and abundant in loving kindness, and you relent of doing harm.''", "answer": "anger"}', false, 14),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh God prepare to shade Jonah?', 'Jonah 4:6', 'Yahweh God prepared a vine and made it to come up over Jonah, that it might be a shade over his head to deliver him from his discomfort. So Jonah was exceedingly glad because of the vine.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh God prepared a ___ and made it to come up over Jonah, that it might be a shade over his head to deliver him from his discomfort. So Jonah was exceedingly glad because of the vine.", "answer": "vine"}', false, 15),
  ((select id from w), 'multiple_choice', 'According to Jonah 4:9, how did Jonah respond when Yahweh asked if it was right for him to be angry about the vine?', 'Jonah 4:9', 'God said to Jonah, ''Is it right for you to be angry about the vine?'' He said, ''I am right to be angry, even to death.''', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["''I am right to be angry, even to death.''", "''No, I was wrong to be angry.''", "He said nothing and walked away.", "He asked Yahweh for forgiveness."], "correct_index": 0}', false, 16),
  ((select id from w), 'recall', 'Fill in the missing word: which great city does Yahweh say he is concerned for, in the book''s closing question?', 'Jonah 4:10-11', 'Yahweh said, ''You have been concerned for the vine, for which you have not labored, neither made it grow; which came up in a night and perished in a night. Shouldn''t I be concerned for Nineveh, that great city, in which are more than one hundred twenty thousand persons who can''t discern between their right hand and their left hand, and also many animals?''', 'WEB', 4,
   '{"type": "recall", "template": "Yahweh said, ''You have been concerned for the vine, for which you have not labored, neither made it grow; which came up in a night and perished in a night. Shouldn''t I be concerned for ___, that great city, in which are more than one hundred twenty thousand persons who can''t discern between their right hand and their left hand, and also many animals?''", "answer": "Nineveh"}', true, 17),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Jonah 1:12; 3:4; 4:2', 'The plea to be thrown into the sea; the forty-day proclamation; Jonah''s prayer explaining his flight', 'WEB', 4,
   '{"type": "sequence", "items": ["''Take me up, and throw me into the sea... for I know that because of me this great storm is on you.'' \u2014 Jonah''s plea to the sailors (1:12)", "''In forty days, Nineveh will be overthrown!'' \u2014 Jonah''s proclamation in the city (3:4)", "''I knew that you are a gracious God and merciful, slow to anger...'' \u2014 Jonah''s prayer explaining his flight (4:2)"], "correct_order": [0, 1, 2]}', false, 18),
  ((select id from w), 'sequence', 'Put these pivotal scenes in the order they appear in the book of Jonah.', 'Jonah 1-4', 'The call and the flight; the storm and the sailors; the fish and Jonah''s prayer; the call renewed and Nineveh''s repentance; Jonah''s anger and the plant', 'WEB', 5,
   '{"type": "sequence", "items": ["The call to go to Nineveh and Jonah''s flight to Tarshish", "The storm at sea and the sailors casting lots", "Jonah thrown into the sea and swallowed by the great fish", "Jonah''s prayer and the fish vomiting him onto dry land", "The renewed call and Nineveh''s repentance", "Jonah''s anger and the vine"], "correct_order": [0, 1, 2, 3, 4, 5]}', true, 19)
;

with w as (select id from public.world where book_slug = 'micah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: from where does the Lord Yahweh act as witness, in Micah''s opening summons?', 'Micah 1:2', 'Hear, you peoples, all of you! Listen, O earth, and all that is therein. Let the Lord Yahweh be witness against you, the Lord from his holy temple.', 'WEB', 1,
   '{"type": "recall", "template": "Hear, you peoples, all of you! Listen, O earth, and all that is therein. Let the Lord Yahweh be witness against you, the Lord from his holy ___.", "answer": "temple"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh tread on as he comes out of his place?', 'Micah 1:3', 'For behold, Yahweh comes out of his place, and will come down and tread on the high places of the earth.', 'WEB', 2,
   '{"type": "recall", "template": "For behold, Yahweh comes out of his place, and will come down and tread on the high places of the ___.", "answer": "earth"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what do the mountains melt like, before Yahweh?', 'Micah 1:4', 'The mountains melt under him, and the valleys split apart like wax before the fire, like waters that are poured down a steep place.', 'WEB', 2,
   '{"type": "recall", "template": "The mountains melt under him, and the valleys split apart like wax before the ___, like waters that are poured down a steep place.", "answer": "fire"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: where will the mountain of Yahweh''s temple be established?', 'Micah 4:1', 'But in the latter days, it will happen that the mountain of Yahweh''s temple will be established on the top of the mountains, and it will be exalted above the hills; and peoples will stream to it.', 'WEB', 1,
   '{"type": "recall", "template": "But in the latter days, it will happen that the mountain of Yahweh''s temple will be established on the top of the ___, and it will be exalted above the hills; and peoples will stream to it.", "answer": "mountains"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: from where will the law go out, according to Micah 4:2?', 'Micah 4:2', 'Many nations will go and say, ''Come! Let''s go up to the mountain of Yahweh, and to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths.'' For the law will go out of Zion, and Yahweh''s word from Jerusalem;', 'WEB', 2,
   '{"type": "recall", "template": "Many nations will go and say, ''Come! Let''s go up to the mountain of Yahweh, and to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths.'' For the law will go out of ___, and Yahweh''s word from Jerusalem;", "answer": "Zion"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Micah 4:3, what will nations beat their swords into?', 'Micah 4:3', 'and he will judge between many peoples, and will decide concerning strong nations afar off. They will beat their swords into plowshares, and their spears into pruning hooks. Nation will not lift up sword against nation, neither will they learn war any more.', 'WEB', 1,
   '{"type": "multiple_choice", "options": ["Plowshares", "Chariots", "Altars", "Idols"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to Micah 4:4, what will every man sit under, safe and unafraid?', 'Micah 4:4', 'But every man will sit under his vine and under his fig tree. No one will make them afraid, for the mouth of Yahweh of Armies has spoken.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["His vine and his fig tree", "A tent of goat''s hair", "The shade of a great cedar", "A tabernacle of testimony"], "correct_index": 0}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what kind of offerings does Micah ask if Yahweh wants?', 'Micah 6:6', 'How shall I come before Yahweh, and bow myself before the exalted God? Shall I come before him with burnt offerings, with calves a year old?', 'WEB', 2,
   '{"type": "recall", "template": "How shall I come before Yahweh, and bow myself before the exalted God? Shall I come before him with burnt ___, with calves a year old?", "answer": "offerings"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what does Micah 6:7 call the sin needing atonement?', 'Micah 6:7', 'Will Yahweh be pleased with thousands of rams? With tens of thousands of rivers of oil? Shall I give my firstborn for my disobedience? The fruit of my body for the sin of my soul?', 'WEB', 3,
   '{"type": "recall", "template": "Will Yahweh be pleased with thousands of rams? With tens of thousands of rivers of oil? Shall I give my firstborn for my disobedience? The fruit of my body for the sin of my ___?", "answer": "soul"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: with whom does Yahweh require you to walk humbly?', 'Micah 6:8', 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?', 'WEB', 1,
   '{"type": "recall", "template": "He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your ___?", "answer": "God"}', true, 10),
  ((select id from w), 'multiple_choice', 'According to Micah 6:8, what does Yahweh require of you besides acting justly and loving mercy?', 'Micah 6:8', 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["To walk humbly with your God", "To offer burnt offerings daily", "To give your firstborn as a sacrifice", "To fast for forty days"], "correct_index": 0}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: in what does Yahweh delight, according to Micah 7:18?', 'Micah 7:18', 'Who is a God like you, who pardons iniquity, and passes over the disobedience of the remnant of his heritage? He doesn''t retain his anger forever, because he delights in loving kindness.', 'WEB', 2,
   '{"type": "recall", "template": "Who is a God like you, who pardons iniquity, and passes over the disobedience of the remnant of his heritage? He doesn''t retain his anger forever, because he delights in loving ___.", "answer": "kindness"}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: where will Yahweh cast the people''s sins, according to Micah 7:19?', 'Micah 7:19', 'He will again have compassion on us. He will tread our iniquities under foot. You will cast all their sins into the depths of the sea.', 'WEB', 2,
   '{"type": "recall", "template": "He will again have compassion on us. He will tread our iniquities under foot. You will cast all their sins into the depths of the ___.", "answer": "sea"}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: to whom besides Jacob does Yahweh give mercy, according to Micah 7:20?', 'Micah 7:20', 'You will give truth to Jacob, and mercy to Abraham, as you have sworn to our fathers from the days of old.', 'WEB', 3,
   '{"type": "recall", "template": "You will give truth to Jacob, and mercy to ___, as you have sworn to our fathers from the days of old.", "answer": "Abraham"}', false, 14),
  ((select id from w), 'sequence', 'Order the pivotal passages as they appear in the book of Micah.', 'Micah 1:2-4; 4:1-4; 6:6-8; 7:18-20', 'Yahweh comes in judgment; swords into plowshares; what Yahweh requires; who is a God like you', 'WEB', 3,
   '{"type": "sequence", "items": ["Yahweh comes out of his place in judgment (1:2-4)", "Swords beaten into plowshares (4:1-4)", "What does Yahweh require of you? (6:6-8)", "Who is a God like you? (7:18-20)"], "correct_order": [0, 1, 2, 3]}', false, 15),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Micah 4:3; 6:8; 7:18', 'Swords into plowshares; what Yahweh requires; who is a God like you', 'WEB', 4,
   '{"type": "sequence", "items": ["''They will beat their swords into plowshares, and their spears into pruning hooks.'' \u2014 the vision of nations at peace (4:3)", "''To act justly, to love mercy, and to walk humbly with your God?'' \u2014 what Yahweh requires (6:8)", "''Who is a God like you, who pardons iniquity...'' \u2014 the closing hymn of praise (7:18)"], "correct_order": [0, 1, 2]}', false, 16),
  ((select id from w), 'sequence', 'Put these four pivotal passages in the order they appear in the book of Micah, from the opening theophany to the closing hymn.', 'Micah 1:3; 4:3; 6:8; 7:18', 'Yahweh''s coming; swords into plowshares; what Yahweh requires; who is a God like you', 'WEB', 5,
   '{"type": "sequence", "items": ["''Yahweh comes out of his place, and will come down and tread on the high places of the earth.'' \u2014 the opening theophany (1:3)", "''They will beat their swords into plowshares, and their spears into pruning hooks.'' \u2014 swords into plowshares (4:3)", "''What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?'' \u2014 what Yahweh requires (6:8)", "''Who is a God like you, who pardons iniquity...'' \u2014 the closing hymn of praise (7:18)"], "correct_order": [0, 1, 2, 3]}', true, 17)
;

with w as (select id from public.world where book_slug = 'nahum')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what is Yahweh full of, according to Nahum 1:2?', 'Nahum 1:2', 'Yahweh is a jealous God and avenges. Yahweh avenges and is full of wrath.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh is a jealous God and avenges. Yahweh avenges and is full of ___.", "answer": "wrath"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what is Yahweh great in, according to Nahum 1:3?', 'Nahum 1:3', 'Yahweh is slow to anger, and great in power, and will by no means leave the guilty unpunished.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh is slow to anger, and great in ___, and will by no means leave the guilty unpunished.", "answer": "power"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what is Yahweh, in the day of trouble?', 'Nahum 1:7', 'Yahweh is good, a stronghold in the day of trouble; and he knows those who take refuge in him.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh is good, a ___ in the day of trouble; and he knows those who take refuge in him.", "answer": "stronghold"}', true, 3),
  ((select id from w), 'multiple_choice', 'According to Nahum 1:7, who does Yahweh know?', 'Nahum 1:7', 'Yahweh is good, a stronghold in the day of trouble; and he knows those who take refuge in him.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Those who take refuge in him", "Those who fast and pray daily", "Only the kings of Judah", "Everyone without exception"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what does the messenger on the mountains publish, besides good news?', 'Nahum 1:15', 'Behold, on the mountains the feet of him who brings good news, who publishes peace! Keep your feasts, Judah! Perform your vows, for the wicked one will no more pass through you. He is utterly cut off.', 'WEB', 2,
   '{"type": "recall", "template": "Behold, on the mountains the feet of him who brings good news, who publishes ___! Keep your feasts, Judah! Perform your vows, for the wicked one will no more pass through you. He is utterly cut off.", "answer": "peace"}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Nahum 1:15, what does the messenger on the mountains bring?', 'Nahum 1:15', 'Behold, on the mountains the feet of him who brings good news, who publishes peace! Keep your feasts, Judah! Perform your vows, for the wicked one will no more pass through you. He is utterly cut off.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Good news and peace", "A call to battle", "A decree of taxation", "A warning of famine"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what does Nahum 3:19 say cannot be healed?', 'Nahum 3:19', 'There is no healing your wound, for your injury is fatal. All who hear the report of you clap their hands over you, for who hasn''t felt your endless cruelty?', 'WEB', 2,
   '{"type": "recall", "template": "There is no healing your ___, for your injury is fatal. All who hear the report of you clap their hands over you, for who hasn''t felt your endless cruelty?", "answer": "wound"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Nahum 3:19, who claps their hands over Nineveh''s fall?', 'Nahum 3:19', 'There is no healing your wound, for your injury is fatal. All who hear the report of you clap their hands over you, for who hasn''t felt your endless cruelty?', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["All who hear the report of it", "Only the king''s own soldiers", "No one \u2014 the fall goes unnoticed", "Only the priests of Judah"], "correct_index": 0}', false, 8),
  ((select id from w), 'sequence', 'Order the pivotal passages as they appear in the book of Nahum.', 'Nahum 1:2-3, 1:7; 1:15; 3:19', 'Yahweh''s character: just and good; good news for Judah; the certainty of Nineveh''s fall', 'WEB', 3,
   '{"type": "sequence", "items": ["Yahweh''s character: just and good (1:2-3, 1:7)", "Good news for Judah (1:15)", "The certainty of Nineveh''s fall (ch. 3)"], "correct_order": [0, 1, 2]}', false, 9),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Nahum 1:3; 1:7; 3:19', 'Yahweh''s justice; Yahweh''s goodness; the certainty of Nineveh''s fall', 'WEB', 4,
   '{"type": "sequence", "items": ["''Yahweh is slow to anger, and great in power, and will by no means leave the guilty unpunished.'' \u2014 Yahweh''s justice (1:3)", "''Yahweh is good, a stronghold in the day of trouble; and he knows those who take refuge in him.'' \u2014 Yahweh''s goodness (1:7)", "''There is no healing your wound, for your injury is fatal.'' \u2014 the certainty of Nineveh''s fall (3:19)"], "correct_order": [0, 1, 2]}', false, 10),
  ((select id from w), 'sequence', 'This world''s capstone: place these three closing lines in the order they appear across the book of Nahum.', 'Nahum 1:7; 1:15; 3:19', 'Yahweh as stronghold; good news and peace; Nineveh''s fatal wound', 'WEB', 3,
   '{"type": "sequence", "items": ["''Yahweh is good, a stronghold in the day of trouble.'' (1:7)", "''Behold, on the mountains the feet of him who brings good news, who publishes peace!'' (1:15)", "''There is no healing your wound, for your injury is fatal.'' (3:19)"], "correct_order": [0, 1, 2]}', true, 11)
;
