-- Gen2Rev challenge ingest: Joshua (World 6), Judges (World 7), Ruth (World 8)
-- Generated from docs/content/joshua.md, docs/content/judges.md, docs/content/ruth.md
-- All three books: theological review approved / approved-with-changes, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md, docs/QA_SIGNOFF.md, both 2026-08-08).
-- Joshua: herem/destruction-clause verses (6:17, 6:21, 10:40's destruction clause) are
-- permanently excluded; Scene 4 (10:41-42) used in recall format only, per Kachi Okere's
-- 2026-08-08 escalation sign-off. Judges: Jephthah's daughter (ch. 11), the Levite's
-- concubine (ch. 19), and Jael/Sisera's killing (4:17-22, 5:24-27) are excluded entirely;
-- Judges 4:4-5 and 6:37 are recall-only per theological review. Ruth 4:9-10 is recall-only
-- per theological review.


with w as (select id from public.world where book_slug = 'joshua')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: where did Joshua secretly send two men from as spies?', 'Joshua 2:1', 'Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, ''Go, view the land, including Jericho.''', 'WEB', 1,
   '{"type": "recall", "template": "Joshua the son of Nun secretly sent two men out of ___ as spies, saying, ''Go, view the land, including Jericho.''", "answer": "Shittim"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Joshua 2:21, what did Rahab tie in her window as a sign?', 'Joshua 2:21', 'She said, ''Let it be as you have said.'' She sent them away, and they departed. Then she tied the scarlet line in the window.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["A scarlet line", "A blue cord", "A white cloth", "A gold thread"], "correct_index": 0}', false, 2),
  ((select id from w), 'sequence', 'Put these events of the Jericho siege in the order they happen in the text.', 'Joshua 6:3-5; 6:20', 'All of your men of war shall march around the city, going around the city once. You shall do this six days. Seven priests shall bear seven trumpets of rams'' horns before the ark. On the seventh day, you shall march around the city seven times, and the priests shall blow the trumpets. It shall be that when they make a long blast with the ram''s horn, and when you hear the sound of the trumpet, all the people shall shout with a great shout; then the city wall will fall down flat.; So the people shouted and the priests blew the trumpets. When the people heard the sound of the trumpet, the people shouted with a great shout, and the wall fell down flat, so that the people went up into the city, every man straight in front of him, and they took the city.', 'WEB', 3,
   '{"type": "sequence", "items": ["Israel''s men of war march around the city once a day for six days", "On the seventh day they march around the city seven times", "The priests blow the trumpets and the people shout with a great shout", "The wall falls down flat and the people take the city"], "correct_order": [0, 1, 2, 3]}', true, 3),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text and match each to its scene.', 'Joshua 2:9-11; 4:22-24; 21:43-45', 'I know that Yahweh has given you the land, and that the fear of you has fallen upon us... we have heard how Yahweh dried up the water of the Red Sea before you, when you came out of Egypt... our hearts melted, and there wasn''t any more spirit in any man, because of you.; ...you shall let your children know, saying, Israel came over this Jordan on dry land... that all the peoples of the earth may know that Yahweh''s hand is mighty, and that you may fear Yahweh your God forever.; So Yahweh gave to Israel all the land which he swore to give to their fathers. They possessed it, and lived in it. Yahweh gave them rest all around, according to all that he swore to their fathers. Not a man of all their enemies stood before them. Yahweh delivered all their enemies into their hand. Nothing failed of any good thing which Yahweh had spoken to the house of Israel. All came to pass.', 'WEB', 4,
   '{"type": "sequence", "items": ["\"...we have heard how Yahweh dried up the water of the Red Sea before you... our hearts melted...\" — Rahab to the spies (Joshua 2:9-11)", "\"...that all the peoples of the earth may know that Yahweh''s hand is mighty...\" — Joshua explaining the memorial stones (Joshua 4:22-24)", "\"Not a man of all their enemies stood before them... Nothing failed of any good thing which Yahweh had spoken.\" — the land-division summary (Joshua 21:43-45)"], "correct_order": [0, 1, 2]}', true, 4),
  ((select id from w), 'multiple_choice', 'According to Joshua 4:6-7, why did Israel set up twelve stones at Gilgal?', 'Joshua 4:6-7', '...that this may be a sign among you, that when your children ask in the future, saying, What do you mean by these stones? then you shall tell them, Because the waters of the Jordan were cut off before the ark of Yahweh''s covenant. When it crossed over the Jordan, the waters of the Jordan were cut off. These stones shall be for a memorial to the children of Israel forever.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["So future generations would ask about them and be told the story of the Jordan crossing", "To mark the boundary of the Promised Land", "As an offering to Yahweh for victory in battle", "To count the number of fighting men who crossed"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: where did the priests carrying the ark stand firm while Israel crossed?', 'Joshua 3:15-17', '...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho. The priests who bore the ark of Yahweh''s covenant stood firm on dry ground in the middle of the Jordan; and all Israel crossed over on dry ground, until all the nation had passed completely over the Jordan.', 'WEB', 1,
   '{"type": "recall", "template": "...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho. The priests who bore the ark of Yahweh''s covenant stood firm on dry ground in the middle of the ___; and all Israel crossed over on dry ground, until all the nation had passed completely over the Jordan.", "answer": "Jordan"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing place name from Joshua''s campaign summary.', 'Joshua 10:41-42', 'Joshua struck them from Kadesh Barnea even to Gaza, and all the country of Goshen, even to Gibeon. Joshua took all these kings and their land at one time because Yahweh, the God of Israel, fought for Israel.', 'WEB', 2,
   '{"type": "recall", "template": "Joshua struck them from Kadesh Barnea even to Gaza, and all the country of Goshen, even to ___. Joshua took all these kings and their land at one time because Yahweh, the God of Israel, fought for Israel.", "answer": "Gibeon"}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word from Caleb''s request to Joshua.', 'Joshua 14:10-12', '...now, behold, I am eighty-five years old, today. As yet I am as strong today as I was in the day that Moses sent me... Now therefore give me this hill country, of which Yahweh spoke in that day...', 'WEB', 2,
   '{"type": "recall", "template": "...now, behold, I am eighty-five years old, today. As yet I am as strong today as I was in the day that Moses sent me... Now therefore give me this ___ country, of which Yahweh spoke in that day...", "answer": "hill"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: who did Rahab hide, according to Joshua 6:25?', 'Joshua 6:25', 'But Rahab the prostitute, her father''s household, and all that she had, Joshua saved alive. She lives in the middle of Israel to this day, because she hid the messengers whom Joshua sent to spy out Jericho.', 'WEB', 2,
   '{"type": "recall", "template": "But Rahab the prostitute, her father''s household, and all that she had, Joshua saved alive. She lives in the middle of Israel to this day, because she hid the ___ whom Joshua sent to spy out Jericho.", "answer": "messengers"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word closing the summary of the land-division section.', 'Joshua 21:43-45', 'So Yahweh gave to Israel all the land which he swore to give to their fathers. They possessed it, and lived in it. Yahweh gave them rest all around, according to all that he swore to their fathers. Not a man of all their enemies stood before them. Yahweh delivered all their enemies into their hand. Nothing failed of any good thing which Yahweh had spoken to the house of Israel. All came to pass.', 'WEB', 1,
   '{"type": "recall", "template": "So Yahweh gave to Israel all the land which he swore to give to their fathers. They possessed it, and lived in it. Yahweh gave them rest all around, according to all that he swore to their fathers. Not a man of all their enemies stood before them. Yahweh delivered all their enemies into their hand. Nothing failed of any good thing which Yahweh had spoken to the house of Israel. All came to ___.", "answer": "pass"}', false, 10)
;

with w as (select id from public.world where book_slug = 'judges')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word closing the book of Judges.', 'Judges 21:25', 'In those days there was no king in Israel. Everyone did that which was right in his own eyes.', 'WEB', 1,
   '{"type": "recall", "template": "In those days there was no king in Israel. Everyone did that which was ___ in his own eyes.", "answer": "right"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: into whose hands did Yahweh deliver Israel when his anger burned against them?', 'Judges 2:14', 'Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh''s anger burned against Israel, and he delivered them into the hands of ___ who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.", "answer": "raiders"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: who did Yahweh raise up to save Israel from the hand of those who plundered them?', 'Judges 2:16', 'Yahweh raised up judges, who saved them out of the hand of those who plundered them.', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh raised up ___, who saved them out of the hand of those who plundered them.", "answer": "judges"}', false, 3),
  ((select id from w), 'sequence', 'Put these steps of the judges'' cycle, as the narrator describes it, in the order they happen in the text.', 'Judges 2:14; 2:16; 2:18-19', 'Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.; Yahweh raised up judges, who saved them out of the hand of those who plundered them.; When Yahweh raised up judges for them, then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the judge... But when the judge was dead, they turned back, and dealt more corruptly than their fathers...', 'WEB', 3,
   '{"type": "sequence", "items": ["Yahweh hands Israel over to raiders who plunder them", "Yahweh raises up judges who save them from the plunderers", "While the judge is alive, Yahweh saves them from their enemies", "When the judge dies, the people turn back and deal more corruptly than their fathers"], "correct_order": [0, 1, 2, 3]}', true, 4),
  ((select id from w), 'recall', 'Fill in the missing word describing Deborah''s role, per Judges 4:4-5.', 'Judges 4:4-5', 'Now Deborah, a prophetess, the wife of Lappidoth, judged Israel at that time. She lived under Deborah''s palm tree between Ramah and Bethel in the hill country of Ephraim; and the children of Israel came up to her for judgment.', 'WEB', 1,
   '{"type": "recall", "template": "Now Deborah, a ___, the wife of Lappidoth, judged Israel at that time. She lived under Deborah''s palm tree between Ramah and Bethel in the hill country of Ephraim; and the children of Israel came up to her for judgment.", "answer": "prophetess"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing place name from Deborah''s instruction to Barak.', 'Judges 4:6-7', '...Go and lead the way to Mount Tabor, and take with you ten thousand men of the children of Naphtali and of the children of Zebulun... I will draw to you, to the river Kishon, Sisera, the captain of Jabin''s army... and I will deliver him into your hand.', 'WEB', 2,
   '{"type": "recall", "template": "...Go and lead the way to ___, and take with you ten thousand men of the children of Naphtali and of the children of Zebulun... I will draw to you, to the river Kishon, Sisera, the captain of Jabin''s army... and I will deliver him into your hand.", "answer": "Mount Tabor"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what had Yahweh done with Sisera, according to Deborah?', 'Judges 4:14-16', 'Deborah said to Barak, ''Go; for this is the day in which Yahweh has delivered Sisera into your hand...'' Yahweh confused Sisera, all his chariots, and all his army, with the edge of the sword before Barak... all the army of Sisera fell by the edge of the sword. There was not a man left.', 'WEB', 2,
   '{"type": "recall", "template": "Deborah said to Barak, ''Go; for this is the day in which Yahweh has ___ Sisera into your hand...'' Yahweh confused Sisera, all his chariots, and all his army, with the edge of the sword before Barak... all the army of Sisera fell by the edge of the sword. There was not a man left.", "answer": "delivered"}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what did Gideon say his family was, in Manasseh?', 'Judges 6:14-16', 'Yahweh looked at him, and said, ''Go in this your might, and save Israel from the hand of Midian. Haven''t I sent you?'' He said to him, ''O Lord, how shall I save Israel? Behold, my family is the poorest in Manasseh, and I am the least in my father''s house.'' Yahweh said to him, ''Surely I will be with you, and you shall strike the Midianites as one man.''', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh looked at him, and said, ''Go in this your might, and save Israel from the hand of Midian. Haven''t I sent you?'' He said to him, ''O Lord, how shall I save Israel? Behold, my family is the ___ in Manasseh, and I am the least in my father''s house.'' Yahweh said to him, ''Surely I will be with you, and you shall strike the Midianites as one man.''", "answer": "poorest"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what did Gideon put on the threshing floor as a sign?', 'Judges 6:37', '...behold, I will put a fleece of wool on the threshing floor. If there is dew on the fleece only, and it is dry on all the ground, then I''ll know that you will save Israel by my hand, as you have spoken.', 'WEB', 2,
   '{"type": "recall", "template": "...behold, I will put a ___ of wool on the threshing floor. If there is dew on the fleece only, and it is dry on all the ground, then I''ll know that you will save Israel by my hand, as you have spoken.", "answer": "fleece"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Judges 7:2, why did Yahweh tell Gideon his army was too many?', 'Judges 7:2', 'The people who are with you are too many for me to give the Midianites into their hand, lest Israel brag against me, saying, ''My own hand has saved me.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["So Israel could not claim the victory was won by their own strength", "So the army would be easier to feed during the campaign", "So Gideon could personally command every soldier by name", "So the Midianites would underestimate Israel''s numbers"], "correct_index": 0}', true, 10),
  ((select id from w), 'sequence', 'Put these moments of Gideon''s story in the order they happen in the text.', 'Judges 6:14-16; 6:37; 7:2; 7:20-21', 'Yahweh looked at him, and said, ''Go in this your might, and save Israel from the hand of Midian. Haven''t I sent you?'' He said to him, ''O Lord, how shall I save Israel? Behold, my family is the poorest in Manasseh, and I am the least in my father''s house.'' Yahweh said to him, ''Surely I will be with you, and you shall strike the Midianites as one man.''; ...behold, I will put a fleece of wool on the threshing floor. If there is dew on the fleece only, and it is dry on all the ground, then I''ll know that you will save Israel by my hand, as you have spoken.; The people who are with you are too many for me to give the Midianites into their hand, lest Israel brag against me, saying, ''My own hand has saved me.''; ...they shouted, ''The sword of Yahweh and of Gideon!'' They each stood in his place around the camp, and all the army ran; and they shouted, and put them to flight.', 'WEB', 4,
   '{"type": "sequence", "items": ["Yahweh calls Gideon to save Israel, and Gideon objects that his family is the poorest in Manasseh (Judges 6:14-16)", "Gideon asks for a sign, setting a fleece of wool on the threshing floor (Judges 6:37)", "Yahweh tells Gideon his army is too many, so Israel can''t claim credit for the victory (Judges 7:2)", "The three hundred shout ''The sword of Yahweh and of Gideon!'' and the Midianite army flees (Judges 7:20-21)"], "correct_order": [0, 1, 2, 3]}', false, 11)
;

with w as (select id from public.world where book_slug = 'ruth')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: Ruth''s declaration of loyalty to Naomi.', 'Ruth 1:16', 'Don''t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God.', 'WEB', 1,
   '{"type": "recall", "template": "Don''t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will ___. Your people will be my people, and your God my God.", "answer": "stay"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what did Ruth say she would do where Naomi died?', 'Ruth 1:17', 'Where you die, I will die, and there I will be buried. May Yahweh do so to me, and more also, if anything but death parts you and me.', 'WEB', 1,
   '{"type": "recall", "template": "Where you die, I will die, and there I will be ___. May Yahweh do so to me, and more also, if anything but death parts you and me.", "answer": "buried"}', false, 2),
  ((select id from w), 'multiple_choice', 'In whose field did Ruth happen to glean grain?', 'Ruth 2:2-3', 'Ruth the Moabitess said to Naomi, ''Let me now go to the field, and glean among the ears of grain after him in whose sight I find favor.''... she happened to come to the portion of the field belonging to Boaz, who was of the family of Elimelech.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Boaz''s field", "Elimelech''s field", "Naomi''s field", "Orpah''s field"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: who did Boaz tell Ruth to stay close to while gleaning?', 'Ruth 2:8-9', 'Then Boaz said to Ruth, ''Listen, my daughter. Don''t go to glean in another field, and don''t go from here, but stay here close to my maidens... Haven''t I commanded the young men not to touch you?''', 'WEB', 2,
   '{"type": "recall", "template": "Then Boaz said to Ruth, ''Listen, my daughter. Don''t go to glean in another field, and don''t go from here, but stay here close to my ___... Haven''t I commanded the young men not to touch you?''", "answer": "maidens"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what did Ruth ask Boaz to do at the threshing floor?', 'Ruth 3:9', 'She answered, ''I am Ruth your servant. Therefore spread the corner of your garment over your servant; for you are a near kinsman.''', 'WEB', 2,
   '{"type": "recall", "template": "She answered, ''I am Ruth your servant. Therefore spread the corner of your garment over your servant; for you are a near ___.''", "answer": "kinsman"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz say the whole city knew Ruth to be?', 'Ruth 3:11', 'Now, my daughter, don''t be afraid. I will do to you all that you say; for all the city of my people knows that you are a worthy woman.', 'WEB', 1,
   '{"type": "recall", "template": "Now, my daughter, don''t be afraid. I will do to you all that you say; for all the city of my people knows that you are a ___ woman.", "answer": "worthy"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz call the elders and people at the gate, according to Ruth 4:9-10?', 'Ruth 4:9-10', 'Boaz said to the elders and to all the people, ''You are witnesses today, that I have bought all that was Elimelech''s, and all that was Chilion''s and Mahlon''s, from the hand of Naomi. Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife... You are witnesses today.''', 'WEB', 3,
   '{"type": "recall", "template": "Boaz said to the elders and to all the people, ''You are ___ today, that I have bought all that was Elimelech''s, and all that was Chilion''s and Mahlon''s, from the hand of Naomi. Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife... You are ___ today.''", "answer": "witnesses"}', true, 7),
  ((select id from w), 'multiple_choice', 'According to Ruth 4:17, who was Obed''s grandson?', 'Ruth 4:17', 'The women, her neighbors, gave him a name, saying, ''A son is born to Naomi''. They named him Obed. He is the father of Jesse, the father of David.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["David", "Boaz", "Jesse", "Salmon"], "correct_index": 0}', true, 8),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the text and match each to its scene.', 'Ruth 1:16; 3:9; 4:13-14', 'Don''t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God.; She answered, ''I am Ruth your servant. Therefore spread the corner of your garment over your servant; for you are a near kinsman.''; So Boaz took Ruth and she became his wife... and she bore a son. The women said to Naomi, ''Blessed be Yahweh, who has not left you today without a near kinsman. Let his name be famous in Israel.''', 'WEB', 4,
   '{"type": "sequence", "items": ["\"...where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God.\" — Ruth''s declaration to Naomi (Ruth 1:16)", "\"I am Ruth your servant... spread the corner of your garment over your servant; for you are a near kinsman.\" — Ruth''s request to Boaz at the threshing floor (Ruth 3:9)", "\"Blessed be Yahweh, who has not left you today without a near kinsman. Let his name be famous in Israel.\" — the women''s blessing over Naomi after Obed''s birth (Ruth 4:13-14)"], "correct_order": [0, 1, 2]}', true, 9)
;
