-- Gen2Rev challenge ingest: Joshua/Judges/Ruth EASY and HARD difficulty tiers
-- (World 6 = Joshua, World 7 = Judges, World 8 = Ruth)
-- Generated from the finalized, fixed, theologically-reviewed, verbatim-QA-passed content briefs:
--   docs/content/joshua-easy.md, docs/content/joshua-hard.md
--   docs/content/judges-easy.md, docs/content/judges-hard.md
--   docs/content/ruth-easy.md,   docs/content/ruth-hard.md
-- Schema/syntax template: docs/ingest/joshua-judges-ruth.sql (the original medium-tier ingest).
--
-- difficulty_rank is flat per tier per the ingestion spec: 1 for every easy-tier row, 5 for every
-- hard-tier row (not the varying per-item ranks used in the medium-tier ingest).
--
-- *** RESOLVED ESCALATION (2026-08-22) ***
-- docs/content/joshua-easy.md's item 10 (a boss recall item on Joshua 10:41, originally blanking
-- "Gaza") carried an unresolved `escalate-to-human` verdict on political/child-safety-sensitivity
-- grounds tied to present-day Gaza geography. Kachi Okere (named human theological reviewer,
-- 2026-08-08 sign-off) resolved it 2026-08-22 by choosing the review's preferred option: the blanked
-- token moves to "Gibeon" instead, same verse, same format. See the addendum at the bottom of
-- `docs/reviews/joshua-easy-review.md` and the updated item 10 row in
-- `docs/qa/joshua-easy-verbatim-qa.md`. Joshua-easy therefore ships with all 10 items below.
--
-- Ḥerem/destruction-clause verses (Joshua 6:17, 6:21, 10:40) and excluded Judges material (ch. 11,
-- ch. 19, Jael's killing of Sisera at 4:17-22/5:24-27) are confirmed absent from every item below,
-- per each brief's own Contested Territory self-check and re-confirmed by grep before finalizing this
-- file.


-- ===================== Joshua — EASY tier (10 items) =====================

with w as (select id from public.world where book_slug = 'joshua')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'What did Joshua tell the two spies to do?', 'Joshua 2:1', 'Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, ''Go, view the land, including Jericho.''...', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["View the land, including Jericho", "Attack the king of Jericho", "Bring back gold from Jericho", "Meet with Rahab in secret"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'What did Rahab tie in her window as a sign?', 'Joshua 2:21', 'She said, ''Let it be as you have said.'' She sent them away, and they departed. Then she tied the scarlet line in the window.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a scarlet line", "a white flag", "a blue cord", "a bundle of straw"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'How did Israel cross the Jordan River?', 'Joshua 3:16-17', '...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho. The priests who bore the ark of Yahweh''s covenant stood firm on dry ground in the middle of the Jordan; and all Israel crossed over on dry ground, until all the nation had passed completely over the Jordan.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["On dry ground, because the waters stood in a heap", "By boat, one tribe at a time", "By swimming across", "They did not cross the Jordan"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'What were the stones set up at the Jordan to help future generations remember?', 'Joshua 4:6-7', '...that this may be a sign among you, that when your children ask in the future, saying, What do you mean by these stones? then you shall tell them, Because the waters of the Jordan were cut off before the ark of Yahweh''s covenant. When it crossed over the Jordan, the waters of the Jordan were cut off. These stones shall be for a memorial to the children of Israel forever.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["That the waters of the Jordan were cut off before the ark of Yahweh''s covenant", "A battle Israel won at Jericho", "The Ten Commandments", "Moses'' death"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'What happened when the people shouted and the priests blew the trumpets at Jericho?', 'Joshua 6:20', 'So the people shouted and the priests blew the trumpets. When the people heard the sound of the trumpet, the people shouted with a great shout, and the wall fell down flat, so that the people went up into the city, every man straight in front of him, and they took the city.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["The wall fell down flat", "The city gates opened peacefully", "Nothing happened", "The people were struck silent"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Joshua 6:25, whom did Joshua save alive?', 'Joshua 6:25', 'But Rahab the prostitute, her father''s household, and all that she had, Joshua saved alive. She lives in the middle of Israel to this day, because she hid the messengers whom Joshua sent to spy out Jericho.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Rahab and her father''s household", "The king of Jericho", "All the city''s soldiers", "The two spies'' own families"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'How old was Caleb when he asked Joshua for the hill country?', 'Joshua 14:10-12', '...Now, behold, I am eighty-five years old, today. As yet I am as strong today as I was in the day that Moses sent me... Now therefore give me this hill country, of which Yahweh spoke in that day...', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["eighty-five years old", "forty years old", "one hundred years old", "twenty years old"], "correct_index": 0}', false, 7),
  ((select id from w), 'sequence', 'Order these events of the entry into Canaan in the order they happen in the text.', 'Joshua 2:1; 3:16-17; 4:6-7; 6:20', 'Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, ''Go, view the land, including Jericho.''...; ...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho. The priests who bore the ark of Yahweh''s covenant stood firm on dry ground in the middle of the Jordan; and all Israel crossed over on dry ground, until all the nation had passed completely over the Jordan.; ...that this may be a sign among you, that when your children ask in the future, saying, What do you mean by these stones? then you shall tell them, Because the waters of the Jordan were cut off before the ark of Yahweh''s covenant. When it crossed over the Jordan, the waters of the Jordan were cut off. These stones shall be for a memorial to the children of Israel forever.; So the people shouted and the priests blew the trumpets. When the people heard the sound of the trumpet, the people shouted with a great shout, and the wall fell down flat, so that the people went up into the city, every man straight in front of him, and they took the city.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Joshua sends two spies to Jericho", "Israel crosses the Jordan on dry ground", "stones are set up as a memorial", "Israel marches around Jericho and the wall falls"], "correct_order": [0, 1, 2, 3]}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh give to Israel, according to Joshua 21:43-45?', 'Joshua 21:43-45', 'So Yahweh gave to Israel all the land which he swore to give to their fathers. They possessed it, and lived in it. Yahweh gave them rest all around, according to all that he swore to their fathers. Not a man of all their enemies stood before them. Yahweh delivered all their enemies into their hand. Nothing failed of any good thing which Yahweh had spoken to the house of Israel. All came to pass.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "So Yahweh gave to Israel all the ___ which he swore to give to their fathers.", "answer": "land"}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing place name from Joshua''s campaign summary.', 'Joshua 10:41', 'Joshua struck them from Kadesh Barnea even to Gaza, and all the country of Goshen, even to Gibeon. Joshua took all these kings and their land at one time because Yahweh, the God of Israel, fought for Israel.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Joshua struck them from Kadesh Barnea even to Gaza, and all the country of Goshen, even to ___.", "answer": "Gibeon"}', true, 10)
;

-- ===================== Joshua — HARD tier (10 items) =====================

with w as (select id from public.world where book_slug = 'joshua')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing place name from Israel''s crossing of the Jordan.', 'Joshua 3:16', '...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...the waters which came down from above stood, and rose up in one heap a great way off, at ___, the city that is beside Zarethan.", "answer": "Adam"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what had the Israelites come out of, according to Rahab?', 'Joshua 2:10', 'I know that Yahweh has given you the land, and that the fear of you has fallen upon us... we have heard how Yahweh dried up the water of the Red Sea before you, when you came out of Egypt...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...we have heard how Yahweh dried up the water of the Red Sea before you, when you came out of ___.", "answer": "Egypt"}', false, 2),
  ((select id from w), 'recall', 'According to Joshua 4:22, fill in the missing word describing how Israel crossed the Jordan.', 'Joshua 4:22', '...you shall let your children know, saying, Israel came over this Jordan on dry land... that all the peoples of the earth may know that Yahweh''s hand is mighty, and that you may fear Yahweh your God forever.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "According to Joshua 4:22: ...you shall let your children know, saying, Israel came over this Jordan on dry ___.", "answer": "land"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from Caleb''s claim about his strength.', 'Joshua 14:11', '...Now, behold, I am eighty-five years old, today. As yet I am as strong today as I was in the day that Moses sent me... Now therefore give me this hill country, of which Yahweh spoke in that day...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "As yet I am as ___ today as I was in the day that Moses sent me.", "answer": "strong"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word closing the description of the memorial stones.', 'Joshua 4:7', '...These stones shall be for a memorial to the children of Israel forever.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "These stones shall be for a memorial to the children of Israel ___.", "answer": "forever"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing number: how many times did Israel march around Jericho on the seventh day?', 'Joshua 6:4', '...Seven priests shall bear seven trumpets of rams'' horns before the ark. On the seventh day, you shall march around the city seven times, and the priests shall blow the trumpets...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "On the seventh day, you shall march around the city ___ times.", "answer": "seven"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what city did the messengers Rahab hid come to spy out?', 'Joshua 6:25', 'But Rahab the prostitute, her father''s household, and all that she had, Joshua saved alive. She lives in the middle of Israel to this day, because she hid the messengers whom Joshua sent to spy out Jericho.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...because she hid the messengers whom Joshua sent to spy out ___.", "answer": "Jericho"}', false, 7),
  ((select id from w), 'sequence', 'Order these events of the entry into Canaan in the order they happen in the text.', 'Joshua 2:1; 3:16-17; 4:6-7; 6:20', 'Joshua the son of Nun secretly sent two men out of Shittim as spies, saying, ''Go, view the land, including Jericho.''...; ...the waters which came down from above stood, and rose up in one heap a great way off, at Adam, the city that is beside Zarethan... Then the people passed over near Jericho. The priests who bore the ark of Yahweh''s covenant stood firm on dry ground in the middle of the Jordan; and all Israel crossed over on dry ground, until all the nation had passed completely over the Jordan.; ...that this may be a sign among you, that when your children ask in the future, saying, What do you mean by these stones? then you shall tell them, Because the waters of the Jordan were cut off before the ark of Yahweh''s covenant. When it crossed over the Jordan, the waters of the Jordan were cut off. These stones shall be for a memorial to the children of Israel forever.; So the people shouted and the priests blew the trumpets. When the people heard the sound of the trumpet, the people shouted with a great shout, and the wall fell down flat, so that the people went up into the city, every man straight in front of him, and they took the city.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["Joshua sends two spies to Jericho", "Israel crosses the Jordan on dry ground", "stones are set up as a memorial", "Israel marches around Jericho and the wall falls"], "correct_order": [0, 1, 2, 3]}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh give to Israel, according to Joshua 21:43-45?', 'Joshua 21:43-45', 'So Yahweh gave to Israel all the land which he swore to give to their fathers. They possessed it, and lived in it. Yahweh gave them rest all around, according to all that he swore to their fathers. Not a man of all their enemies stood before them. Yahweh delivered all their enemies into their hand. Nothing failed of any good thing which Yahweh had spoken to the house of Israel. All came to pass.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "So Yahweh gave to Israel all the ___ which he swore to give to their fathers.", "answer": "land"}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing place name from Joshua''s campaign summary.', 'Joshua 10:41', 'Joshua struck them from Kadesh Barnea even to Gaza, and all the country of Goshen, even to Gibeon. Joshua took all these kings and their land at one time because Yahweh, the God of Israel, fought for Israel.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Joshua struck them from Kadesh Barnea even to Gaza, and all the country of ___, even to Gibeon.", "answer": "Goshen"}', true, 10)
;

-- ===================== Judges — EASY tier (11 items) =====================

with w as (select id from public.world where book_slug = 'judges')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'Who did Yahweh raise up to save Israel from those who plundered them?', 'Judges 2:16', 'Yahweh raised up judges, who saved them out of the hand of those who plundered them.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["judges", "kings", "priests", "prophets"], "correct_index": 0}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word describing Deborah''s role.', 'Judges 4:4-5', 'Now Deborah, a prophetess, the wife of Lappidoth, judged Israel at that time. She lived under Deborah''s palm tree between Ramah and Bethel in the hill country of Ephraim; and the children of Israel came up to her for judgment.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Now Deborah, a prophetess, the wife of Lappidoth, ___ Israel at that time.", "answer": "judged"}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Judges 4:16, what happened to Sisera''s army when Yahweh gave Barak the victory?', 'Judges 4:14-16', 'Deborah said to Barak, ''Go; for this is the day in which Yahweh has delivered Sisera into your hand...'' Yahweh confused Sisera, all his chariots, and all his army, with the edge of the sword before Barak... all the army of Sisera fell by the edge of the sword. There was not a man left.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["The whole army fell by the edge of the sword; not a man was left", "They surrendered without a fight", "They fled and were never seen again", "Barak spared them all"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'What did Yahweh tell Gideon to do?', 'Judges 6:14-16', 'Yahweh looked at him, and said, ''Go in this your might, and save Israel from the hand of Midian. Haven''t I sent you?'' He said to him, ''O Lord, how shall I save Israel? Behold, my family is the poorest in Manasseh, and I am the least in my father''s house.'' Yahweh said to him, ''Surely I will be with you, and you shall strike the Midianites as one man.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Go in his might and save Israel from Midian", "Build an altar before doing anything else", "Gather ten thousand men immediately", "Flee to Egypt"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what did Gideon put on the threshing floor as a sign?', 'Judges 6:37', '...behold, I will put a fleece of wool on the threshing floor. If there is dew on the fleece only, and it is dry on all the ground, then I''ll know that you will save Israel by my hand, as you have spoken.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "...behold, I will put a fleece of ___ on the threshing floor.", "answer": "wool"}', false, 5),
  ((select id from w), 'multiple_choice', 'Why did Yahweh say Gideon''s army was too large?', 'Judges 7:2', 'The people who are with you are too many for me to give the Midianites into their hand, lest Israel brag against me, saying, ''My own hand has saved me.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["So that Israel could not boast the victory was by their own hand", "Because there wasn''t enough food for them", "Because the men were afraid", "Because Midian had a much bigger army"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to Judges 7:20, what did Gideon''s three hundred men shout during the attack on the Midianite camp?', 'Judges 7:20-21', '...they shouted, ''The sword of Yahweh and of Gideon!'' They each stood in his place around the camp, and all the army ran; and they shouted, and put them to flight.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["''The sword of Yahweh and of Gideon!''", "''Long live the king!''", "''Peace be with you''", "They shouted nothing"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Judges 21:25, what was true of Israel in those days?', 'Judges 21:25', 'In those days there was no king in Israel. Everyone did that which was right in his own eyes.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["There was no king in Israel, and everyone did what was right in his own eyes", "The judges had all died out", "The land was completely at peace", "The people had forgotten the law"], "correct_index": 0}', false, 8),
  ((select id from w), 'sequence', 'Put these steps of the judges'' cycle, as the narrator describes it, in the order they happen in the text.', 'Judges 2:11-19', 'Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.; Yahweh raised up judges, who saved them out of the hand of those who plundered them.; When Yahweh raised up judges for them, then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the judge... But when the judge was dead, they turned back, and dealt more corruptly than their fathers...', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Israel does evil and is handed over to raiders", "Yahweh raises up a judge who delivers them", "when the judge dies, the people fall back into the same pattern"], "correct_order": [0, 1, 2]}', true, 9),
  ((select id from w), 'multiple_choice', 'According to Judges 7:2, why did Yahweh tell Gideon to reduce his army?', 'Judges 7:2', 'The people who are with you are too many for me to give the Midianites into their hand, lest Israel brag against me, saying, ''My own hand has saved me.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["So that Israel could not claim credit for the victory itself", "Because there wasn''t enough food for them", "Because the men were afraid", "Because Midian had a much bigger army"], "correct_index": 0}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what did the Israelites do after each judge died?', 'Judges 2:19', 'When Yahweh raised up judges for them, then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the judge... But when the judge was dead, they turned back, and dealt more corruptly than their fathers...', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "...But when the judge was dead, they turned back, and dealt more ___ than their fathers...", "answer": "corruptly"}', true, 11)
;

-- ===================== Judges — HARD tier (11 items) =====================

with w as (select id from public.world where book_slug = 'judges')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: into whose hands did Yahweh deliver Israel, alongside the raiders?', 'Judges 2:14', 'Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their ___ all around.", "answer": "enemies"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word closing the description of the judges'' cycle.', 'Judges 2:18', 'When Yahweh raised up judges for them, then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the judge... But when the judge was dead, they turned back, and dealt more corruptly than their fathers...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the ___.", "answer": "judge"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing place name from the description of where Deborah judged Israel.', 'Judges 4:5', 'Now Deborah, a prophetess, the wife of Lappidoth, judged Israel at that time. She lived under Deborah''s palm tree between Ramah and Bethel in the hill country of Ephraim; and the children of Israel came up to her for judgment.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "She lived under Deborah''s palm tree between Ramah and ___ in the hill country of Ephraim.", "answer": "Bethel"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing river name from Deborah''s instruction to Barak.', 'Judges 4:7', '...Go and lead the way to Mount Tabor, and take with you ten thousand men of the children of Naphtali and of the children of Zebulun... I will draw to you, to the river Kishon, Sisera, the captain of Jabin''s army... and I will deliver him into your hand.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "I will draw to you, to the river ___, Sisera, the captain of Jabin''s army.", "answer": "Kishon"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what tribe did Gideon say his family was the poorest in?', 'Judges 6:15', '...He said to him, ''O Lord, how shall I save Israel? Behold, my family is the poorest in Manasseh, and I am the least in my father''s house.''...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Behold, my family is the poorest in ___, and I am the least in my father''s house.", "answer": "Manasseh"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word closing Gideon''s fleece request.', 'Judges 6:37', '...behold, I will put a fleece of wool on the threshing floor. If there is dew on the fleece only, and it is dry on all the ground, then I''ll know that you will save Israel by my hand, as you have spoken.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...then I''ll know that you will save Israel by my hand, as you have ___.", "answer": "spoken"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: where did the three hundred men stand during the attack?', 'Judges 7:21', '...they shouted, ''The sword of Yahweh and of Gideon!'' They each stood in his place around the camp, and all the army ran; and they shouted, and put them to flight.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "They each stood in his place around the ___, and all the army ran; and they shouted, and put them to flight.", "answer": "camp"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word closing the book of Judges.', 'Judges 21:25', 'In those days there was no king in Israel. Everyone did that which was right in his own eyes.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "In those days there was no king in Israel. Everyone did that which was right in his own ___.", "answer": "eyes"}', false, 8),
  ((select id from w), 'sequence', 'Put these steps of the judges'' cycle, as the narrator describes it, in the order they happen in the text.', 'Judges 2:11-19', 'Yahweh''s anger burned against Israel, and he delivered them into the hands of raiders who plundered them. He sold them into the hands of their enemies all around, so that they could no longer stand before their enemies.; Yahweh raised up judges, who saved them out of the hand of those who plundered them.; When Yahweh raised up judges for them, then Yahweh was with the judge, and saved them out of the hand of their enemies all the days of the judge... But when the judge was dead, they turned back, and dealt more corruptly than their fathers...', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["Israel does evil and is handed over to raiders", "Yahweh raises up a judge who delivers them", "when the judge dies, the people fall back into the same pattern"], "correct_order": [0, 1, 2]}', true, 9),
  ((select id from w), 'multiple_choice', 'According to Judges 7:2, why did Yahweh tell Gideon to reduce his army?', 'Judges 7:2', 'The people who are with you are too many for me to give the Midianites into their hand, lest Israel brag against me, saying, ''My own hand has saved me.''', 'WEB', 5, 'hard',
   '{"type": "multiple_choice", "options": ["So that Israel could not claim credit for the victory itself", "Because there wasn''t enough food for them", "Because the men were afraid", "Because Midian had a much bigger army"], "correct_index": 0}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word from Deborah''s declaration to Barak.', 'Judges 4:14', 'Deborah said to Barak, ''Go; for this is the day in which Yahweh has delivered Sisera into your hand. Hasn''t Yahweh gone out before you?''...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Deborah said to Barak, ''Go; for this is the day in which Yahweh has delivered Sisera into your ___. Hasn''t Yahweh gone out before you?''", "answer": "hand"}', true, 11)
;

-- ===================== Ruth — EASY tier (9 items) =====================

with w as (select id from public.world where book_slug = 'ruth')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'What did Ruth tell Naomi she would do?', 'Ruth 1:16', '...Don''t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Go where Naomi goes, and take Naomi''s people and God as her own", "Return to her mother''s house in Moab", "Stay behind while Naomi traveled on alone", "Ask Boaz to marry her at once"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Ruth 1:8-9, what did Naomi urge her two daughters-in-law to do?', 'Ruth 1:8-9', 'Naomi said to her two daughters-in-law, ''Go, return each of you to her mother''s house... May Yahweh grant you that you may find rest, each of you in the house of her husband.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Return each of them to her mother''s house", "Come with her to Bethlehem", "Glean in the fields of Bethlehem", "Marry Boaz"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'In whose field did Ruth happen to glean grain?', 'Ruth 2:2-3', 'Ruth the Moabitess said to Naomi, ''Let me now go to the field, and glean among the ears of grain after him in whose sight I find favor.''... she happened to come to the portion of the field belonging to Boaz, who was of the family of Elimelech.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Boaz''s field", "Elimelech''s field", "Naomi''s field", "Orpah''s field"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'What did Boaz tell Ruth he had heard about her?', 'Ruth 2:11-12', '...I have been told all about what you have done for your mother-in-law since the death of your husband... May Yahweh repay your work, and a full reward be given to you from Yahweh, the God of Israel, under whose wings you have come to take refuge.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["All she had done for her mother-in-law since her husband''s death", "That she was wealthy in Moab", "That she planned to return to Moab", "That she was Naomi''s servant"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'What did Ruth ask Boaz to do at the threshing floor?', 'Ruth 3:9', '...She answered, ''I am Ruth your servant. Therefore spread the corner of your garment over your servant; for you are a near kinsman.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Spread the corner of his garment over her, because he was a near kinsman", "Give her a place to sleep for the night", "Redeem the land on her behalf immediately", "Send her back to Naomi"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Ruth 4:21-22, who was Boaz''s son?', 'Ruth 4:21-22', '...and Salmon became the father of Boaz, and Boaz became the father of Obed, and Obed became the father of Jesse, and Jesse became the father of David.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Obed", "David", "Jesse", "Salmon"], "correct_index": 0}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz call the elders and people at the gate?', 'Ruth 4:9-10', 'Boaz said to the elders and to all the people, ''You are witnesses today, that I have bought all that was Elimelech''s, and all that was Chilion''s and Mahlon''s, from the hand of Naomi. Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife... You are witnesses today.''', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Boaz said to the elders and to all the people, ''You are ___ today...''", "answer": "witnesses"}', true, 7),
  ((select id from w), 'multiple_choice', 'According to Ruth 4:17, who was Obed''s grandson?', 'Ruth 4:17', 'The women, her neighbors, gave him a name, saying, ''A son is born to Naomi''. They named him Obed. He is the father of Jesse, the father of David.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["David", "Boaz", "Jesse", "Salmon"], "correct_index": 0}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word from Naomi''s question to Ruth about Boaz.', 'Ruth 3:1-2', 'Naomi her mother-in-law said to her, ''My daughter, shall I not seek rest for you, that it may be well with you? Now isn''t Boaz our kinsman, with whose maidens you were?''', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Now isn''t Boaz our ___, with whose maidens you were?", "answer": "kinsman"}', true, 9)
;

-- ===================== Ruth — HARD tier (9 items) =====================

with w as (select id from public.world where book_slug = 'ruth')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word from Ruth''s oath to Naomi.', 'Ruth 1:17', 'Where you die, I will die, and there I will be buried. May Yahweh do so to me, and more also, if anything but death parts you and me.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "May Yahweh do so to me, and more also, if anything but ___ parts you and me.", "answer": "death"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from Naomi''s blessing over her daughters-in-law.', 'Ruth 1:8-9', 'Naomi said to her two daughters-in-law, ''Go, return each of you to her mother''s house... May Yahweh grant you that you may find rest, each of you in the house of her husband.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "May Yahweh grant you that you may find ___, each of you in the house of her husband.", "answer": "rest"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing name: whose family was Boaz part of?', 'Ruth 2:2-3', 'Ruth the Moabitess said to Naomi, ''Let me now go to the field, and glean among the ears of grain after him in whose sight I find favor.''... she happened to come to the portion of the field belonging to Boaz, who was of the family of Elimelech.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...she happened to come to the portion of the field belonging to Boaz, who was of the family of ___.", "answer": "Elimelech"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz command the young men not to do to Ruth?', 'Ruth 2:8-9', 'Then Boaz said to Ruth, ''Listen, my daughter. Don''t go to glean in another field, and don''t go from here, but stay here close to my maidens... Haven''t I commanded the young men not to touch you?''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...Haven''t I commanded the young men not to ___ you?", "answer": "touch"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz tell Ruth not to be?', 'Ruth 3:11', 'Now, my daughter, don''t be afraid. I will do to you all that you say; for all the city of my people knows that you are a worthy woman.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Now, my daughter, don''t be ___. I will do to you all that you say; for all the city of my people knows that you are a worthy woman.", "answer": "afraid"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did the women say Obed''s name would be in Israel?', 'Ruth 4:13-14', 'So Boaz took Ruth and she became his wife... and she bore a son. The women said to Naomi, ''Blessed be Yahweh, who has not left you today without a near kinsman. Let his name be famous in Israel.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...Let his name be ___ in Israel.''", "answer": "famous"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what did Boaz call the elders and people at the gate?', 'Ruth 4:9-10', 'Boaz said to the elders and to all the people, ''You are witnesses today, that I have bought all that was Elimelech''s, and all that was Chilion''s and Mahlon''s, from the hand of Naomi. Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife... You are witnesses today.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Boaz said to the elders and to all the people, ''You are ___ today...''", "answer": "witnesses"}', true, 7),
  ((select id from w), 'multiple_choice', 'According to Ruth 4:17, who was Obed''s grandson?', 'Ruth 4:17', 'The women, her neighbors, gave him a name, saying, ''A son is born to Naomi''. They named him Obed. He is the father of Jesse, the father of David.', 'WEB', 5, 'hard',
   '{"type": "multiple_choice", "options": ["David", "Boaz", "Jesse", "Salmon"], "correct_index": 0}', true, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what had Ruth come to take under Yahweh''s wings?', 'Ruth 2:11-12', 'I have been told all about what you have done for your mother-in-law since the death of your husband... May Yahweh repay your work, and a full reward be given to you from Yahweh, the God of Israel, under whose wings you have come to take refuge.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...under whose wings you have come to take ___.", "answer": "refuge"}', true, 9)
;
