-- Gen2Rev challenge ingest: 1 Kings / 2 Kings / 1 Chronicles / 2 Chronicles
-- EASY and HARD difficulty tiers
-- (World 11 = 1 Kings, World 12 = 2 Kings, World 13 = 1 Chronicles, World 14 = 2 Chronicles)
--
-- Generated from the finalized, theologically-reviewed (approved-with-changes), verbatim-QA-passed
-- content briefs:
--   docs/content/1-kings-easy.md,       docs/content/1-kings-hard.md
--   docs/content/2-kings-easy.md,       docs/content/2-kings-hard.md
--   docs/content/1-chronicles-easy.md,  docs/content/1-chronicles-hard.md
--   docs/content/2-chronicles-easy.md,  docs/content/2-chronicles-hard.md
-- Review docs: docs/reviews/{book}-{tier}-review.md — all approved-with-changes, fixes applied
--   in the briefs themselves prior to this ingest.
-- QA docs: docs/qa/{book}-{tier}-verbatim-qa.md — all `pass`.
-- Schema/syntax template: docs/ingest/1-2-kings-1-2-chronicles.sql (the original medium-tier
--   ingest for these same four books) and docs/ingest/joshua-judges-ruth-tiers.sql (a clean,
--   already-applied easy/hard-tier example for a different book set).
--
-- book_slug values ('1-kings', '2-kings', '1-chronicles', '2-chronicles') confirmed directly
-- against the `where book_slug = '...'` clauses in docs/ingest/1-2-kings-1-2-chronicles.sql.
--
-- difficulty_rank is flat per tier per the ingestion spec: 1 for every easy-tier row, 5 for every
-- hard-tier row (not the varying per-item ranks used in the medium-tier ingest).
--
-- Several boss items in the easy/hard briefs are explicitly "reused verbatim from medium" and, in
-- a few cases (the two-women sequence, the three-quotation order, the five/four-scene order, the
-- four-quotation order), the brief text itself points back at the already-shipped medium-tier SQL
-- (docs/ingest/1-2-kings-1-2-chronicles.sql) as the source of record for the exact wording rather
-- than re-spelling it. Those rows below transcribe that already-approved medium content directly,
-- per the brief's own instruction, rather than inventing new option/item text.
--
-- Content-safety exclusions carried forward and reconfirmed absent from every row below: 1 Kings
-- 18:40 (killing of Baal's prophets); the 1 Kings 3:16 "prostitutes" detail (kept as narrative-
-- summary only, "two women" framing, never displayed as verse text); 2 Kings 25:6-7 (Zedekiah's
-- sons killed, his eyes put out); 2 Kings 6:26-29 (cannibalism during a siege); 2 Kings 2:23-24
-- (children mauled by bears); 2 Chronicles 7:14 (the "if my people" civil-religion verse);
-- 2 Chronicles 36:17 (graphic conquest detail — 36:16 is used and stops immediately short of it,
-- per the hard-tier brief's own note that the boundary is deliberate). 2 Chronicles 29:10 uses the
-- confirmed-correct WEB reading "fierce anger" (not "fierce wrath"), per the hard-tier brief's
-- four-source cross-check. 1 Chronicles deliberately stays at 6 items per tier (4 regular + 2
-- boss), matching the medium tier's own deliberately-thin count — not padded.
--
-- *** SQL STRING ESCAPING — READ BEFORE EDITING THIS FILE ***
-- Every apostrophe / single-quote character anywhere inside a SQL single-quoted string literal —
-- including inside a JSON string that is itself embedded in a SQL string literal — must be escaped
-- as EXACTLY TWO single quotes (''), never four (''''). This applies uniformly to plain
-- prompt/verse_text fields AND to the JSON text inside answer_key, and applies to EVERY apostrophe
-- character, whether it is a contraction (e.g. "Yahweh''s", "don''t") or a dialogue quotation mark
-- (WEB renders spoken dialogue with single quotes, e.g. "and God said, ''Ask for what I should give
-- you.''"). JSON itself needs no special handling for apostrophes — JSON strings are double-quoted,
-- so a literal ' inside a JSON string value is just a plain character; the ONLY escaping layer that
-- applies anywhere in this file is the single outer SQL-string '' escaping, applied once. A real
-- quadrupled-quote bug of exactly this kind shipped to production earlier today in a sibling file
-- (docs/ingest/numbers-deuteronomy-tiers.sql, since fixed) — do not reintroduce it here. None of the
-- verse text in this file contains a literal double-quote character, so no \" JSON-escaping is
-- needed anywhere below (checked explicitly during drafting).


-- ===================== 1 Kings — EASY tier (16 items: 12 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '1-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'What did God say to Solomon in the dream at Gibeon?', '1 Kings 3:5', 'In Gibeon, Yahweh appeared to Solomon in a dream by night; and God said, ''Ask for what I should give you.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["that Solomon should ask for what he wanted God to give him", "that Solomon should build him a house", "that Solomon should choose a wife", "that Solomon should fight his enemies"], "correct_index": 0}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s request to Yahweh at Gibeon.', '1 Kings 3:9', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Give your servant therefore an ___ heart to judge your people.", "answer": "understanding"}', false, 2),
  ((select id from w), 'multiple_choice', 'What did God give Solomon because he asked for wisdom instead of long life or riches?', '1 Kings 3:12', 'I have given you a wise and understanding heart, so that there has been no one like you before you, and after you none will arise like you.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a wise and understanding heart", "great wealth", "a large army", "many sons"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'What did the king order?', '1 Kings 3:25', 'The king said, ''Divide the living child in two, and give half to the one, and half to the other.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Divide the living child in two", "Ask them to swear an oath", "Send for witnesses", "Give the child to the older woman"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'What did the child''s true mother beg the king to do?', '1 Kings 3:26', 'Then the woman whose the living child was spoke to the king, for her heart yearned over her son, and she said, ''Oh, my lord, give her the living child, and in no way kill him!''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Give the child to the other woman rather than kill him", "Divide the child as ordered", "Take the child herself", "Punish the other woman"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'What filled Yahweh''s house so that the priests could not continue ministering?', '1 Kings 8:10-11', 'It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled Yahweh''s house.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["A cloud", "Smoke from a fire", "Music", "A crowd of people"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 6:7, what sound was never heard in the house while the temple was under construction?', '1 Kings 6:7', 'The house, when it was under construction, was built of stone prepared at the quarry; and no hammer or ax or any tool of iron was heard in the house while it was under construction.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a hammer, ax, or iron tool", "singing", "trumpets", "footsteps"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'In his temple prayer, what did Solomon say there is none like, in heaven or on earth?', '1 Kings 8:23', 'Yahweh, the God of Israel, there is no God like you, in heaven above, or on earth beneath; who keeps covenant and loving kindness with your servants who walk before you with all their heart;', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["God", "the ark", "the temple", "the priesthood"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'What did the northern tribes ask Rehoboam to do?', '1 Kings 12:4', 'Your father made our yoke difficult. Now therefore make the hard service of your father, and his heavy yoke which he put on us, lighter, and we will serve you.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Lighten the heavy service his father had placed on them", "Build them a new temple", "Lower their taxes to zero", "Make Jeroboam king right away"], "correct_index": 0}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word from Rehoboam''s harsh reply to the northern tribes.', '1 Kings 12:14', 'My father made your yoke heavy, but I will add to your yoke.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "My father made your yoke heavy, but I will ___ to your yoke.", "answer": "add"}', false, 10),
  ((select id from w), 'multiple_choice', 'What did Elijah ask the people at Mount Carmel?', '1 Kings 18:21', 'Elijah came near to all the people, and said, ''How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.'' The people didn''t say a word.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["how long they would waver between the two sides", "who built the altar", "where their God was", "why they had forsaken Yahweh"], "correct_index": 0}', false, 11),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 18:22, how many prophets did Baal have at the contest?', '1 Kings 18:22', 'I, even I only, am left as a prophet of Yahweh; but Baal''s prophets are four hundred fifty men.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["450", "50", "100", "12"], "correct_index": 0}', false, 12),
  ((select id from w), 'sequence', 'Put these four beats of the judgment of the two women in the order they happen in the text.', '1 Kings 3:16; 3:24; 3:26; 3:27-28', 'The king said, ''Get me a sword.'' So they brought a sword before the king.; Then the woman whose the living child was spoke to the king, for her heart yearned over her son, and she said, ''Oh, my lord, give her the living child, and in no way kill him!''; Then the king answered, ''Give the first woman the living child, and definitely do not kill him. She is his mother.'' All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of God was in him to do justice.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["The women are brought before the king", "The king calls for a sword", "The child''s true mother begs for his life", "The king gives the child to his true mother, and Israel fears him"], "correct_order": [0, 1, 2, 3]}', true, 13),
  ((select id from w), 'sequence', 'Put these three quotations from 1 Kings in the order they occur and match each to its reference.', '1 Kings 3:9; 12:16; 18:21', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?; What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.; How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["1 Kings 3:9 — Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?", "1 Kings 12:16 — What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.", "1 Kings 18:21 — How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him."], "correct_order": [0, 1, 2]}', true, 14),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 12:16, what did the northern tribes say when Rehoboam refused their request?', '1 Kings 12:16', 'When all Israel saw that the king didn''t listen to them, the people answered the king, saying, ''What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.'' So Israel departed to their tents.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["''What portion have we in David? ... To your tents, Israel!''", "''We will serve you forever, our king.''", "''Let us make Rehoboam king over all Israel.''", "''We shall return to Egypt.''"], "correct_index": 0}', true, 15),
  ((select id from w), 'sequence', 'Put these four events of 1 Kings in the order they happen in the book.', '1 Kings 3:5-14; 6, 8; 12; 18:20-39', 'In Gibeon, Yahweh appeared to Solomon in a dream by night; and God said, ''Ask for what I should give you.''; It came to pass, when the priests had come out of the holy place, that the cloud filled Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled Yahweh''s house.; Your father made our yoke difficult. Now therefore make the hard service of your father, and his heavy yoke which he put on us, lighter, and we will serve you.; Elijah came near to all the people, and said, ''How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.'' The people didn''t say a word.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Solomon asks for wisdom at Gibeon (1 Kings 3:5-14)", "Solomon dedicates the temple in Jerusalem (1 Kings 6, 8)", "The kingdom splits under Rehoboam (1 Kings 12)", "Yahweh answers Elijah by fire on Mount Carmel (1 Kings 18:20-39)"], "correct_order": [0, 1, 2, 3]}', true, 16)
;

-- ===================== 1 Kings — HARD tier (16 items: 12 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '1-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word from Yahweh''s response to Solomon''s request.', '1 Kings 3:11', 'Because you have asked this thing, and have not asked for yourself long life, nor have you asked for riches for yourself, nor have you asked for the life of your enemies, but have asked for yourself understanding to discern justice,', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Because you have asked this thing, and have not asked for yourself long life, nor have you asked for riches for yourself, nor have you asked for the life of your enemies, but have asked for yourself understanding to discern ___.", "answer": "justice"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from Yahweh''s promise of unasked-for blessings to Solomon.', '1 Kings 3:13', 'I have also given you that which you have not asked, both riches and honor, so that there will not be any among the kings like you for all your days.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "I have also given you that which you have not asked, both ___ and honor.", "answer": "riches"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word from Yahweh''s conditional promise to Solomon.', '1 Kings 3:14', 'If you will walk in my ways, to keep my statutes and my commandments, as your father David walked, then I will lengthen your days.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "If you will walk in my ways... then I will ___ your days.", "answer": "lengthen"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what the king asked to be brought to him.', '1 Kings 3:24', 'The king said, ''Get me a sword.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "The king said, ''Get me a ___.''", "answer": "sword"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word describing the true mother''s reaction.', '1 Kings 3:26', '...for her heart yearned over her son...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...for her heart ___ over her son...", "answer": "yearned"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: whose wisdom Israel recognized in the king''s judgment.', '1 Kings 3:28', 'All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of God was in him to do justice.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of ___ was in him to do justice.", "answer": "God"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word from the chronology of when Solomon began building the temple.', '1 Kings 6:1', 'In the four hundred and eightieth year after the children of Israel had come out of the land of Egypt, in the fourth year of Solomon''s reign over Israel, in the month Ziv, which is the second month, he began to build Yahweh''s house.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "In the four hundred and ___ year after the children of Israel had come out of the land of Egypt... he began to build Yahweh''s house.", "answer": "eightieth"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s dedication prayer, on whether God can be contained.', '1 Kings 8:27', 'But will God in very deed dwell on the earth? Behold, heaven and the heaven of heavens can''t contain you; how much less this house that I have built!', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...heaven and the heaven of heavens can''t ___ you; how much less this house that I have built!", "answer": "contain"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word from Solomon''s prayer about Yahweh''s name at the temple.', '1 Kings 8:29', 'that your eyes may be open toward this house night and day, even toward the place of which you have said, ''My name shall be there;'' to listen to the prayer which your servant prays toward this place.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...even toward the place of which you have said, ''My name shall be ___;''...", "answer": "there"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: whose counsel Rehoboam took instead of the old men''s.', '1 Kings 12:8', 'But he abandoned the counsel of the old men which they had given him, and took counsel with the young men who had grown up with him, who stood before him.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "But he abandoned the counsel of the old men... and took counsel with the ___ men who had grown up with him.", "answer": "young"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word closing the account of Israel''s rebellion against David''s house.', '1 Kings 12:19', 'So Israel rebelled against David''s house to this day.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "So Israel rebelled against David''s house to this ___.", "answer": "day"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what the prophets of Baal never received in answer to their cries.', '1 Kings 18:26', 'They took the bull which was given them, and they dressed it, and called on the name of Baal from morning even until noon, saying, ''Baal, hear us!'' But there was no voice, and nobody answered.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...called on the name of Baal from morning even until noon, saying, ''Baal, hear us!'' But there was no ___, and nobody answered.", "answer": "voice"}', false, 12),
  ((select id from w), 'sequence', 'Put these four beats of the judgment of the two women in the order they happen in the text.', '1 Kings 3:16; 3:24; 3:26; 3:27-28', 'The king said, ''Get me a sword.'' So they brought a sword before the king.; Then the woman whose the living child was spoke to the king, for her heart yearned over her son, and she said, ''Oh, my lord, give her the living child, and in no way kill him!''; Then the king answered, ''Give the first woman the living child, and definitely do not kill him. She is his mother.'' All Israel heard of the judgment which the king had judged; and they feared the king, for they saw that the wisdom of God was in him to do justice.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["The women are brought before the king", "The king calls for a sword", "The child''s true mother begs for his life", "The king gives the child to his true mother, and Israel fears him"], "correct_order": [0, 1, 2, 3]}', true, 13),
  ((select id from w), 'sequence', 'Put these three quotations from 1 Kings in the order they occur and match each to its reference.', '1 Kings 3:9; 12:16; 18:21', 'Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?; What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.; How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["1 Kings 3:9 — Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?", "1 Kings 12:16 — What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.", "1 Kings 18:21 — How long will you waver between the two sides? If Yahweh is God, follow him; but if Baal, then follow him."], "correct_order": [0, 1, 2]}', true, 14),
  ((select id from w), 'multiple_choice', 'According to 1 Kings 12:16, what did the northern tribes say when Rehoboam refused their request?', '1 Kings 12:16', 'When all Israel saw that the king didn''t listen to them, the people answered the king, saying, ''What portion have we in David? We don''t have an inheritance in the son of Jesse. To your tents, Israel! Now see to your own house, David.'' So Israel departed to their tents.', 'WEB', 5, 'hard',
   '{"type": "multiple_choice", "options": ["''What portion have we in David? ... To your tents, Israel!''", "''We will serve you forever, our king.''", "''Let us make Rehoboam king over all Israel.''", "''We shall return to Egypt.''"], "correct_index": 0}', true, 15),
  ((select id from w), 'recall', 'Fill in the missing word from Elijah''s prayer for the people''s hearts to be turned back.', '1 Kings 18:37', 'Hear me, Yahweh, hear me, that this people may know that you, Yahweh, are God, and that you have turned their heart back again.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Hear me, Yahweh, hear me, that this people may know that you, Yahweh, are ___, and that you have turned their heart back again.", "answer": "God"}', true, 16)
;

-- ===================== 2 Kings — EASY tier (16 items: 12 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '2-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'What did Elisha ask for before Elijah was taken from him?', '2 Kings 2:9', '...''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a double portion of his spirit", "gold and silver", "a place in heaven", "his mantle"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'What appeared and separated Elijah from Elisha?', '2 Kings 2:11', 'As they continued on and talked, behold, a chariot of fire and horses of fire separated them; and Elijah went up by a whirlwind into heaven.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a chariot of fire and horses of fire", "a great wind", "an earthquake", "a bright cloud"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'What did the other prophets say when they saw Elisha?', '2 Kings 2:15', 'When the sons of the prophets who were at Jericho facing him saw him, they said, ''The spirit of Elijah rests on Elisha.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["''The spirit of Elijah rests on Elisha''", "''Elijah has returned''", "''Elisha is now king''", "''The Lord has abandoned us''"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'What did the king of Assyria do to Samaria?', '2 Kings 17:5-6', '...The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried Israel away to Assyria...', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Besieged it three years, then captured it and carried Israel away", "Burned it immediately", "Made peace with it", "Gave it back to Israel"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 17:23, where was Israel carried away to?', '2 Kings 17:23', '...Yahweh removed Israel out of his sight, as he said by all his servants the prophets. So Israel was carried away out of their own land to Assyria to this day.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Assyria", "Babylon", "Egypt", "Persia"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 19:19, what did Hezekiah ask Yahweh to do?', '2 Kings 19:19', 'Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Save Judah, so all kingdoms would know Yahweh alone is God", "Send more soldiers", "Destroy Assyria''s crops", "Make Judah wealthy"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 18:13, who invaded Judah''s fortified cities in Hezekiah''s fourteenth year?', '2 Kings 18:13', 'Now in the fourteenth year of King Hezekiah, Sennacherib king of Assyria came up against all the fortified cities of Judah and took them.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Sennacherib king of Assyria", "Nebuchadnezzar king of Babylon", "Pharaoh king of Egypt", "Cyrus king of Persia"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 19:35-36, what happened to the Assyrian army that night?', '2 Kings 19:35-36', 'That night, Yahweh''s angel went out and struck one hundred eighty-five thousand in the camp of the Assyrians... So Sennacherib king of Assyria departed, went home, and lived at Nineveh.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Yahweh''s angel struck them down, and Sennacherib withdrew", "They surrendered to Hezekiah", "They were defeated in battle by Judah''s army", "They retreated without incident"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'What did Hilkiah find in Yahweh''s house?', '2 Kings 22:8', 'Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["The book of the law", "A golden ark", "A hidden treasure", "An ancient altar"], "correct_index": 0}', false, 9),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 22:13, why did Josiah send to inquire of Yahweh?', '2 Kings 22:13', 'Go inquire of Yahweh for me, and for the people, and for all Judah, concerning the words of this book that is found; for great is Yahweh''s wrath that is kindled against us, because our fathers have not listened to the words of this book, to do according to all that which is written concerning us.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Because Yahweh''s wrath was kindled against them, since their fathers had not obeyed the book''s words", "Because he wanted to know if he would win a war", "Because the temple needed more repairs", "Because Hilkiah asked him to"], "correct_index": 0}', false, 10),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 25:9, what did Nebuzaradan burn in Jerusalem?', '2 Kings 25:9', 'He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem. He burned every great house with fire.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Yahweh''s house, the king''s house, and all the great houses", "The city gates", "The royal archives", "Nothing"], "correct_index": 0}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what the Chaldean army broke down around Jerusalem.', '2 Kings 25:10', 'All the army of the Chaldeans, who were with the captain of the guard, broke down the walls around Jerusalem.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "All the army of the Chaldeans... broke down the walls around ___.", "answer": "Jerusalem"}', false, 12),
  ((select id from w), 'sequence', 'Put these five scenes of 2 Kings in the order they happen in the book.', '2 Kings 2:11; 17:5-6; 19:19; 22:8; 25:8-9', 'As they continued on and talked, behold, a chariot of fire and horses of fire separated them; and Elijah went up by a whirlwind into heaven.; The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried Israel away to Assyria.; Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.; Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.; Nebuzaradan the captain of the guard, a servant of the king of Babylon, came to Jerusalem. He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Elijah is taken up in a whirlwind and Elisha succeeds him as prophet (2 Kings 2)", "The northern kingdom, Israel, falls to Assyria after persistent idolatry (2 Kings 17)", "Hezekiah prays in the temple during Assyria''s siege of Jerusalem, and the siege ends (2 Kings 18-19)", "Josiah''s workers rediscover the book of the law, and Josiah renews the covenant (2 Kings 22-23)", "Babylon conquers Jerusalem, burns the temple, and carries the people into exile (2 Kings 25)"], "correct_order": [0, 1, 2, 3, 4]}', true, 13),
  ((select id from w), 'sequence', 'Given these three quotations from 2 Kings, place them in the order they occur and match each to its reference.', '2 Kings 2:9; 19:19; 22:8', '...''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''; Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.; Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["2 Kings 2:9 — ...''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''", "2 Kings 19:19 — Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.", "2 Kings 22:8 — Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it."], "correct_order": [0, 1, 2]}', true, 14),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 22:11, what did Josiah do when he heard the words of the book of the law?', '2 Kings 22:11', 'When the king had heard the words of the book of the law, he tore his clothes.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["He tore his clothes", "He ignored the scroll", "He ordered a feast", "He rebuilt the temple immediately"], "correct_index": 0}', true, 15),
  ((select id from w), 'multiple_choice', 'What did Elisha do with Elijah''s fallen mantle at the Jordan?', '2 Kings 2:14', 'He took Elijah''s mantle that fell from him, and struck the waters, and said, ''Where is Yahweh, the God of Elijah?'' When he also had struck the waters, they were divided apart, and Elisha went over.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Struck the water with it, and it parted so he could cross", "Wore it and disappeared", "Buried it", "Gave it to the sons of the prophets"], "correct_index": 0}', true, 16)
;

-- ===================== 2 Kings — HARD tier (16 items: 12 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '2-kings')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word from Elijah''s response to Elisha''s request.', '2 Kings 2:10', 'He said, ''You have asked a hard thing. If you see me when I am taken from you, it will be so for you; but if not, it will not be so.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "He said, ''You have asked a ___ thing. If you see me when I am taken from you, it will be so for you...''", "answer": "hard"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from Elisha''s cry as Elijah was taken up.', '2 Kings 2:12', 'Elisha saw it, and he cried, ''My father, my father, the chariots of Israel and its horsemen!'' He saw him no more...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Elisha saw it, and he cried, ''My father, my father, the chariots of ___ and its horsemen!''", "answer": "Israel"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what Elisha took up after Elijah was taken from him.', '2 Kings 2:13', 'He also took up Elijah''s mantle that fell from him, and went back and stood by the bank of the Jordan.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "He also took up Elijah''s ___ that fell from him, and went back and stood by the bank of the Jordan.", "answer": "mantle"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: which tribe alone was left, per 2 Kings 17:18.', '2 Kings 17:18', 'Therefore Yahweh was very angry with Israel, and removed them out of his sight. There was none left but the tribe of Judah only.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...There was none left but the tribe of ___ only.", "answer": "Judah"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what the children of Israel had done against Yahweh, per 2 Kings 17:7.', '2 Kings 17:7', 'It was so because the children of Israel had sinned against Yahweh their God, who brought them up out of the land of Egypt from under the hand of Pharaoh king of Egypt, and had feared other gods.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "It was so because the children of Israel had ___ against Yahweh their God, who brought them up out of the land of Egypt...", "answer": "sinned"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word from Hezekiah''s prayer describing Yahweh''s throne.', '2 Kings 19:15', 'Yahweh, the God of Israel, who are enthroned above the cherubim, you are the God, even you alone, of all the kingdoms of the earth.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Yahweh, the God of Israel, who are enthroned above the ___, you are the God, even you alone, of all the kingdoms of the earth.", "answer": "cherubim"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what Hezekiah covered himself with when he heard the Assyrian threat.', '2 Kings 19:1', 'When King Hezekiah heard it, he tore his clothes, covered himself with sackcloth, and went into Yahweh''s house.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "When King Hezekiah heard it, he tore his clothes, covered himself with ___, and went into Yahweh''s house.", "answer": "sackcloth"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what Hezekiah did with the letter before Yahweh.', '2 Kings 19:14', 'Hezekiah received the letter from the hand of the messengers and read it. Then Hezekiah went up to Yahweh''s house, and spread it before Yahweh.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Hezekiah received the letter... and read it. Then Hezekiah went up to Yahweh''s house, and ___ it before Yahweh.", "answer": "spread"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word describing Josiah''s heart, per Yahweh''s message through Huldah.', '2 Kings 22:19', 'because your heart was tender, and you humbled yourself before Yahweh when you heard what I spoke against this place and against its inhabitants, that they should become a desolation and a curse, and have torn your clothes and wept before me, I also have heard you,'' says Yahweh.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...because your heart was ___, and you humbled yourself before Yahweh when you heard what I spoke against this place...", "answer": "tender"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word from Josiah''s covenant renewal before Yahweh.', '2 Kings 23:3', 'The king stood by the pillar and made a covenant before Yahweh to walk after Yahweh and to keep his commandments, his testimonies, and his statutes with all his heart and all his soul, to confirm the words of this covenant that were written in this book; and all the people agreed to the covenant.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...to walk after Yahweh and to keep his commandments, his testimonies, and his statutes with all his heart and all his ___...", "answer": "soul"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: in which year of Zedekiah''s reign the siege of Jerusalem began, per 2 Kings 25:1.', '2 Kings 25:1', 'In the ninth year of his reign, in the tenth month, in the tenth day of the month, Nebuchadnezzar king of Babylon came, he and all his army, against Jerusalem, and encamped against it; and they built forts against it around it.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "In the ___ year of his reign, in the tenth month, in the tenth day of the month, Nebuchadnezzar king of Babylon came... against Jerusalem.", "answer": "ninth"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: how long Jehoiachin ate bread before the king of Babylon, per 2 Kings 25:29.', '2 Kings 25:29', '...and changed his prison garments. Jehoiachin ate bread before him continually all the days of his life.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...and changed his prison garments. Jehoiachin ate bread before him continually all the days of his ___.", "answer": "life"}', false, 12),
  ((select id from w), 'sequence', 'Put these five scenes of 2 Kings in the order they happen in the book.', '2 Kings 2:11; 17:5-6; 19:19; 22:8; 25:8-9', 'As they continued on and talked, behold, a chariot of fire and horses of fire separated them; and Elijah went up by a whirlwind into heaven.; The king of Assyria came up throughout all the land, went up to Samaria, and besieged it three years. In the ninth year of Hoshea the king of Assyria took Samaria and carried Israel away to Assyria.; Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.; Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.; Nebuzaradan the captain of the guard, a servant of the king of Babylon, came to Jerusalem. He burned Yahweh''s house, the king''s house, and all the houses of Jerusalem.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["Elijah is taken up in a whirlwind and Elisha succeeds him as prophet (2 Kings 2)", "The northern kingdom, Israel, falls to Assyria after persistent idolatry (2 Kings 17)", "Hezekiah prays in the temple during Assyria''s siege of Jerusalem, and the siege ends (2 Kings 18-19)", "Josiah''s workers rediscover the book of the law, and Josiah renews the covenant (2 Kings 22-23)", "Babylon conquers Jerusalem, burns the temple, and carries the people into exile (2 Kings 25)"], "correct_order": [0, 1, 2, 3, 4]}', true, 13),
  ((select id from w), 'sequence', 'Given these three quotations from 2 Kings, place them in the order they occur and match each to its reference.', '2 Kings 2:9; 19:19; 22:8', '...''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''; Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.; Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["2 Kings 2:9 — ...''Ask what I shall do for you, before I am taken from you.'' Elisha said, ''Please let a double portion of your spirit be on me.''", "2 Kings 19:19 — Now therefore, Yahweh our God, save us, I beg you, out of his hand, that all the kingdoms of the earth may know that you, Yahweh, are God alone.", "2 Kings 22:8 — Hilkiah the high priest said to Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' Hilkiah delivered the book to Shaphan, and he read it."], "correct_order": [0, 1, 2]}', true, 14),
  ((select id from w), 'multiple_choice', 'According to 2 Kings 22:11, what did Josiah do when he heard the words of the book of the law?', '2 Kings 22:11', 'When the king had heard the words of the book of the law, he tore his clothes.', 'WEB', 5, 'hard',
   '{"type": "multiple_choice", "options": ["He tore his clothes", "He ignored the scroll", "He ordered a feast", "He rebuilt the temple immediately"], "correct_index": 0}', true, 15),
  ((select id from w), 'recall', 'Fill in the missing word: what Nebuzaradan did to the rest of the people left in the city, per 2 Kings 25:11.', '2 Kings 25:11', 'Nebuzaradan the captain of the guard carried away captive the rest of the people who were left in the city and those who had deserted to the king of Babylon—all the rest of the multitude.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Nebuzaradan the captain of the guard carried away ___ the rest of the people who were left in the city...", "answer": "captive"}', true, 16)
;

-- ===================== 1 Chronicles — EASY tier (6 items: 4 regular + 2 boss) =====================
-- Deliberately thin — matches the medium tier's own deliberately-thin count per
-- docs/CANON_STRUCTURE.md §4. Not padded to resemble other books' tiers.

with w as (select id from public.world where book_slug = '1-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing name: the third name in 1 Chronicles'' opening genealogy.', '1 Chronicles 1:1', 'Adam, Seth, Enosh,', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Adam, Seth, ___,", "answer": "Enosh"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to 1 Chronicles 21:1, what was David moved to do?', '1 Chronicles 21:1', 'Satan stood up against Israel, and moved David to take a census of Israel.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Take a census of Israel", "Attack the Philistines", "Build an altar", "Flee to Ornan''s threshing floor"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'According to 1 Chronicles 21:26, how did Yahweh answer David after he built the altar and offered sacrifices?', '1 Chronicles 21:26', 'David built an altar to Yahweh there, and offered burnt offerings and peace offerings, and called on Yahweh; and he answered him from the sky by fire on the altar of burnt offering.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["By fire from the sky on the altar", "By a voice from heaven", "By sending rain", "By a vision in a dream"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'According to 1 Chronicles 28:20, what did David tell Solomon to be, in charging him to build the temple?', '1 Chronicles 28:20', 'Be strong and courageous, and do it. Don''t be afraid, nor be dismayed, for Yahweh God, even my God, is with you.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Strong and courageous", "Wealthy and wise", "Patient and humble", "Famous and powerful"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: the stated reason Yahweh''s word gave David for why he could not build the temple.', '1 Chronicles 22:7-8', 'As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my sight.''', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my ___.''", "answer": "sight"}', true, 5),
  ((select id from w), 'multiple_choice', 'According to 1 Chronicles 22:14, what did David prepare in vast quantities for the temple Solomon would build?', '1 Chronicles 22:14', 'In my affliction I have prepared for Yahweh''s house one hundred thousand talents of gold, one million talents of silver, and bronze and iron without weight... I have also prepared timber and stone.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Gold, silver, bronze, iron, timber, and stone", "Gold and incense only", "Silver and cedar only", "Bronze and linen"], "correct_index": 0}', true, 6)
;

-- ===================== 1 Chronicles — HARD tier (6 items: 4 regular + 2 boss) =====================
-- Same thinness rationale as easy tier above.

with w as (select id from public.world where book_slug = '1-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing name: the first name in 1 Chronicles'' opening genealogy.', '1 Chronicles 1:1', 'Adam, Seth, Enosh,', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "___, Seth, Enosh,", "answer": "Adam"}', false, 1),
  ((select id from w), 'recall', 'According to 1 Chronicles 21:18, fill in the missing name: on the threshing floor of ___ the Jebusite Yahweh''s angel commanded that an altar be raised.', '1 Chronicles 21:18', 'Yahweh''s angel commanded Gad to tell David that David should go up and raise an altar to Yahweh on the threshing floor of Ornan the Jebusite.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Yahweh''s angel commanded Gad to tell David that David should go up and raise an altar to Yahweh on the threshing floor of ___ the Jebusite.", "answer": "Ornan"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word, per 1 Chronicles 22:5: besides young, what did David say Solomon was?', '1 Chronicles 22:5', 'Solomon my son is young and tender, and the house that is to be built for Yahweh must be exceedingly magnificent... I will therefore make preparation for it.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Solomon my son is young and ___, and the house that is to be built for Yahweh must be exceedingly magnificent... I will therefore make preparation for it.", "answer": "tender"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word, per 1 Chronicles 29:14: David''s prayer says all things come from Yahweh, and ''we have given you of your ___.''', '1 Chronicles 29:14', 'But who am I, and what is my people, that we should be able to offer so willingly as this? For all things come from you, and we have given you of your own.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "But who am I, and what is my people, that we should be able to offer so willingly as this? For all things come from you, and we have given you of your ___.", "answer": "own"}', false, 4),
  ((select id from w), 'sequence', 'Given these four quotations from 1 Chronicles, place them in the order they occur and match each to its reference.', '1 Chronicles 22:7-8; 22:14; 28:9-10; 29:14', 'As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my sight.''; In my affliction I have prepared for Yahweh''s house one hundred thousand talents of gold, one million talents of silver, and bronze and iron without weight... I have also prepared timber and stone.; You, Solomon my son, know the God of your father, and serve him with a perfect heart and with a willing mind... Take heed now, for Yahweh has chosen you to build a house for the sanctuary. Be strong, and do it.; But who am I, and what is my people, that we should be able to offer so willingly as this? For all things come from you, and we have given you of your own.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["1 Chronicles 22:7-8 — As for me, it was in my heart to build a house to the name of Yahweh my God. But Yahweh''s word came to me, saying, ''You have shed blood abundantly and have made great wars. You shall not build a house to my name, because you have shed much blood on the earth in my sight.''", "1 Chronicles 22:14 — In my affliction I have prepared for Yahweh''s house one hundred thousand talents of gold, one million talents of silver, and bronze and iron without weight... I have also prepared timber and stone.", "1 Chronicles 28:9-10 — You, Solomon my son, know the God of your father, and serve him with a perfect heart and with a willing mind... Take heed now, for Yahweh has chosen you to build a house for the sanctuary. Be strong, and do it.", "1 Chronicles 29:14 — But who am I, and what is my people, that we should be able to offer so willingly as this? For all things come from you, and we have given you of your own."], "correct_order": [0, 1, 2, 3]}', true, 5),
  ((select id from w), 'recall', 'Fill in the missing word, per 1 Chronicles 28:9-10: David charges Solomon to serve Yahweh with a perfect heart and a willing ___.', '1 Chronicles 28:9-10', 'You, Solomon my son, know the God of your father, and serve him with a perfect heart and with a willing mind... Take heed now, for Yahweh has chosen you to build a house for the sanctuary. Be strong, and do it.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "You, Solomon my son, know the God of your father, and serve him with a perfect heart and with a willing ___... Take heed now, for Yahweh has chosen you to build a house for the sanctuary. Be strong, and do it.", "answer": "mind"}', true, 6)
;

-- ===================== 2 Chronicles — EASY tier (12 items: 8 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '2-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 5:13-14, what filled Yahweh''s house when the trumpeters and singers made one sound of praise?', '2 Chronicles 5:13-14', '...when the trumpeters and singers were as one, to make one sound to be heard in praising and thanking Yahweh... then the house was filled with a cloud, even Yahweh''s house, so that the priests could not stand to minister by reason of the cloud; for Yahweh''s glory filled God''s house.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["A cloud, filled with Yahweh''s glory", "Fire from heaven", "Total darkness", "A great earthquake"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 7:1, what happened right after Solomon finished praying at the temple dedication?', '2 Chronicles 7:1', 'Now when Solomon had finished praying, fire came down from heaven and consumed the burnt offering and the sacrifices; and Yahweh''s glory filled the house.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Fire came down from heaven and consumed the sacrifice", "The ark disappeared from the temple", "An earthquake shook Jerusalem", "The priests began a new song"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 29:1-2, what did Hezekiah do as king, following his father David''s example?', '2 Chronicles 29:1-2', 'Hezekiah began to reign when he was twenty-five years old, and he reigned twenty-nine years in Jerusalem... He did that which was right in Yahweh''s eyes, according to all that David his father had done.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["He did what was right in Yahweh''s eyes", "He built a new palace", "He raised a large army", "He made treaties with Egypt"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 29:3, what did Hezekiah do in the first month of the first year of his reign?', '2 Chronicles 29:3', 'In the first year of his reign, in the first month, he opened the doors of Yahweh''s house and repaired them.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["He opened the doors of Yahweh''s house and repaired them", "He tore down the temple", "He appointed new priests", "He declared war on Assyria"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 34:15, what did Hilkiah tell Shaphan the scribe he had found in Yahweh''s house?', '2 Chronicles 34:15', 'Hilkiah answered Shaphan the scribe, ''I have found the book of the law in Yahweh''s house.'' So Hilkiah delivered the book to Shaphan.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["The book of the law", "A hidden treasure", "A golden ark", "An ancient altar"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 35:1, what did Josiah keep in Jerusalem?', '2 Chronicles 35:1', 'Josiah kept a Passover to Yahweh in Jerusalem. They killed the Passover on the fourteenth day of the first month.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["A Passover to Yahweh", "A coronation feast", "A harvest festival", "A day of mourning"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 36:19-20, what happened to Jerusalem and its people?', '2 Chronicles 36:19-20', 'They burned God''s house, broke down the wall of Jerusalem, burned all its palaces with fire, and destroyed all of its valuable vessels. He carried those who had escaped from the sword away to Babylon...', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Burned God''s house and the city, and carried the survivors to Babylon", "Burned only the palace", "Made Jerusalem a Babylonian province without violence", "Rebuilt the temple"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 36:23, what did Cyrus king of Persia''s decree permit?', '2 Chronicles 36:23', 'Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah. Whoever there is among you of all his people, Yahweh his God be with him, and let him go up.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Any of Yahweh''s people among them could go up to Jerusalem", "The exiles must remain in Babylon", "The temple would be rebuilt in Persia", "Judah''s kings would be restored to power"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 36:22-23, which foreign king does the text say Yahweh ''stirred up'' to let the exiles return?', '2 Chronicles 36:22-23', 'In the first year of Cyrus king of Persia... Yahweh stirred up the spirit of Cyrus king of Persia, so that he made a proclamation throughout all his kingdom, and put it also in writing.; Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah. Whoever there is among you of all his people, Yahweh his God be with him, and let him go up.''', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Cyrus of Persia", "Nebuchadnezzar of Babylon", "Darius of Persia", "Sennacherib of Assyria"], "correct_index": 0}', true, 9),
  ((select id from w), 'sequence', 'Put these four scenes of 2 Chronicles in the order they happen in the book.', '2 Chronicles 7:1; 29:3; 35:1; 36:23', 'Now when Solomon had finished praying, fire came down from heaven and consumed the burnt offering and the sacrifices; and Yahweh''s glory filled the house.; In the first year of his reign, in the first month, he opened the doors of Yahweh''s house and repaired them.; Josiah kept a Passover to Yahweh in Jerusalem. They killed the Passover on the fourteenth day of the first month.; Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah. Whoever there is among you of all his people, Yahweh his God be with him, and let him go up.''', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Solomon''s Temple Dedication (2 Chronicles 7:1)", "Hezekiah''s Temple Cleansing (2 Chronicles 29:3)", "Josiah''s Passover (2 Chronicles 35:1)", "The Fall of Judah and Cyrus''s Decree (2 Chronicles 36:23)"], "correct_order": [0, 1, 2, 3]}', true, 10),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 7:2, why could the priests not enter Yahweh''s house?', '2 Chronicles 7:2', 'The priests could not enter into Yahweh''s house, because Yahweh''s glory filled Yahweh''s house.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Because Yahweh''s glory filled the house", "Because the doors were sealed shut", "Because the ark hadn''t yet arrived", "Because Solomon forbade it"], "correct_index": 0}', true, 11),
  ((select id from w), 'multiple_choice', 'According to 2 Chronicles 29:5, what did Hezekiah command the Levites to do, besides sanctifying themselves?', '2 Chronicles 29:5', '...Listen to me, you Levites! Now sanctify yourselves, and sanctify the house of Yahweh, the God of your fathers, and carry the filthiness out of the holy place.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Sanctify the house of Yahweh and carry out its filthiness", "Rebuild the outer wall", "Appoint new judges", "Compose new psalms"], "correct_index": 0}', true, 12)
;

-- ===================== 2 Chronicles — HARD tier (12 items: 8 regular + 4 boss) =====================

with w as (select id from public.world where book_slug = '2-chronicles')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what Solomon put the dedicated silver, gold, and vessels into, per 2 Chronicles 5:1.', '2 Chronicles 5:1', 'Thus all the work that Solomon did for Yahweh''s house was finished. Solomon brought in the things that David his father had dedicated, even the silver, the gold, and all the vessels, and put them in the treasuries of God''s house.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...Solomon brought in the things that David his father had dedicated, even the silver, the gold, and all the vessels, and put them in the treasuries of God''s ___.", "answer": "house"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: where the priests placed the ark, per 2 Chronicles 5:7.', '2 Chronicles 5:7', 'The priests brought in the ark of Yahweh''s covenant to its place, into the inner sanctuary of the house, to the most holy place, even under the wings of the cherubim.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "The priests brought in the ark of Yahweh''s covenant to its place, into the inner sanctuary of the house, to the most holy place, even under the wings of the ___.", "answer": "cherubim"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what the priests told Hezekiah they had done to Yahweh''s house, per 2 Chronicles 29:18.', '2 Chronicles 29:18', '...We have cleansed all Yahweh''s house, including the altar of burnt offering with all its vessels, and the table of show bread with all its vessels.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...We have ___ all Yahweh''s house, including the altar of burnt offering with all its vessels, and the table of show bread with all its vessels.", "answer": "cleansed"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from Hezekiah''s stated intent to make a covenant, per 2 Chronicles 29:10.', '2 Chronicles 29:10', 'Now it is in my heart to make a covenant with Yahweh, the God of Israel, that his fierce anger may turn away from us.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Now it is in my heart to make a covenant with Yahweh, the God of Israel, that his fierce ___ may turn away from us.", "answer": "anger"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what Josiah tore when he heard the words of the law, per 2 Chronicles 34:19.', '2 Chronicles 34:19', 'When the king had heard the words of the law, he tore his clothes.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "When the king had heard the words of the law, he tore his ___.", "answer": "clothes"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word from Josiah''s covenant renewal, per 2 Chronicles 34:31.', '2 Chronicles 34:31', 'The king stood in his place and made a covenant before Yahweh, to walk after Yahweh, and to keep his commandments, his testimonies, and his statutes with all his heart and with all his soul, to perform the words of the covenant that were written in this book.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...to walk after Yahweh, and to keep his commandments, his testimonies, and his statutes with all his heart and with all his ___, to perform the words of the covenant that were written in this book.", "answer": "soul"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: how many years the land''s desolation fulfilled, per 2 Chronicles 36:21.', '2 Chronicles 36:21', '...to fulfill Yahweh''s word by Jeremiah''s mouth, until the land had enjoyed its Sabbaths. As long as it lay desolate, it kept Sabbath, to fulfill seventy years.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...As long as it lay desolate, it kept Sabbath, to fulfill seventy ___.", "answer": "years"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word from Cyrus''s decree, per 2 Chronicles 36:23.', '2 Chronicles 36:23', 'Cyrus king of Persia says, ''Yahweh, the God of heaven, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go up.''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Cyrus king of Persia says, ''Yahweh, the God of ___, has given all the kingdoms of the earth to me; and he has commanded me to build him a house in Jerusalem, which is in Judah... let him go up.''", "answer": "heaven"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word from the people''s song of thanks when the fire fell on Solomon''s altar.', '2 Chronicles 7:3', 'All the children of Israel looked on, when the fire came down, and Yahweh''s glory was on the house. They bowed themselves with their faces to the ground on the pavement, worshiped, and gave thanks to Yahweh, saying, ''For he is good, for his loving kindness endures forever!''', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "All the children of Israel looked on, when the fire came down, and Yahweh''s glory was on the house. They bowed themselves with their faces to the ground on the pavement, worshiped, and gave thanks to Yahweh, saying, ''For he is good, for his loving kindness endures ___!''", "answer": "forever"}', true, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what the text says had not been kept like this since the days of Samuel the prophet.', '2 Chronicles 35:18', 'There was no Passover like that kept in Israel from the days of Samuel the prophet, nor did any of the kings of Israel keep such a Passover as Josiah kept...', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "There was no ___ like that kept in Israel from the days of Samuel the prophet, nor did any of the kings of Israel keep such a Passover as Josiah kept...", "answer": "Passover"}', true, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what Hezekiah told the Levites to carry out of the holy place, per 2 Chronicles 29:5.', '2 Chronicles 29:5', '...Listen to me, you Levites! Now sanctify yourselves, and sanctify the house of Yahweh, the God of your fathers, and carry the filthiness out of the holy place.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...Listen to me, you Levites! Now sanctify yourselves, and sanctify the house of Yahweh, the God of your fathers, and carry the ___ out of the holy place.", "answer": "filthiness"}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what the text says there was no more of, once Yahweh''s wrath arose against his people, per 2 Chronicles 36:16.', '2 Chronicles 36:16', '...but they mocked the messengers of God, despised his words, and scoffed at his prophets, until Yahweh''s wrath arose against his people, until there was no remedy.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "...until Yahweh''s wrath arose against his people, until there was no ___.", "answer": "remedy"}', true, 12)
;
