-- Gen2Rev challenge ingest: Numbers (World 4) and Deuteronomy (World 5)
-- Generated from docs/content/numbers.md and docs/content/deuteronomy.md
-- Both books: theological review approved-with-changes, verbatim QA pass (docs/CONTENT_REVIEW_LOG.md, docs/QA_SIGNOFF.md)
-- Structural rules applied per the briefs' Contested Territory sections:
--   Numbers: Korah's rebellion (16) and the bronze serpent (21) scenes limited to recall/sequence
--     format only (no multiple choice, no "why" phrasing); Numbers 23:19 restricted to recall-only;
--     Numbers 25 (Baal Peor) excluded entirely.
--   Deuteronomy: Deuteronomy 30:19-20 limited to recall/fill-in-blank or sequence format only (no
--     multiple choice); Ten Commandments referenced by verse only, never by ordinal number;
--     Deuteronomy 28's curse list excluded entirely; Deuteronomy 34 (Moses' death) included as the
--     required narrative bridge into Joshua (World 6).

with w as (select id from public.world where book_slug = 'numbers')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what were the counted men of Israel, twenty years old and upward, able to go out and do?',
   'Numbers 1:1-3', 'Yahweh spoke to Moses in the wilderness of Sinai, in the Tent of Meeting, on the first day of the second month, in the second year after they had come out of the land of Egypt, saying, ''Take a census of all the congregation of the children of Israel, by their families, by their fathers'' houses, according to the number of the names, every male, one by one, from twenty years old and upward, all who are able to go out to war in Israel. You and Aaron shall count them by their divisions.''', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh spoke to Moses in the wilderness of Sinai, in the Tent of Meeting, on the first day of the second month, in the second year after they had come out of the land of Egypt, saying, ''Take a census of all the congregation of the children of Israel, by their families, by their fathers'' houses, according to the number of the names, every male, one by one, from twenty years old and upward, all who are able to go out to ___ in Israel. You and Aaron shall count them by their divisions.''", "answer": "war"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: how did Yahweh instruct each man of Israel to encamp?',
   'Numbers 2:1-2', 'Yahweh spoke to Moses and to Aaron, saying, ''The children of Israel shall encamp every man by his own standard, with the banners of their fathers'' houses. They shall encamp around the Tent of Meeting at a distance from it.''', 'WEB', 1,
   '{"type": "recall", "template": "Yahweh spoke to Moses and to Aaron, saying, ''The children of Israel shall encamp every man by his own ___, with the banners of their fathers'' houses. They shall encamp around the Tent of Meeting at a distance from it.''", "answer": "standard"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word from the spies'' report on the cities of Canaan.',
   'Numbers 13:27-28', 'We came to the land where you sent us. Surely it flows with milk and honey, and this is its fruit. However, the people who dwell in the land are strong, and the cities are fortified and very large. Moreover, we saw the children of Anak there.', 'WEB', 2,
   '{"type": "recall", "template": "We came to the land where you sent us. Surely it flows with milk and honey, and this is its fruit. However, the people who dwell in the land are strong, and the cities are ___ and very large. Moreover, we saw the children of Anak there.", "answer": "fortified"}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Numbers 13:30, what did Caleb urge the people to do?',
   'Numbers 13:30', 'Caleb stilled the people before Moses, and said, ''Let''s go up at once, and possess it; for we are well able to overcome it!''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Go up at once and possess the land", "Wait one more year before deciding", "Send a second group of spies", "Return to Egypt immediately"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word from the people''s despairing complaint at Kadesh-barnea.',
   'Numbers 14:1-4', 'All the congregation lifted up their voice, and cried; and the people wept that night. All the children of Israel murmured against Moses and against Aaron. The whole congregation said to them, ''We wish that we had died in the land of Egypt, or that we had died in this wilderness! Why does Yahweh bring us to this land, to fall by the sword? Our wives and our little ones will be captured or killed! Wouldn''t it be better for us to return into Egypt?'' They said to one another, ''Let''s choose a leader, and let''s return into Egypt.''', 'WEB', 2,
   '{"type": "recall", "template": "All the congregation lifted up their voice, and cried; and the people wept that night. All the children of Israel murmured against Moses and against Aaron. The whole congregation said to them, ''We wish that we had died in the land of Egypt, or that we had died in this wilderness! Why does Yahweh bring us to this land, to fall by the ___? Our wives and our little ones will be captured or killed! Wouldn''t it be better for us to return into Egypt?'' They said to one another, ''Let''s choose a leader, and let''s return into Egypt.''", "answer": "sword"}', true, 5),
  ((select id from w), 'recall', 'Fill in the missing word from Korah''s challenge to Moses and Aaron''s authority.',
   'Numbers 16:1-3', 'Now Korah... with Dathan and Abiram... took some men. They rose up before Moses, with some of the children of Israel, two hundred fifty princes of the congregation... They assembled themselves together against Moses and against Aaron, and said to them, ''You take too much on yourself, since all the congregation are holy, everyone of them, and Yahweh is among them! Why do you lift yourselves up above Yahweh''s assembly?''', 'WEB', 3,
   '{"type": "recall", "template": "Now Korah... with Dathan and Abiram... took some men. They rose up before Moses, with some of the children of Israel, two hundred fifty princes of the congregation... They assembled themselves together against Moses and against Aaron, and said to them, ''You take too much on yourself, since all the congregation are ___, everyone of them, and Yahweh is among them! Why do you lift yourselves up above Yahweh''s assembly?''", "answer": "holy"}', true, 6),
  ((select id from w), 'sequence', 'Put these events of Korah''s rebellion and its aftermath in the order they occur in the text.',
   'Numbers 16:1-3; 16:31-32; 26:11', 'Now Korah... with Dathan and Abiram... took some men... They assembled themselves together against Moses and against Aaron, and said to them, ''You take too much on yourself, since all the congregation are holy, everyone of them, and Yahweh is among them! Why do you lift yourselves up above Yahweh''s assembly?''; As he finished speaking all these words, the ground that was under them split apart. The earth opened its mouth and swallowed them up with their households, all of Korah''s men, and all their goods.; Notwithstanding, the sons of Korah didn''t die.', 'WEB', 4,
   '{"type": "sequence", "items": ["Korah, joined by Dathan and Abiram and 250 leaders, challenges Moses and Aaron''s authority", "The ground opens and swallows Korah''s household along with all his men and goods", "The text later notes that the sons of Korah did not die"], "correct_order": [0, 1, 2]}', true, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what happened to a bitten man who looked at the bronze serpent?',
   'Numbers 21:8-9', 'Yahweh said to Moses, ''Make a venomous snake, and set it on a pole. It shall happen that everyone who is bitten, when he sees it, shall live.'' Moses made a serpent of bronze, and set it on the pole. If a serpent had bitten any man, when he looked at the serpent of bronze, he lived.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh said to Moses, ''Make a venomous snake, and set it on a pole. It shall happen that everyone who is bitten, when he sees it, shall live.'' Moses made a serpent of bronze, and set it on the pole. If a serpent had bitten any man, when he looked at the serpent of bronze, he ___.", "answer": "lived"}', false, 8),
  ((select id from w), 'sequence', 'Put these events of the bronze serpent episode in the order they occur in the text.',
   'Numbers 21:6-7; 21:8-9', 'Yahweh sent venomous snakes among the people, and they bit the people. Many people of Israel died. The people came to Moses, and said, ''We have sinned, because we have spoken against Yahweh and against you. Pray to Yahweh, that he take away the serpents from us.'' Moses prayed for the people.; Yahweh said to Moses, ''Make a venomous snake, and set it on a pole. It shall happen that everyone who is bitten, when he sees it, shall live.'' Moses made a serpent of bronze, and set it on the pole. If a serpent had bitten any man, when he looked at the serpent of bronze, he lived.', 'WEB', 3,
   '{"type": "sequence", "items": ["Yahweh sends venomous snakes among the people, and many of them die", "The people confess their sin to Moses and ask him to pray for them", "Yahweh instructs Moses to make a bronze snake and set it on a pole", "Moses makes the bronze serpent, and anyone bitten who looks at it lives"], "correct_order": [0, 1, 2, 3]}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Numbers 22:27-28, what happened when Yahweh opened the mouth of Balaam''s donkey?',
   'Numbers 22:27-28', 'The donkey saw Yahweh''s angel, and she lay down under Balaam. Balaam''s anger burned, and he struck the donkey with his staff. Yahweh opened the mouth of the donkey, and she said to Balaam, ''What have I done to you, that you have struck me these three times?''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The donkey spoke and questioned Balaam", "The donkey ran away from Balaam", "The donkey collapsed and died", "The donkey kicked Balaam"], "correct_index": 0}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word from Balaam''s oracle about Yahweh''s unchanging word.',
   'Numbers 23:19', 'God is not a man, that he should lie, nor a son of man, that he should repent. Has he said, and he won''t do it? Or has he spoken, and he won''t make it good?', 'WEB', 1,
   '{"type": "recall", "template": "God is not a man, that he should ___, nor a son of man, that he should repent. Has he said, and he won''t do it? Or has he spoken, and he won''t make it good?", "answer": "lie"}', false, 11),
  ((select id from w), 'sequence', 'Put these events of the Balaam episode in the order they occur in the text.',
   'Numbers 22:27-28; 22:31', 'The donkey saw Yahweh''s angel, and she lay down under Balaam. Balaam''s anger burned, and he struck the donkey with his staff. Yahweh opened the mouth of the donkey, and she said to Balaam, ''What have I done to you, that you have struck me these three times?''; Then Yahweh opened the eyes of Balaam, and he saw Yahweh''s angel standing in the way, with his sword drawn in his hand; and he bowed his head, and fell on his face.', 'WEB', 3,
   '{"type": "sequence", "items": ["Balak, king of Moab, hires Balaam to curse Israel", "Balaam''s donkey sees Yahweh''s angel blocking the path and balks three times", "The donkey speaks and rebukes Balaam after he strikes her", "Yahweh opens Balaam''s eyes and he sees the angel standing in the way", "Balaam blesses Israel three times instead of cursing them, as Balak had wanted"], "correct_order": [0, 1, 2, 3, 4]}', true, 12)
;

with w as (select id from public.world where book_slug = 'deuteronomy')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say Israel shall have none of, before him?',
   'Deuteronomy 5:6-7', 'I am Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage. You shall have no other gods before me.', 'WEB', 1,
   '{"type": "recall", "template": "I am Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage. You shall have no other ___ before me.", "answer": "gods"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word from the command to honor one''s parents.',
   'Deuteronomy 5:16', 'Honor your father and your mother, as Yahweh your God commanded you, that your days may be long and that it may go well with you in the land which Yahweh your God gives you.', 'WEB', 1,
   '{"type": "recall", "template": "Honor your father and your ___, as Yahweh your God commanded you, that your days may be long and that it may go well with you in the land which Yahweh your God gives you.", "answer": "mother"}', false, 2),
  ((select id from w), 'multiple_choice', 'Which of these instructions appears in Deuteronomy 5:17-19?',
   'Deuteronomy 5:17-19', 'You shall not murder. You shall not commit adultery. You shall not steal.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["You shall not murder", "Remember the Sabbath day to keep it holy", "You shall have no other gods before me", "You shall not covet your neighbor''s house"], "correct_index": 0}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word from the Shema, Israel''s central confession of faith.',
   'Deuteronomy 6:4-5', 'Hear, Israel: Yahweh is our God. Yahweh is one. You shall love Yahweh your God with all your heart, with all your soul, and with all your might.', 'WEB', 1,
   '{"type": "recall", "template": "Hear, Israel: Yahweh is our God. Yahweh is one. You shall love Yahweh your God with all your heart, with all your soul, and with all your ___.", "answer": "might"}', true, 4),
  ((select id from w), 'recall', 'Fill in the missing word: where does Moses say these words shall be, and taught diligently to the children?',
   'Deuteronomy 6:6-7', 'These words, which I command you today, shall be on your heart; and you shall teach them diligently to your children, and shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise up.', 'WEB', 2,
   '{"type": "recall", "template": "These words, which I command you today, shall be on your ___; and you shall teach them diligently to your children, and shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise up.", "answer": "heart"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does Moses warn the people not to go after, if they turn away?',
   'Deuteronomy 11:26-28', 'Behold, I set before you today a blessing and a curse: the blessing, if you listen to the commandments of Yahweh your God, which I command you today; and the curse, if you do not listen to the commandments of Yahweh your God, but turn away out of the way which I command you today, to go after other gods which you have not known.', 'WEB', 2,
   '{"type": "recall", "template": "Behold, I set before you today a blessing and a curse: the blessing, if you listen to the commandments of Yahweh your God, which I command you today; and the curse, if you do not listen to the commandments of Yahweh your God, but turn away out of the way which I command you today, to go after other ___ which you have not known.", "answer": "gods"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word from Moses'' charge to ''choose life.''',
   'Deuteronomy 30:19-20', '...Therefore choose life, that you may live, you and your descendants, to love Yahweh your God, to obey his voice, and to cling to him...', 'WEB', 1,
   '{"type": "recall", "template": "...Therefore choose ___, that you may live, you and your descendants, to love Yahweh your God, to obey his voice, and to cling to him...", "answer": "life"}', true, 7),
  ((select id from w), 'multiple_choice', 'According to Deuteronomy 31:7-8, what does Moses charge Joshua to be, in the sight of all Israel?',
   'Deuteronomy 31:7-8', 'Moses called to Joshua, and said to him in the sight of all Israel, ''Be strong and courageous, for you shall go with this people into the land which Yahweh has sworn to their fathers to give them; and you shall cause them to inherit it. Yahweh himself is who goes before you. He will be with you. He will not fail you nor forsake you. Don''t be afraid. Don''t be discouraged.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Strong and courageous", "Patient and cautious", "Silent and obedient", "Wealthy and powerful"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: in what land did Moses die, according to the text?',
   'Deuteronomy 34:4-5', 'Yahweh said to him, ''This is the land which I swore to Abraham, to Isaac, and to Jacob, saying, "I will give it to your offspring." I have caused you to see it with your eyes, but you shall not go over there.'' So Moses the servant of Yahweh died there in the land of Moab, according to Yahweh''s word.', 'WEB', 2,
   '{"type": "recall", "template": "Yahweh said to him, ''This is the land which I swore to Abraham, to Isaac, and to Jacob, saying, \"I will give it to your offspring.\" I have caused you to see it with your eyes, but you shall not go over there.'' So Moses the servant of Yahweh died there in the land of ___, according to Yahweh''s word.", "answer": "Moab"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Deuteronomy 34:7, what does the text say about Moses'' physical condition when he died at 120?',
   'Deuteronomy 34:7', 'Moses was one hundred twenty years old when he died. His eye was not dim, nor his strength gone.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["His eye was not dim, nor his strength gone", "He was blind and frail", "He had lost his memory", "He had been ill for many years"], "correct_index": 0}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word closing the book of Deuteronomy, about Moses'' unique status.',
   'Deuteronomy 34:10', 'Since then, there has not arisen a prophet in Israel like Moses, whom Yahweh knew face to face.', 'WEB', 2,
   '{"type": "recall", "template": "Since then, there has not arisen a ___ in Israel like Moses, whom Yahweh knew face to face.", "answer": "prophet"}', true, 11),
  ((select id from w), 'sequence', 'Put these movements of Moses'' farewell address in the order they occur in the book of Deuteronomy.',
   'Deuteronomy 5; 6:4-9; 11,30; 31; 34', 'Moses restates the Ten Commandments to the new generation; Moses gives the Shema, Israel''s central confession of faith; Moses sets before Israel the blessing and the curse, and charges them to choose life; Moses commissions Joshua as his successor in the sight of all Israel; Moses dies on Mount Nebo after viewing the promised land', 'WEB', 5,
   '{"type": "sequence", "items": ["Moses restates the Ten Commandments to the new generation (Deuteronomy 5)", "Moses gives Israel the Shema, its central confession of faith (Deuteronomy 6:4-9)", "Moses sets before the people the blessing and the curse, and charges them to choose life (Deuteronomy 11, 30)", "Moses commissions Joshua as his successor in the sight of all Israel (Deuteronomy 31)", "Moses dies on Mount Nebo after viewing the promised land he will not enter (Deuteronomy 34)"], "correct_order": [0, 1, 2, 3, 4]}', true, 12)
;
