-- Gen2Rev challenge ingest: Proverbs (World 20), Ecclesiastes (World 21), Song of Solomon (World 22)
-- Generated from docs/content/proverbs.md, docs/content/ecclesiastes.md, docs/content/song-of-solomon.md
-- All three books: theological review pass/approved-with-changes, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md rows 20-22, docs/QA_SIGNOFF.md). Song of Solomon escalated and
-- resolved by Kachi Okere 2026-08-25 (docs/reviews/song-of-solomon-review.md addendum) to ship
-- exactly as scoped -- 4 passages only, no material beyond what's in the brief.

with w as (select id from public.world where book_slug = 'proverbs')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what is the beginning of knowledge, per Proverbs 1:7?', 'Proverbs 1:7', 'The fear of Yahweh is the beginning of knowledge, but the foolish despise wisdom and instruction.', 'WEB', 1,
   '{"type": "recall", "template": "The fear of Yahweh is the beginning of ___, but the foolish despise wisdom and instruction.", "answer": "knowledge"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what does Proverbs 3:5 say to trust with all your heart?', 'Proverbs 3:5-6', 'Trust in Yahweh with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.', 'WEB', 1,
   '{"type": "recall", "template": "Trust in ___ with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.", "answer": "Yahweh"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what does Proverbs 3:15 say wisdom is more precious than?', 'Proverbs 3:13-15', 'Happy is the man who finds wisdom, the man who gets understanding. For her good profit is better than getting silver, and her return is better than fine gold. She is more precious than rubies. None of the things you can desire are to be compared to her.', 'WEB', 2,
   '{"type": "recall", "template": "Happy is the man who finds wisdom, the man who gets understanding. For her good profit is better than getting silver, and her return is better than fine gold. She is more precious than ___. None of the things you can desire are to be compared to her.", "answer": "rubies"}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Proverbs 4:18, what is the path of the righteous compared to?', 'Proverbs 4:18-19', 'But the path of the righteous is like the dawning light that shines more and more until the perfect day. The way of the wicked is like darkness. They don''t know what they stumble over.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The dawning light that shines more and more until the perfect day", "A river flowing to the sea", "A tree planted by water", "A lamp under a basket"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what does Proverbs 4:23 say to keep with all diligence?', 'Proverbs 4:23', 'Keep your heart with all diligence, for out of it is the wellspring of life.', 'WEB', 1,
   '{"type": "recall", "template": "Keep your ___ with all diligence, for out of it is the wellspring of life.", "answer": "heart"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does a gentle answer do, per Proverbs 15:1?', 'Proverbs 15:1', 'A gentle answer turns away wrath, but a harsh word stirs up anger.', 'WEB', 1,
   '{"type": "recall", "template": "A gentle answer turns away ___, but a harsh word stirs up anger.", "answer": "wrath"}', false, 6),
  ((select id from w), 'multiple_choice', 'Which of these proverbs is found at Proverbs 27:17?', 'Proverbs 27:17', 'Iron sharpens iron; so a man sharpens his friend''s countenance.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Iron sharpens iron; so a man sharpens his friend''s countenance.", "A gentle answer turns away wrath, but a harsh word stirs up anger.", "Pride goes before destruction, and an arrogant spirit before a fall.", "A friend loves at all times; and a brother is born for adversity."], "correct_index": 0}', false, 7),
  ((select id from w), 'sequence', 'Proverbs 16:18 states two parallel lines. Put them in the order the verse states them.', 'Proverbs 16:18', 'Pride goes before destruction, and an arrogant spirit before a fall.', 'WEB', 3,
   '{"type": "sequence", "items": ["Pride goes before destruction", "an arrogant spirit before a fall"], "correct_order": [0, 1]}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what is more desirable than great riches, per Proverbs 22:1?', 'Proverbs 22:1', 'A good name is more desirable than great riches, and loving favor is better than silver and gold.', 'WEB', 1,
   '{"type": "recall", "template": "A good ___ is more desirable than great riches, and loving favor is better than silver and gold.", "answer": "name"}', false, 9),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the book of Proverbs.', 'Proverbs 1:7; 3:5-6; 22:6', 'The fear of Yahweh is the beginning of knowledge, but the foolish despise wisdom and instruction.; Trust in Yahweh with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.; Train up a child in the way he should go, and when he is old he will not depart from it.', 'WEB', 4,
   '{"type": "sequence", "items": ["“The fear of Yahweh is the beginning of knowledge...” (Proverbs 1:7)", "“Trust in Yahweh with all your heart...” (Proverbs 3:5-6)", "“Train up a child in the way he should go...” (Proverbs 22:6)"], "correct_order": [0, 1, 2]}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: according to Proverbs 31:10, what is a worthy woman''s value compared to?', 'Proverbs 31:10', 'Who can find a worthy woman? For her value is far above rubies.', 'WEB', 4,
   '{"type": "recall", "template": "Who can find a worthy woman? For her value is far above ___.", "answer": "rubies"}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: according to Proverbs 31:25, what does the text say clothes her?', 'Proverbs 31:25-26', 'Strength and dignity are her clothing. She laughs at the time to come. She opens her mouth with wisdom. Kind instruction is on her tongue.', 'WEB', 4,
   '{"type": "recall", "template": "Strength and dignity are her ___. She laughs at the time to come. She opens her mouth with wisdom. Kind instruction is on her tongue.", "answer": "clothing"}', true, 12),
  ((select id from w), 'multiple_choice', 'According to Proverbs 31:30, what does the text say is deceitful?', 'Proverbs 31:30', 'Charm is deceitful, and beauty is vain; but a woman who fears Yahweh, she shall be praised.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Charm", "Wealth", "Beauty", "Strength"], "correct_index": 0}', true, 13)
;

with w as (select id from public.world where book_slug = 'ecclesiastes')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: how does the Preacher''s opening refrain end, per Ecclesiastes 1:2?', 'Ecclesiastes 1:2', '''Vanity of vanities,'' says the Preacher; ''Vanity of vanities, all is vanity.''', 'WEB', 1,
   '{"type": "recall", "template": "''Vanity of vanities,'' says the Preacher; ''Vanity of vanities, all is ___.''", "answer": "vanity"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 1:9, there is no new thing under the ___?', 'Ecclesiastes 1:9', 'That which has been is that which shall be, and that which has been done is that which shall be done; and there is no new thing under the sun.', 'WEB', 1,
   '{"type": "recall", "template": "That which has been is that which shall be, and that which has been done is that which shall be done; and there is no new thing under the ___.", "answer": "sun"}', false, 2),
  ((select id from w), 'multiple_choice', 'Which chapter of Ecclesiastes contains the line "a time to be born, and a time to die"?', 'Ecclesiastes 3:1-8', 'For everything there is a season, and a time for every purpose under heaven: a time to be born, and a time to die; a time to plant, and a time to pluck up that which is planted; a time to kill, and a time to heal; a time to break down, and a time to build up; a time to weep, and a time to laugh; a time to mourn, and a time to dance; a time to cast away stones, and a time to gather stones together; a time to embrace, and a time to refrain from embracing; a time to seek, and a time to lose; a time to keep, and a time to cast away; a time to tear, and a time to sew; a time to keep silence, and a time to speak; a time to love, and a time to hate; a time for war, and a time for peace.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Ecclesiastes 3", "Ecclesiastes 1", "Ecclesiastes 4", "Ecclesiastes 12"], "correct_index": 0}', false, 3),
  ((select id from w), 'sequence', 'Ecclesiastes 3:1-8 lists paired opposites, each with its appointed time. Put these four pairs in the order the text states them.', 'Ecclesiastes 3:2-7', 'For everything there is a season, and a time for every purpose under heaven: a time to be born, and a time to die; a time to plant, and a time to pluck up that which is planted; a time to kill, and a time to heal; a time to break down, and a time to build up; a time to weep, and a time to laugh; a time to mourn, and a time to dance; a time to cast away stones, and a time to gather stones together; a time to embrace, and a time to refrain from embracing; a time to seek, and a time to lose; a time to keep, and a time to cast away; a time to tear, and a time to sew; a time to keep silence, and a time to speak; a time to love, and a time to hate; a time for war, and a time for peace.', 'WEB', 3,
   '{"type": "sequence", "items": ["a time to plant, and a time to pluck up that which is planted", "a time to kill, and a time to heal", "a time to break down, and a time to build up", "a time to weep, and a time to laugh"], "correct_order": [0, 1, 2, 3]}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 3:11, what has God set in people''s hearts?', 'Ecclesiastes 3:11', 'He has made everything beautiful in its time. He has also set eternity in their hearts, yet so that man can''t find out the work that God has done from the beginning even to the end.', 'WEB', 2,
   '{"type": "recall", "template": "He has made everything beautiful in its time. He has also set ___ in their hearts, yet so that man can''t find out the work that God has done from the beginning even to the end.", "answer": "eternity"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 4:9, two are better than one because of what?', 'Ecclesiastes 4:9-10', 'Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn''t have another to lift him up.', 'WEB', 1,
   '{"type": "recall", "template": "Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his ___; but woe to him who is alone when he falls, and doesn''t have another to lift him up.", "answer": "fellow"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 4:12, what is not quickly broken?', 'Ecclesiastes 4:12', 'If a man prevails against one who is alone, two shall withstand him; and a threefold cord is not quickly broken.', 'WEB', 2,
   '{"type": "recall", "template": "If a man prevails against one who is alone, two shall withstand him; and a threefold ___ is not quickly broken.", "answer": "cord"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what does Ecclesiastes 12:1 say to remember in the days of your youth?', 'Ecclesiastes 12:1', 'Remember also your Creator in the days of your youth, before the evil days come, and the years draw near, when you will say, ''I have no pleasure in them.''', 'WEB', 1,
   '{"type": "recall", "template": "Remember also your ___ in the days of your youth, before the evil days come, and the years draw near, when you will say, ''I have no pleasure in them.''", "answer": "Creator"}', false, 8),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the book of Ecclesiastes.', 'Ecclesiastes 1:2; 3:1; 12:13', '''Vanity of vanities,'' says the Preacher; ''Vanity of vanities, all is vanity.''; For everything there is a season, and a time for every purpose under heaven.; This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man.', 'WEB', 4,
   '{"type": "sequence", "items": ["“Vanity of vanities... all is vanity.” (Ecclesiastes 1:2)", "“For everything there is a season, and a time for every purpose under heaven.” (Ecclesiastes 3:1)", "“Fear God and keep his commandments; for this is the whole duty of man.” (Ecclesiastes 12:13)"], "correct_order": [0, 1, 2]}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 12:13, fearing God and keeping his commandments is the whole duty of whom?', 'Ecclesiastes 12:13', 'This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man.', 'WEB', 3,
   '{"type": "recall", "template": "This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of ___.", "answer": "man"}', true, 10),
  ((select id from w), 'multiple_choice', 'According to Ecclesiastes 12:13, what does the text state is ''the whole duty of man''?', 'Ecclesiastes 12:13', 'This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["To fear God and keep his commandments", "To seek wisdom above all things", "To enjoy the fruit of one''s labor", "To remember one''s Creator only"], "correct_index": 0}', true, 11),
  ((select id from w), 'recall', 'Fill in the missing word: per Ecclesiastes 12:14, what will God bring every work into?', 'Ecclesiastes 12:14', 'For God will bring every work into judgment, with every hidden thing, whether it is good, or whether it is evil.', 'WEB', 3,
   '{"type": "recall", "template": "For God will bring every work into ___, with every hidden thing, whether it is good, or whether it is evil.", "answer": "judgment"}', true, 12)
;

with w as (select id from public.world where book_slug = 'song-of-solomon')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what does Song of Solomon 2:7 say not to awaken until it desires?', 'Song of Solomon 2:7', 'I adjure you, daughters of Jerusalem, by the roes, or by the hinds of the field, that you not stir up, nor awaken love, until it so desires.', 'WEB', 1,
   '{"type": "recall", "template": "I adjure you, daughters of Jerusalem, by the roes, or by the hinds of the field, that you not stir up, nor awaken ___, until it so desires.", "answer": "love"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: per Song of Solomon 3:5, the daughters of Jerusalem are adjured by the roes, or by the ___ of the field.', 'Song of Solomon 3:5', 'I adjure you, daughters of Jerusalem, by the roes, or by the hinds of the field, that you not stir up nor awaken love, until it so desires.', 'WEB', 2,
   '{"type": "recall", "template": "I adjure you, daughters of Jerusalem, by the roes, or by the ___ of the field, that you not stir up nor awaken love, until it so desires.", "answer": "hinds"}', false, 2),
  ((select id from w), 'sequence', 'The ''do not awaken love'' refrain appears three times in Song of Solomon. Put the three occurrences in the order they fall in the book.', 'Song of Solomon 2:7; 3:5; 8:4', 'I adjure you, daughters of Jerusalem, by the roes, or by the hinds of the field, that you not stir up, nor awaken love, until it so desires.; I adjure you, daughters of Jerusalem, by the roes, or by the hinds of the field, that you not stir up nor awaken love, until it so desires.; I adjure you, daughters of Jerusalem, that you not stir up, nor awaken love, until it so desires.', 'WEB', 3,
   '{"type": "sequence", "items": ["Song of Solomon 2:7", "Song of Solomon 3:5", "Song of Solomon 8:4"], "correct_order": [0, 1, 2]}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: per Song of Solomon 2:12, whose voice is heard in the land?', 'Song of Solomon 2:10-13', 'My beloved spoke, and said to me, ''Rise up, my love, my beautiful one, and come away. For behold, the winter is past. The rain is over and gone. The flowers appear on the earth. The time of the singing has come, and the voice of the turtledove is heard in our land. The fig tree ripens her green figs. The vines are in blossom. They give out their fragrance. Arise, my love, my beautiful one, and come away.''', 'WEB', 2,
   '{"type": "recall", "template": "My beloved spoke, and said to me, ''Rise up, my love, my beautiful one, and come away. For behold, the winter is past. The rain is over and gone. The flowers appear on the earth. The time of the singing has come, and the voice of the ___ is heard in our land. The fig tree ripens her green figs. The vines are in blossom. They give out their fragrance. Arise, my love, my beautiful one, and come away.''", "answer": "turtledove"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: complete the declaration in Song of Solomon 2:16.', 'Song of Solomon 2:16', 'My beloved is mine, and I am his.', 'WEB', 1,
   '{"type": "recall", "template": "My beloved is mine, and I am ___.", "answer": "his"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: per Song of Solomon 8:6, love is said to be as strong as what?', 'Song of Solomon 8:6-7', 'Set me as a seal on your heart, as a seal on your arm; for love is strong as death. Jealousy is as cruel as Sheol. Its flashes are flashes of fire, a very flame of Yah. Many waters can''t quench love, neither can floods drown it. If a man would give all the wealth of his house for love, he would be utterly scorned.', 'WEB', 4,
   '{"type": "recall", "template": "Set me as a seal on your heart, as a seal on your arm; for love is strong as ___. Jealousy is as cruel as Sheol. Its flashes are flashes of fire, a very flame of Yah. Many waters can''t quench love, neither can floods drown it. If a man would give all the wealth of his house for love, he would be utterly scorned.", "answer": "death"}', true, 6),
  ((select id from w), 'multiple_choice', 'According to Song of Solomon 8:7, what can''t quench love?', 'Song of Solomon 8:6-7', 'Set me as a seal on your heart, as a seal on your arm; for love is strong as death. Jealousy is as cruel as Sheol. Its flashes are flashes of fire, a very flame of Yah. Many waters can''t quench love, neither can floods drown it. If a man would give all the wealth of his house for love, he would be utterly scorned.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Many waters", "Fire", "Time", "Jealousy"], "correct_index": 0}', true, 7),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in Song of Solomon, matched to their references.', 'Song of Solomon 2:10-13; 2:16; 8:6-7', 'My beloved spoke, and said to me, ''Rise up, my love, my beautiful one, and come away...''; My beloved is mine, and I am his.; Set me as a seal on your heart, as a seal on your arm; for love is strong as death.', 'WEB', 4,
   '{"type": "sequence", "items": ["“Rise up, my love, my beautiful one, and come away...” (Song of Solomon 2:10-13)", "“My beloved is mine, and I am his.” (Song of Solomon 2:16)", "“Set me as a seal on your heart... for love is strong as death.” (Song of Solomon 8:6-7)"], "correct_order": [0, 1, 2]}', false, 8)
;
