-- Gen2Rev challenge ingest: Psalms (World 19) and Proverbs (World 20) -- EASY and HARD tiers
-- Generated from docs/content/psalms-easy.md, docs/content/psalms-hard.md,
--   docs/content/proverbs-easy.md, docs/content/proverbs-hard.md
-- All four briefs: theological review approved / approved-with-changes, independent verbatim-text QA
--   pass complete (docs/CONTENT_REVIEW_LOG.md rows 19e/19h/20e/20h, docs/QA_SIGNOFF.md same rows;
--   docs/reviews/psalms-easy-review.md, docs/reviews/psalms-hard-review.md,
--   docs/reviews/proverbs-easy-review.md, docs/reviews/proverbs-hard-review.md).
-- Medium-tier rows (difficulty_tier = 'medium') already in the DB from docs/ingest/job-psalms.sql and
--   docs/ingest/proverbs-ecclesiastes-song-of-solomon.sql are untouched by this file.
--
-- Structural rules carried forward from each medium brief and reaffirmed/extended by the easy/hard
-- briefs:
--   Psalms: imprecatory psalms, Psalm 22, Psalm 110, and Psalm 51:5 excluded entirely in every tier.
--     Psalm 51:12 ("the joy of your salvation," hard item 6) is recall-only, word-level-only -- never
--     a question about what "salvation" refers to or a doctrine of salvation.
--   Proverbs: Proverbs 22:6 restricted to recall/attribution-matching format only, never
--     application-framed; the Proverbs 31:10-31 cluster restricted to recall of the poem's own wording
--     only. Proverbs 3:7-8 (hard item 2) and Proverbs 16:9 (hard item 6) are recall-only, never
--     multiple choice or a question resolving the underlying interpretive tension.
--   difficulty_rank: 1 for every easy-tier row, 5 for every hard-tier row (medium rows, untouched,
--     keep their own varied ranks).

with w as (select id from public.world where book_slug = 'psalms')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  -- ===================== PSALMS — EASY TIER =====================
  ((select id from w), 'multiple_choice', 'According to Psalm 1:1, whose counsel does the blessed man not walk in?',
   'Psalm 1:1', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers;', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["the wicked", "the priests", "the elders", "the poor"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Psalm 1:3, the righteous person is compared to what?',
   'Psalm 1:3', 'He will be like a tree planted by the streams of water, that produces its fruit in its season, whose leaf also does not wither. Whatever he does shall prosper.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["a tree planted by streams of water", "a mountain", "a lamp", "a shield"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'According to Psalm 23:1, what does the psalmist call Yahweh?',
   'Psalm 23:1', 'Yahweh is my shepherd; I shall lack nothing.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["my shepherd", "my king", "my rock", "my father"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'Per its own superscription, who is traditionally credited as the author of Psalm 23?',
   'Psalm 23, superscription', 'A Psalm by David.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["David", "Solomon", "Moses", "Asaph"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Psalm 23:2, where does Yahweh make the psalmist lie down?',
   'Psalm 23:2', 'He makes me lie down in green pastures. He leads me beside still waters.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["green pastures", "a mountain top", "a desert", "a garden"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what does David ask God to create in him, per Psalm 51:10?',
   'Psalm 51:10', 'Create in me a clean heart, O God. Renew a right spirit within me.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "Create in me a clean ___, O God. Renew a right spirit within me.", "answer": "heart"}', false, 6),
  ((select id from w), 'multiple_choice', 'Per Psalm 51''s own superscription, which prophet came to David?',
   'Psalm 51, superscription', 'For the Chief Musician. A Psalm by David, when Nathan the prophet came to him, after he had gone in to Bathsheba.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Nathan", "Samuel", "Elijah", "Gad"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'Psalm 100 opens with a call to do what?',
   'Psalm 100:1', 'Shout for joy to Yahweh, all you lands!', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Shout for joy to Yahweh", "Sit in silence", "Weep before Yahweh", "Build an altar"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Psalm 100:3, whose people are we called?',
   'Psalm 100:3', 'Know that Yahweh, he is God. It is he who has made us, and we are his. We are his people, and the sheep of his pasture.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["his (Yahweh''s) people", "the king''s people", "the priest''s people", "no one''s"], "correct_index": 0}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Psalm 121, where does the psalmist''s help come from?',
   'Psalm 121:1-2', 'I will lift up my eyes to the hills. Where does my help come from? My help comes from Yahweh, who made heaven and earth.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Yahweh, who made heaven and earth", "the hills themselves", "the king", "the priests"], "correct_index": 0}', false, 10),
  ((select id from w), 'multiple_choice', 'According to Psalm 121:4, what will the keeper of Israel never do?',
   'Psalm 121:4', 'Behold, he who keeps Israel will neither slumber nor sleep.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["slumber nor sleep", "eat nor drink", "speak nor sing", "rest nor gather"], "correct_index": 0}', false, 11),
  ((select id from w), 'multiple_choice', 'Which instrument is named first in Psalm 150:3?',
   'Psalm 150:3', 'Praise him with the sounding of the trumpet! Praise him with harp and lyre!', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["trumpet", "cymbals", "flute", "tambourine"], "correct_index": 0}', false, 12),
  ((select id from w), 'multiple_choice', 'According to Psalm 100:5, what does the text say endures forever?',
   'Psalm 100:5', 'For Yahweh is good. His loving kindness endures forever, his faithfulness to all generations.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["his loving kindness", "his temple", "his throne", "his covenant"], "correct_index": 0}', true, 13),
  ((select id from w), 'sequence', 'Put Psalm 150''s list of instruments in the order they appear in the text.',
   'Psalm 150:3-5', 'Praise him with the sounding of the trumpet! Praise him with harp and lyre!; Praise him with tambourine and dancing! Praise him with stringed instruments and flute!; Praise him with loud cymbals! Praise him with resounding cymbals!', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["Trumpet, harp, and lyre (v.3)", "Tambourine and dancing, stringed instruments and flute (v.4)", "Loud cymbals and resounding cymbals (v.5)"], "correct_order": [0, 1, 2]}', true, 14),
  ((select id from w), 'multiple_choice', 'According to Psalm 150:6, what does the text call on everything that has breath to do?',
   'Psalm 150:6', 'Let everything that has breath praise Yah! Praise Yah!', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["praise Yah", "build an altar", "offer sacrifice", "keep silence"], "correct_index": 0}', true, 15),

  -- ===================== PSALMS — HARD TIER =====================
  ((select id from w), 'recall', 'Fill in the missing word: how the righteous meditates on Yahweh''s law, per Psalm 1:2.',
   'Psalm 1:2', 'but his delight is in Yahweh''s law. On his law he meditates day and night.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "but his delight is in Yahweh''s law. On his law he meditates day and ___.", "answer": "night"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: where the blessed man does not sit, per Psalm 1:1.',
   'Psalm 1:1', 'Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers;', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Blessed is the man who doesn''t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of ___;", "answer": "scoffers"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: why Yahweh guides the psalmist in the paths of righteousness, per Psalm 23:3.',
   'Psalm 23:3', 'He restores my soul. He guides me in the paths of righteousness for his name''s sake.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "He restores my soul. He guides me in the paths of righteousness for his name''s ___.", "answer": "sake"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what comforts the psalmist along with the rod, per Psalm 23:4.',
   'Psalm 23:4', 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your ___, they comfort me.", "answer": "staff"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what is constantly before David, per Psalm 51:3.',
   'Psalm 51:3', 'For I know my transgressions. My sin is constantly before me.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "For I know my transgressions. My sin is constantly before ___.", "answer": "me"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what David asks to be restored to him, per Psalm 51:12.',
   'Psalm 51:12', 'Restore to me the joy of your salvation. Uphold me with a willing spirit.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Restore to me the joy of your ___. Uphold me with a willing spirit.", "answer": "salvation"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what God will not despise, per Psalm 51:17.',
   'Psalm 51:17', 'The sacrifices of God are a broken spirit. O God, you will not despise a broken and contrite heart.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "The sacrifices of God are a broken spirit. O God, you will not despise a broken and contrite ___.", "answer": "heart"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what we enter his gates with, per Psalm 100:4.',
   'Psalm 100:4', 'Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Enter into his gates with ___, and into his courts with praise. Give thanks to him, and bless his name.", "answer": "thanksgiving"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what will not harm the psalmist by night, per Psalm 121:6.',
   'Psalm 121:6', 'The sun will not harm you by day, nor the moon by night.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "The sun will not harm you by day, nor the ___ by night.", "answer": "moon"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh will not allow to be moved, per Psalm 121:3.',
   'Psalm 121:3', 'He will not allow your foot to be moved. He who keeps you will not slumber.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "He will not allow your ___ to be moved. He who keeps you will not slumber.", "answer": "foot"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what we praise him according to, per Psalm 150:2.',
   'Psalm 150:2', 'Praise him for his mighty acts! Praise him according to his excellent greatness!', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Praise him for his mighty acts! Praise him according to his excellent ___!", "answer": "greatness"}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: the second kind of cymbals named in Psalm 150:5.',
   'Psalm 150:5', 'Praise him with loud cymbals! Praise him with resounding cymbals!', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Praise him with loud cymbals! Praise him with ___ cymbals!", "answer": "resounding"}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh will keep, along with the psalmist, from all evil, per Psalm 121:7.',
   'Psalm 121:7', 'Yahweh will keep you from all evil. He will keep your soul.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Yahweh will keep you from all evil. He will keep your ___.", "answer": "soul"}', true, 13),
  ((select id from w), 'sequence', 'Put Psalm 150''s list of instruments and its closing call in the order they appear in the text.',
   'Psalm 150:3-6', 'Praise him with the sounding of the trumpet! Praise him with harp and lyre!; Praise him with tambourine and dancing! Praise him with stringed instruments and flute!; Praise him with loud cymbals! Praise him with resounding cymbals!; Let everything that has breath praise Yah! Praise Yah!', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["Trumpet, harp, and lyre (v.3)", "Tambourine and dancing, stringed instruments and flute (v.4)", "Loud cymbals and resounding cymbals (v.5)", "Let everything that has breath praise Yah (v.6)"], "correct_order": [0, 1, 2, 3]}', true, 14),
  ((select id from w), 'recall', 'Fill in the missing word: whom David went in to, per Psalm 51''s own superscription.',
   'Psalm 51, superscription', 'For the Chief Musician. A Psalm by David, when Nathan the prophet came to him, after he had gone in to Bathsheba.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "For the Chief Musician. A Psalm by David, when Nathan the prophet came to him, after he had gone in to ___.", "answer": "Bathsheba"}', true, 15)
;

with w as (select id from public.world where book_slug = 'proverbs')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, difficulty_tier, answer_key, is_boss_item, sort_order)
values
  -- ===================== PROVERBS — EASY TIER =====================
  ((select id from w), 'multiple_choice', 'According to Proverbs 3:5, in what does the text say to trust?',
   'Proverbs 3:5-6', 'Trust in Yahweh with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Yahweh", "your own understanding", "riches", "the king"], "correct_index": 0}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Proverbs 1:7, what is the beginning of knowledge?',
   'Proverbs 1:7', 'The fear of Yahweh is the beginning of knowledge, but the foolish despise wisdom and instruction.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["the fear of Yahweh", "wealth", "education", "age"], "correct_index": 0}', false, 2),
  ((select id from w), 'multiple_choice', 'Which verse says ''Train up a child in the way he should go''?',
   'Proverbs 22:6', 'Train up a child in the way he should go, and when he is old he will not depart from it.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Proverbs 22:6", "Proverbs 3:5", "Proverbs 1:7", "Proverbs 31:10"], "correct_index": 0}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Proverbs 16:18, what goes before destruction?',
   'Proverbs 16:18', 'Pride goes before destruction, and an arrogant spirit before a fall.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Pride", "Wisdom", "Humility", "Patience"], "correct_index": 0}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Proverbs 17:17, when is a brother born?',
   'Proverbs 17:17', 'A friend loves at all times; and a brother is born for adversity.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["for adversity", "for celebration", "for wealth", "for war"], "correct_index": 0}', false, 5),
  ((select id from w), 'multiple_choice', 'According to Proverbs 27:17, what does iron do to iron?',
   'Proverbs 27:17', 'Iron sharpens iron; so a man sharpens his friend''s countenance.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["sharpens it", "breaks it", "melts it", "bends it"], "correct_index": 0}', false, 6),
  ((select id from w), 'multiple_choice', 'According to Proverbs 31:30, what does the text call vain?',
   'Proverbs 31:30', 'Charm is deceitful, and beauty is vain; but a woman who fears Yahweh, she shall be praised.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["beauty", "wealth", "wisdom", "strength"], "correct_index": 0}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Proverbs 3:13, what is the man called who finds wisdom?',
   'Proverbs 3:13', 'Happy is the man who finds wisdom, the man who gets understanding.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["Happy", "Rich", "Powerful", "Famous"], "correct_index": 0}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Proverbs 4:23, what are you told to keep with all diligence?',
   'Proverbs 4:23', 'Keep your heart with all diligence, for out of it is the wellspring of life.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["your heart", "your money", "your land", "your name"], "correct_index": 0}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Proverbs 4:18, the path of the righteous is compared to what?',
   'Proverbs 4:18', 'But the path of the righteous is like the dawning light that shines more and more until the perfect day.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["the dawning light", "a river", "a tree", "a lamp"], "correct_index": 0}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what a gentle answer turns away, per Proverbs 15:1.',
   'Proverbs 15:1', 'A gentle answer turns away wrath, but a harsh word stirs up anger.', 'WEB', 1, 'easy',
   '{"type": "recall", "template": "A gentle answer turns away ___, but a harsh word stirs up anger.", "answer": "wrath"}', true, 11),
  ((select id from w), 'sequence', 'Put these three quotations in the order they occur in the book of Proverbs.',
   'Proverbs 1:7; 3:5-6; 22:6', 'The fear of Yahweh is the beginning of knowledge, but the foolish despise wisdom and instruction.; Trust in Yahweh with all your heart, and don''t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.; Train up a child in the way he should go, and when he is old he will not depart from it.', 'WEB', 1, 'easy',
   '{"type": "sequence", "items": ["“The fear of Yahweh is the beginning of knowledge...” (Proverbs 1:7)", "“Trust in Yahweh with all your heart...” (Proverbs 3:5-6)", "“Train up a child in the way he should go...” (Proverbs 22:6)"], "correct_order": [0, 1, 2]}', true, 12),
  ((select id from w), 'multiple_choice', 'According to Proverbs 22:1, what is more desirable than great riches?',
   'Proverbs 22:1', 'A good name is more desirable than great riches, and loving favor is better than silver and gold.', 'WEB', 1, 'easy',
   '{"type": "multiple_choice", "options": ["A good name", "Long life", "Many children", "Land"], "correct_index": 0}', true, 13),

  -- ===================== PROVERBS — HARD TIER =====================
  ((select id from w), 'recall', 'Fill in the missing word: what encircles the neck, alongside the garland, per Proverbs 1:8-9.',
   'Proverbs 1:8-9', 'My son, listen to your father''s instruction, and don''t forsake your mother''s teaching; for they will be a garland to grace your head, and chains around your neck.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "My son, listen to your father''s instruction, and don''t forsake your mother''s teaching; for they will be a garland to grace your head, and ___ around your neck.", "answer": "chains"}', false, 1),
  ((select id from w), 'recall', 'Fill in the missing word: what fearing Yahweh and departing from evil brings, per Proverbs 3:7-8.',
   'Proverbs 3:7-8', 'Don''t be wise in your own eyes. Fear Yahweh, and depart from evil. It will be health to your body, and nourishment to your bones.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Don''t be wise in your own eyes. Fear Yahweh, and depart from evil. It will be health to your body, and nourishment to your ___.", "answer": "bones"}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what nothing you desire can be compared to, per Proverbs 3:15.',
   'Proverbs 3:15', 'She is more precious than rubies. None of the things you can desire are to be compared to her.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "She is more precious than rubies. None of the things you can desire are to be compared to ___.", "answer": "her"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: which direction not to turn, per Proverbs 4:26-27.',
   'Proverbs 4:26-27', 'Make the path of your feet level. Let all of your ways be established. Don''t turn to the right hand nor to the left. Remove your foot from evil.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Make the path of your feet level. Let all of your ways be established. Don''t turn to the right hand nor to the ___. Remove your foot from evil.", "answer": "left"}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh''s eyes keep watch on, along with the evil, per Proverbs 15:3.',
   'Proverbs 15:3', 'Yahweh''s eyes are everywhere, keeping watch on the evil and the good.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Yahweh''s eyes are everywhere, keeping watch on the evil and the ___.", "answer": "good"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh directs, though a man''s heart plans his course, per Proverbs 16:9.',
   'Proverbs 16:9', 'A man''s heart plans his course, but Yahweh directs his steps.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "A man''s heart plans his course, but Yahweh directs his ___.", "answer": "steps"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: what not to boast about, per Proverbs 27:1.',
   'Proverbs 27:1', 'Don''t boast about tomorrow; for you don''t know what a day may bring.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Don''t boast about ___; for you don''t know what a day may bring.", "answer": "tomorrow"}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: whose praise you should not rely on your own, per Proverbs 27:2.',
   'Proverbs 27:2', 'Let another man praise you, and not your own mouth; a stranger, and not your own lips.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Let another man praise you, and not your own ___; a stranger, and not your own lips.", "answer": "mouth"}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what Yahweh is called of the rich and the poor alike, per Proverbs 22:2.',
   'Proverbs 22:2', 'The rich and the poor have this in common: Yahweh is the maker of them all.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "The rich and the poor have this in common: Yahweh is the ___ of them all.", "answer": "maker"}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: to whom the virtuous woman extends her hands, per Proverbs 31:20.',
   'Proverbs 31:20', 'She opens her arms to the poor; yes, she extends her hands to the needy.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "She opens her arms to the poor; yes, she extends her hands to the ___.", "answer": "needy"}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: what her children call the virtuous woman, per Proverbs 31:28.',
   'Proverbs 31:28', 'Her children rise up and call her blessed. Her husband also praises her:', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "Her children rise up and call her ___. Her husband also praises her:", "answer": "blessed"}', true, 11),
  ((select id from w), 'sequence', 'Given these four half-lines from two proverbs, pair each first half with its correct second half and place the two completed proverbs in the order they occur in the book.',
   'Proverbs 15:1; 16:18', 'A gentle answer turns away wrath, but a harsh word stirs up anger.; Pride goes before destruction, and an arrogant spirit before a fall.', 'WEB', 5, 'hard',
   '{"type": "sequence", "items": ["A gentle answer turns away wrath (Proverbs 15:1)", "but a harsh word stirs up anger (Proverbs 15:1)", "Pride goes before destruction (Proverbs 16:18)", "and an arrogant spirit before a fall (Proverbs 16:18)"], "correct_order": [0, 1, 2, 3]}', true, 12),
  ((select id from w), 'recall', 'Fill in the missing word: what wisdom''s return is better than, per Proverbs 3:14.',
   'Proverbs 3:14', 'For her good profit is better than getting silver, and her return is better than fine gold.', 'WEB', 5, 'hard',
   '{"type": "recall", "template": "For her good profit is better than getting silver, and her return is better than fine ___.", "answer": "gold"}', true, 13)
;
