-- Gen2Rev challenge ingest: Zechariah (World 38) and Malachi (World 39)
-- Generated from docs/content/zechariah.md and docs/content/malachi.md
-- Both books: theological review approved-with-changes, verbatim QA pass
-- (docs/CONTENT_REVIEW_LOG.md rows 38-39, docs/QA_SIGNOFF.md rows 38-39)
-- Zechariah 9:9, 11:12-13, 12:10, 13:7 and chapters 9-14 as a whole, plus 3:8-10/6:12-13
-- ("the Branch"), are permanently excluded per docs/content/zechariah.md's "Contested Territory".
-- Malachi 1:2-3 and 2:10-16 are permanently excluded per docs/content/malachi.md's
-- "Contested Territory". Malachi 4:4-6 (Elijah's return) is the deliberate capstone of this
-- whole 39-book Old Testament expansion -- see docs/content/malachi.md's closing-capstone note.

with w as (select id from public.world where book_slug = 'zechariah')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh of Armies say through Zechariah, calling the people back to him?', 'Zechariah 1:3', 'Therefore tell them, Yahweh of Armies says: ''Return to me,'' says Yahweh of Armies, ''and I will return to you,'' says Yahweh of Armies.', 'WEB', 2,
   '{"type": "recall", "template": "Therefore tell them, Yahweh of Armies says: ''___ to me,'' says Yahweh of Armies, ''and I will return to you,'' says Yahweh of Armies.", "answer": "Return"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Zechariah 1:4, what did the former prophets tell the fathers to return from?', 'Zechariah 1:4', 'Don''t you be like your fathers, to whom the former prophets proclaimed, saying: Yahweh of Armies says, ''Return now from your evil ways and from your evil doings;'' but they didn''t hear nor listen to me, says Yahweh.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["Their evil ways and their evil doings", "Their false idols", "Their broken promises", "Their foreign alliances"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what role did Satan play as he stood at Joshua''s right hand?', 'Zechariah 3:1', 'He showed me Joshua the high priest standing before Yahweh''s angel, and Satan standing at his right hand to be his adversary.', 'WEB', 3,
   '{"type": "recall", "template": "He showed me Joshua the high priest standing before Yahweh''s angel, and Satan standing at his right hand to be his ___.", "answer": "adversary"}', false, 3),
  ((select id from w), 'multiple_choice', 'According to Zechariah 3:4, what did Yahweh''s angel tell Joshua''s attendants to do with his filthy garments?', 'Zechariah 3:4', 'He answered and spoke to those who stood before him, saying, ''Take the filthy garments off him.'' To him he said, ''Behold, I have caused your iniquity to pass from you, and I will clothe you with rich clothing.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Take them off him", "Wash them clean", "Burn them", "Replace only the turban"], "correct_index": 0}', false, 4),
  ((select id from w), 'recall', 'Fill in the missing word: what did Zechariah ask them to set on Joshua''s head?', 'Zechariah 3:5', 'I said, ''Let them set a clean turban on his head.'' So they set a clean turban on his head, and clothed him; and Yahweh''s angel was standing by.', 'WEB', 2,
   '{"type": "recall", "template": "I said, ''Let them set a clean ___ on his head.'' So they set a clean turban on his head, and clothed him; and Yahweh''s angel was standing by.", "answer": "turban"}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh''s word to Zerubbabel say it would not be accomplished by?', 'Zechariah 4:6', 'Then he answered and spoke to me, saying, ''This is Yahweh''s word to Zerubbabel, saying, Not by might, nor by power, but by my Spirit, says Yahweh of Armies.''', 'WEB', 1,
   '{"type": "recall", "template": "''This is Yahweh''s word to Zerubbabel, saying, Not by might, nor by power, but by my ___, says Yahweh of Armies.''", "answer": "Spirit"}', true, 6),
  ((select id from w), 'multiple_choice', 'According to Zechariah 4:2-3, what did Zechariah see in the vision of the golden lampstand?', 'Zechariah 4:2-3', 'I said, ''I have seen, and behold, a lamp stand all of gold, with its bowl on the top of it, and its seven lamps on it; there are seven pipes to each of the lamps which are on the top of it;'' and two olive trees by it, one on the right side of the bowl, and the other on the left side of it.', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["A lamp stand of gold with seven lamps and two olive trees", "A scroll and a measuring rod", "Four horns and four craftsmen", "A woman sitting in a basket"], "correct_index": 0}', false, 7),
  ((select id from w), 'recall', 'Fill in the missing word: what was the width of the flying scroll Zechariah saw?', 'Zechariah 5:2', 'He said to me, ''What do you see?'' I answered, ''I see a flying scroll; its length is twenty cubits, and its width ten cubits.''', 'WEB', 3,
   '{"type": "recall", "template": "I answered, ''I see a flying scroll; its length is twenty cubits, and its width ___ cubits.''", "answer": "ten"}', false, 8),
  ((select id from w), 'multiple_choice', 'According to Zechariah 5:1-2, how long was the flying scroll?', 'Zechariah 5:1-2', 'Then again I lifted up my eyes and saw, and behold, a flying scroll. He said to me, ''What do you see?'' I answered, ''I see a flying scroll; its length is twenty cubits, and its width ten cubits.''', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["Twenty cubits", "Ten cubits", "Thirty cubits", "Fifty cubits"], "correct_index": 0}', false, 9),
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh of Armies say to show every man to his brother?', 'Zechariah 7:9', 'Thus has Yahweh of Armies spoken, saying, ''Execute true judgment, and show kindness and compassion every man to his brother.', 'WEB', 2,
   '{"type": "recall", "template": "Thus has Yahweh of Armies spoken, saying, ''Execute true judgment, and show kindness and ___ every man to his brother.", "answer": "compassion"}', false, 10),
  ((select id from w), 'multiple_choice', 'According to Zechariah 7:10, whom does Yahweh say not to oppress?', 'Zechariah 7:10', 'Don''t oppress the widow, the fatherless, the foreigner, nor the poor; and let none of you devise evil against his brother in your heart.''', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The widow, the fatherless, the foreigner, and the poor", "The priests, the elders, and the scribes", "The merchants and the tax collectors", "The king and his officials"], "correct_index": 0}', false, 11),
  ((select id from w), 'recall', 'Fill in the missing word: what will the streets of restored Jerusalem be full of boys and girls doing?', 'Zechariah 8:5', '''The streets of the city will be full of boys and girls playing in its streets.''', 'WEB', 1,
   '{"type": "recall", "template": "''The streets of the city will be full of boys and girls ___ in its streets.''", "answer": "playing"}', true, 12),
  ((select id from w), 'multiple_choice', 'According to Zechariah 8:7-8, from where does Yahweh promise to save his people?', 'Zechariah 8:7-8', 'Yahweh of Armies says: ''Behold, I will save my people from the east country and from the west country.'' ''I will bring them, and they will dwell within Jerusalem. They will be my people, and I will be their God, in truth and in righteousness.''', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["The east country and the west country", "The north country and the south country", "Egypt and Assyria", "Babylon and Persia"], "correct_index": 0}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: what does Yahweh say about devising evil and loving a false oath?', 'Zechariah 8:16-17', 'These are the things that you shall do: speak every man the truth with his neighbor. Execute the judgment of truth and peace in your gates, and let none of you devise evil in your hearts against his neighbor, and love no false oath; for all these are things that I hate," says Yahweh.', 'WEB', 2,
   '{"type": "recall", "template": "and let none of you devise evil in your hearts against his neighbor, and love no false oath; for all these are things that I ___,\" says Yahweh.", "answer": "hate"}', false, 14),
  ((select id from w), 'multiple_choice', 'According to Zechariah 8:16, what does Yahweh tell the people to speak with their neighbor?', 'Zechariah 8:16', 'These are the things that you shall do: speak every man the truth with his neighbor. Execute the judgment of truth and peace in your gates,', 'WEB', 1,
   '{"type": "multiple_choice", "options": ["The truth", "Kind words only", "Blessings", "Their grievances"], "correct_index": 0}', false, 15),
  ((select id from w), 'sequence', 'Order Zechariah 3:1-5 as it happens.', 'Zechariah 3:1-5', 'Joshua stands accused; Yahweh rebukes Satan; the filthy garments are removed; clean garments and a turban are given.', 'WEB', 3,
   '{"type": "sequence", "items": ["Joshua the high priest stands before Yahweh''s angel, with Satan standing at his right hand to accuse him (3:1)", "Yahweh rebukes Satan: ''Yahweh rebuke you, Satan!'' (3:2)", "The filthy garments are removed from Joshua (3:4)", "Joshua is clothed with rich clothing and a clean turban is set on his head (3:5)"], "correct_order": [0, 1, 2, 3]}', false, 16),
  ((select id from w), 'sequence', 'Put these seven pivotal passages in the order they appear in Zechariah 1-8.', 'Zechariah 1-8', 'A call to repentance; the vision of Joshua restored; the golden lampstand; the flying scroll; true justice and compassion; the restoration of Jerusalem; speak the truth.', 'WEB', 4,
   '{"type": "sequence", "items": ["A call to repentance: ''Return to me, and I will return to you'' (1:1-6)", "The vision of Joshua the high priest restored from filthy garments to clean ones (3:1-5)", "The golden lampstand: ''Not by might, nor by power, but by my Spirit'' (4:1-7)", "The flying scroll, a curse against thieves and those who swear falsely (5:1-4)", "True justice and compassion for the widow, the fatherless, and the poor (7:8-10)", "The restoration of Jerusalem: streets full of boys and girls playing (8:3-8)", "Speak the truth, love no false oath (8:16-17)"], "correct_order": [0, 1, 2, 3, 4, 5, 6]}', true, 17)
;

with w as (select id from public.world where book_slug = 'malachi')
insert into public.challenge (world_id, type, prompt, verse_ref, verse_text, translation, difficulty_rank, answer_key, is_boss_item, sort_order)
values
  ((select id from w), 'recall', 'Fill in the missing word: what did Yahweh say was due him as a father, if the priests are his sons?', 'Malachi 1:6', 'A son honors his father, and a servant his master. If I am a father, then where is my honor? And if I am a master, where is the respect due me?" says Yahweh of Armies to you priests who despise my name. "You say, ''How have we despised your name?''', 'WEB', 2,
   '{"type": "recall", "template": "A son honors his father, and a servant his master. If I am a father, then where is my ___? And if I am a master, where is the respect due me?", "answer": "honor"}', false, 1),
  ((select id from w), 'multiple_choice', 'According to Malachi 1:8, what kind of animals were the priests offering that Yahweh calls evil?', 'Malachi 1:8', 'When you offer the blind for sacrifice, isn''t that evil? And when you offer the lame and sick, isn''t that evil? Present it now to your governor! Will he be pleased with you? Or will he accept your person?" says Yahweh of Armies.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The blind, the lame, and the sick", "The old and the diseased", "The stolen and the blemished", "The firstborn and the unclean"], "correct_index": 0}', false, 2),
  ((select id from w), 'recall', 'Fill in the missing word: what kind of offering did Yahweh say would be offered to his name among the nations?', 'Malachi 1:11', 'For from the rising of the sun even to its going down, my name is great among the nations, and in every place incense will be offered to my name, and a pure offering; for my name is great among the nations," says Yahweh of Armies.', 'WEB', 3,
   '{"type": "recall", "template": "For from the rising of the sun even to its going down, my name is great among the nations, and in every place incense will be offered to my name, and a ___ offering; for my name is great among the nations,\" says Yahweh of Armies.", "answer": "pure"}', false, 3),
  ((select id from w), 'recall', 'Fill in the missing word: what will Yahweh''s messenger prepare before him?', 'Malachi 3:1', 'Behold, I send my messenger, and he will prepare the way before me! The Lord, whom you seek, will suddenly come to his temple. Behold, the messenger of the covenant, whom you desire, is coming!" says Yahweh of Armies.', 'WEB', 2,
   '{"type": "recall", "template": "Behold, I send my messenger, and he will prepare the ___ before me! The Lord, whom you seek, will suddenly come to his temple.", "answer": "way"}', false, 4),
  ((select id from w), 'multiple_choice', 'According to Malachi 3:2, what two things is the one who comes compared to?', 'Malachi 3:2', 'But who can endure the day of his coming? And who will stand when he appears? For he is like a refiner''s fire, and like launderers'' soap;', 'WEB', 3,
   '{"type": "multiple_choice", "options": ["A refiner''s fire and launderers'' soap", "A consuming flame and a sharp sword", "The sun and the moon", "A shepherd''s staff and rod"], "correct_index": 0}', false, 5),
  ((select id from w), 'recall', 'Fill in the missing word: because Yahweh doesn''t change, what has not happened to the sons of Jacob?', 'Malachi 3:6', 'For I, Yahweh, don''t change; therefore you, sons of Jacob, are not consumed.', 'WEB', 3,
   '{"type": "recall", "template": "For I, Yahweh, don''t change; therefore you, sons of Jacob, are not ___.", "answer": "consumed"}', false, 6),
  ((select id from w), 'recall', 'Fill in the missing word: where did Yahweh tell the people to bring the whole tithe?', 'Malachi 3:10', 'Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this," says Yahweh of Armies, "if I will not open you the windows of heaven, and pour you out a blessing, that there will not be enough room for.', 'WEB', 1,
   '{"type": "recall", "template": "Bring the whole tithe into the ___, that there may be food in my house, and test me now in this,\" says Yahweh of Armies, \"if I will not open you the windows of heaven, and pour you out a blessing, that there will not be enough room for.", "answer": "storehouse"}', false, 7),
  ((select id from w), 'multiple_choice', 'According to Malachi 3:8, what does Yahweh say the people have robbed him of?', 'Malachi 3:8', 'Will a man rob God? Yet you rob me! But you say, ''How have we robbed you?'' In tithes and offerings.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["Tithes and offerings", "Sacrifices and vows", "Praise and worship", "Firstfruits and Sabbaths"], "correct_index": 0}', false, 8),
  ((select id from w), 'recall', 'Fill in the missing word: what kind of book was written before Yahweh for those who feared him?', 'Malachi 3:16', 'Then those who feared Yahweh spoke one with another; and Yahweh listened and heard, and a book of memory was written before him for those who feared Yahweh and who honored his name.', 'WEB', 2,
   '{"type": "recall", "template": "Then those who feared Yahweh spoke one with another; and Yahweh listened and heard, and a book of ___ was written before him for those who feared Yahweh and who honored his name.", "answer": "memory"}', false, 9),
  ((select id from w), 'multiple_choice', 'According to Malachi 3:18, between whom will the people learn to discern?', 'Malachi 3:18', 'Then you shall return and discern between the righteous and the wicked, between him who serves God and him who doesn''t serve him.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["The righteous and the wicked", "The rich and the poor", "The priest and the layperson", "The Jew and the foreigner"], "correct_index": 0}', false, 10),
  ((select id from w), 'recall', 'Fill in the missing word: with what will the sun of righteousness arise for those who fear Yahweh''s name?', 'Malachi 4:2', 'But to you who fear my name shall the sun of righteousness arise with healing in its wings. You will go out and leap like calves of the stall.', 'WEB', 1,
   '{"type": "recall", "template": "But to you who fear my name shall the sun of righteousness arise with healing in its ___. You will go out and leap like calves of the stall.", "answer": "wings"}', false, 11),
  ((select id from w), 'multiple_choice', 'According to Malachi 4:1, what will happen to the proud and wicked on the day that comes?', 'Malachi 4:1', 'For behold, the day comes, burning like a furnace, when all the proud and all who work wickedness will be stubble. The day that comes will burn them up," says Yahweh of Armies, "so that it will leave them neither root nor branch.', 'WEB', 2,
   '{"type": "multiple_choice", "options": ["They will be burned up like stubble", "They will be scattered like chaff", "They will be swallowed by the earth", "They will be turned to stone"], "correct_index": 0}', false, 12),
  ((select id from w), 'recall', 'Fill in the missing word: whose law were the people told to remember?', 'Malachi 4:4', 'Remember the law of Moses my servant, which I commanded to him in Horeb for all Israel, even statutes and ordinances.', 'WEB', 1,
   '{"type": "recall", "template": "Remember the law of ___ my servant, which I commanded to him in Horeb for all Israel, even statutes and ordinances.", "answer": "Moses"}', false, 13),
  ((select id from w), 'recall', 'Fill in the missing word: who did Yahweh promise to send before the great and terrible day of Yahweh?', 'Malachi 4:5', 'Behold, I will send you Elijah the prophet before the great and terrible day of Yahweh comes.', 'WEB', 1,
   '{"type": "recall", "template": "Behold, I will send you ___ the prophet before the great and terrible day of Yahweh comes.", "answer": "Elijah"}', true, 14),
  ((select id from w), 'multiple_choice', 'According to Malachi 4:6, whose hearts will the coming Elijah turn?', 'Malachi 4:6', 'He will turn the hearts of the fathers to the children and the hearts of the children to their fathers, lest I come and strike the earth with a curse.', 'WEB', 5,
   '{"type": "multiple_choice", "options": ["The hearts of the fathers to the children, and the children to the fathers", "The hearts of the priests to the people", "The hearts of the kings to their subjects", "The hearts of Israel to the nations"], "correct_index": 0}', true, 15),
  ((select id from w), 'sequence', 'Order the pivotal-passage blocks as they appear in the book of Malachi.', 'Malachi 1-4', 'Corrupt offerings; the coming messenger; tithing; the book of remembrance; the day of Yahweh; Elijah''s return.', 'WEB', 3,
   '{"type": "sequence", "items": ["Corrupt offerings: the priests offer blind, lame, and sick animals (1:6-11)", "The coming messenger who will prepare the way and purify the sons of Levi (3:1-3)", "Tithing: ''Will a man rob God?'' and the invitation to test him (3:6-10)", "The book of remembrance for those who feared Yahweh (3:16-18)", "The day of Yahweh: the sun of righteousness rising with healing in its wings (4:1-3)", "Remembering the Law of Moses and the promise of Elijah''s return (4:4-6)"], "correct_order": [0, 1, 2, 3, 4, 5]}', false, 16),
  ((select id from w), 'sequence', 'Given these three quotations, place them in the order they occur in the book and match each to its reference.', 'Malachi 3:1; 3:10; 4:5', 'The coming messenger; the tithe instruction; the promise of Elijah''s return.', 'WEB', 4,
   '{"type": "sequence", "items": ["''Behold, I send my messenger, and he will prepare the way before me!'' -- Malachi 3:1", "''Bring the whole tithe into the storehouse, that there may be food in my house.'' -- Malachi 3:10", "''Behold, I will send you Elijah the prophet before the great and terrible day of Yahweh comes.'' -- Malachi 4:5"], "correct_order": [0, 1, 2]}', true, 17)
;
